### PR TITLE
KOGITO-6265 Use Microprofile Config for Quarkus codegen

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Review by nmirasch — APPROVED** [review]

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
Jenkins rerun kogito-apps tests

**Comment by cristianonicolai** [comment]
Jenkins rerun kogito-apps tests

**Review by tiagodolphine — APPROVED** [review]
LGTM, great work.

**Review by MarianMacik — APPROVED** [review]

**Pull request merged**
