### PR TITLE
Backports for 0.11.1

### PR DESCRIPTION
**Pull request by mariofusco**
- https://github.com/kiegroup/kogito-runtimes/pull/604
- https://github.com/kiegroup/kogito-apps/pull/308
- https://github.com/kiegroup/kogito-examples/pull/289

### CODE REVIEW

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by mariofusco** [comment]
@cristianonicolai is this correct? https://github.com/kiegroup/kogito-runtimes/blob/0.11.x/.mvn/maven.config 
I believe that one is the cause of the problem with archetypes. Can you please check?

**Comment by evacchi** [comment]
@mariofusco maybe there are some other places where we have to bump (?) there is a NoSuchMethod error in the build

**Comment by cristianonicolai** [comment]
@mariofusco @evacchi I guess the maven version needs to be update to 0.11.1-SNAPSHOT?

**Comment by evacchi** [comment]
- kogito-runtimes pipeline step is green
- kogito-apps pipeline step is green
- kogito-examples is green on build for kogito-examples is green on https://github.com/kiegroup/kogito-examples/pull/289

merging!

**Pull request merged**
