### PR TITLE
KOGITO-4911 - add test container wait condition

### PR DESCRIPTION
**Pull request by r00ta**
JIRA: https://issues.redhat.com/browse/KOGITO-4911

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.md)
- [x] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/master/kogito-ide-config)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

* <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

### CODE REVIEW

**Review by danielezonca — APPROVED** [review]

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by danielezonca** [comment]
@r00ta 
Previous execution failed because of timeout on Kafka test, it's strange 🤔 
```
09:37:41,506 [INFO] --- maven-failsafe-plugin:2.22.2:integration-test (default) @ kafka-persistence-addon ---
09:37:41,513 [INFO] 
09:37:41,513 [INFO] -------------------------------------------------------
09:37:41,513 [INFO]  T E S T S
09:37:41,513 [INFO] -------------------------------------------------------
09:37:42,017 [INFO] Running org.kie.kogito.persistence.kafka.KafkaProcessInstancesIT
Cancelling nested steps due to timeout
Sending interrupt signal to process
18:55:21,389 [INFO] 
```

**Comment by r00ta** [comment]
jenkins retest this please

**Comment by r00ta** [comment]
jenkins retest this please

**Comment by jstastny-cz** [comment]
> @r00ta
> Previous execution failed because of timeout on Kafka test, it's strange 
> 
> ```
> 09:37:41,506 [INFO] --- maven-failsafe-plugin:2.22.2:integration-test (default) @ kafka-persistence-addon ---
> 09:37:41,513 [INFO] 
> 09:37:41,513 [INFO] -------------------------------------------------------
> 09:37:41,513 [INFO]  T E S T S
> 09:37:41,513 [INFO] -------------------------------------------------------
> 09:37:42,017 [INFO] Running org.kie.kogito.persistence.kafka.KafkaProcessInstancesIT
> Cancelling nested steps due to timeout
> Sending interrupt signal to process
> 18:55:21,389 [INFO] 
> ```

I've seen this failure yesterday too, it might be that the image registry was inaccessible.

**Pull request merged**
