### PR TITLE
KOGITO-1179 Unable to execute a job with native application

### PR DESCRIPTION
**Pull request by tiagodolphine**
https://issues.redhat.com/browse/KOGITO-1179

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](CONTRIBUTING.md)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Review by cristianonicolai — APPROVED** [review]

**Review by sutaakar — APPROVED** [review]

**Comment by tiagodolphine** [comment]
@evacchi would you mind taking a look at this one? otherwise, I think we are ok to merge it.
Thanks

**Comment by tiagodolphine** [comment]
jenkins retest this

**Comment by tiagodolphine** [comment]
jenkins retest this

**Pull request merged**
