### PR TITLE
[1.8.x] KOGITO-5405 Bump quarkus 2.0.0.Final 

### PR DESCRIPTION
**Pull request by evacchi**
- https://github.com/kiegroup/kogito-runtimes/pull/1395
- https://github.com/kiegroup/kogito-apps/pull/902
- https://github.com/kiegroup/kogito-examples/pull/741

### CODE REVIEW

**Comment by evacchi** [comment]
superseded by https://github.com/kiegroup/kogito-runtimes/pull/1392

**Comment by radtriste** [comment]
jenkins rerun optaplanner tests

**Review by cristianonicolai — APPROVED** [review]

**Comment by evacchi** [comment]
and of course there's an occurrence of `@Named("default-kafka-broker")` on `kogito-examples`

**Comment by evacchi** [comment]
and obviously in apps, because why not :D

**Comment by evacchi** [comment]
jenkins retest this

**Comment by evacchi** [comment]
jenkins rerun examples tests

**Pull request merged**
