### PR TITLE
[1.24.x] KOGITO-7541 - Expose host port for Data Index Dev Service (#2331)

### PR DESCRIPTION
**Pull request by cristianonicolai**
Cherry-pick from main

### CODE REVIEW

**Comment by kie-ci3** [comment]
**(tests) - kogito-examples job** `#5` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.24.x/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/5/display/redirect

**Test results:**
- PASSED: 516
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.24.x/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/5/testReport/org.kie.kogito.examples/CorrelationIT/Build_projects___testCorrelation/">Build projects / org.kie.kogito.examples.CorrelationIT.testCorrelation</a></summary>
org.awaitility.core.ConditionTimeoutException: <br/>Assertion condition defined as a lambda expression in org.kie.kogito.examples.CorrelationIT 1 expectation failed.<br/>JSON path processInstanceId doesn't match.<br/>Expected: not null<br/>  Actual: null<br/> within 2 minutes.<br/>	at org.kie.kogito.examples.CorrelationIT.testCorrelation(CorrelationIT.java:74)<br/>Caused by: java.lang.AssertionError: <br/>1 expectation failed.<br/>JSON path processInstanceId doesn't match.<br/>Expected: not null<br/>  Actual: null<br/><br/>	at org.kie.kogito.examples.CorrelationIT.lambda$testCorrelation$1(CorrelationIT.java:80)<br/>
</details>

**Comment by cristianonicolai** [comment]
Jenkins rerun kogito-examples tests

**Comment by kie-ci3** [comment]
**(tests) - kogito-examples job** `#6` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.24.x/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/6/display/redirect

**Test results:**
- PASSED: 516
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.24.x/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/6/testReport/org.kie.kogito.quarkus.outbox/OutboxIT/___/">org.kie.kogito.quarkus.outbox.OutboxIT.(?)</a></summary>
java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [8080, 49183] should be listening)<br/>	at org.kie.kogito.quarkus.outbox.OutboxIT.before(OutboxIT.java:86)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [8080, 49183] should be listening)<br/>
</details>

**Comment by cristianonicolai** [comment]
Jenkins rerun kogito-examples tests

**Pull request merged**
