### PR TITLE
KOGITO-5854 - Remove kogito-serverless-workflow-runtime from kogito-s…

### PR DESCRIPTION
**Pull request by MarianMacik**
…pring-boot-starter

[KOGITO-5854](https://issues.redhat.com/browse/KOGITO-5854)

PR set:
* #1593
* kiegroup/kogito-examples#881

### CODE REVIEW

**Review by ricardozanini — APPROVED** [review]

**Comment by ricardozanini** [comment]
I think we need to change the example as well: https://github.com/kiegroup/kogito-examples/blob/main/serverless-workflow-greeting-springboot/pom.xml#L37

**Comment by MarianMacik** [comment]
@ricardozanini Already wrote you on the chat :)

**Comment by MarianMacik** [comment]
jenkins rerun runtimes tests

**Comment by jstastny-cz** [comment]
Should there be a kogito-examples PR as part of the ensemble? To get the builds pass.

**Comment by MarianMacik** [comment]
@jstastny-cz yes, I have fixed it locally yesterday, just need to create a PR.

**Comment by MarianMacik** [comment]
PR for kogito-examples added.

jenkins rerun examples tests

**Review by jstastny-cz — APPROVED** [review]

**Pull request merged**
