### PR TITLE
KOGITO-4075 - Add microprofile default config for tracing addon

### PR DESCRIPTION
**Pull request by r00ta**
jira: https://issues.redhat.com/browse/KOGITO-4075

This PR aims to simplify the configuration of the tracing addon from the user. The default configuration is now placed inside the module, so the user does not have to specify the kafka topics and so on. 

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.md)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by r00ta** [comment]
kogito-example pr: https://github.com/kiegroup/kogito-examples/pull/492

**Review by danielezonca — APPROVED** [review]

**Review by jiripetrlik — APPROVED** [review]
LGTM

**Comment by jiripetrlik** [comment]
@r00ta Maybe I miss something. But can we do some readme with info about these parameters and its default values to make it easier to understand how to run it?

**Review by kostola — APPROVED** [review]

**Comment by r00ta** [comment]
> @r00ta Maybe I miss something. But can we do some readme with info about these parameters and its default values to make it easier to understand how to run it?

Hi @jiripetrlik , you're right! There was no doc on the configuration. I've added it with this PR https://github.com/kiegroup/kogito-examples/pull/492 . Let me know if this looks good to you and thanks for the catch

**Pull request merged**
