### PR TITLE
[1.27.x] KOGITO-7890 - Use operation id as work item handler name

### PR DESCRIPTION
**Pull request by cristianonicolai**
Cherry pick of https://github.com/kiegroup/kogito-runtimes/pull/2443

### CODE REVIEW

**Comment by cristianonicolai** [comment]
jenkins run quarkus-lts

**Comment by kie-ci3** [comment]
**(tests) - kogito-examples job** `#11` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.27.x/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/11/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] sh<br/>[2022-09-12T04:37:38.346Z] + du -h -d3 /home/jenkins/workspace<br/>[2022-09-12T04:37:38.346Z] 2.8M	/home/jenkins/workspace/KIE/kogito/1.27.x<br/>[2022-09-12T04:37:38.346Z] 2.8M	/home/jenkins/workspace/KIE/kogito<br/>[2022-09-12T04:37:38.346Z] du: cannot access ‘/home/jenkins/workspace/KIE/optaplanner/8.27.x/nightly.quarkus-branch/optaplanner-all_ws-cleanup_1662957454132/optaplanner/optaplanner-persistence/optaplanner-persistence-jackson/target/surefire-reports/org.optaplanner.persistence.jackson.api.score.buildin.bendablelong.BendableLongScoreJacksonRoundTripTest.txt’: No such file or directory<br/>[2022-09-12T04:37:38.346Z] du: cannot access ‘/home/jenkins/workspace/KIE/optaplanner/8.27.x/nightly.quarkus-branch/optaplanner-all_ws-cleanup_1662957454132/optaplanner/optaplanner-persistence/optaplanner-persistence-jackson/target/surefire-reports/TEST-org.optaplanner.persistence.jackson.api.score.buildin.bendablelong.BendableLongScoreJacksonRoundTripTest.xml’: No such file or directory<br/>[2022-09-12T04:37:38.346Z] du: cannot access ‘/home/jenkins/workspace/KIE/optaplanner/8.27.x/nightly.quarkus-branch/optaplanner-all_ws-cleanup_1662957454132/optaplanner/optaplanner-persistence/optaplanner-persistence-jackson/target/surefire-reports/org.optaplanner.persistence.jackson.api.score.buildin.simplebigdecimal.SimpleBigDecimalScoreJacksonRoundTripTest.txt’: No such file or directory<br/>[2022-09-12T04:37:38.346Z] du: cannot access ‘/home/jenkins/workspace/KIE/optaplanner/8.27.x/nightly.quarkus-branch/optaplanner-all_ws-cleanup_1662957454132/optaplanner/optaplanner-persistence/optaplanner-persistence-jackson/target/surefire-reports/TEST-org.optaplanner.persistence.jackson.api.score.buildin.simplebigdecimal.SimpleBigDecimalScoreJacksonRoundTripTest.xml’: No such file or directory<br/>[2022-09-12T04:37:38.346Z] du: cannot access ‘/home/jenkins/workspace/KIE/optaplanner/8.27.x/nightly.quarkus-branch/optaplanner-all_ws-cleanup_1662957454132/optaplanner/optaplanner-persistence/optaplanner-persistence-jackson/target/surefire-reports/org.optaplanner.persistence.jackson.api.score.buildin.hardmediumsoftbigdecimal.HardMediumSoftBigDecimalScoreJacksonRoundTripTest.txt’: No such file or directory<br/>[2022-09-12T04:37:38.346Z] du: cannot access ‘/home/jenkins/workspace/KIE/optaplanner/8.27.x/nightly.quarkus-branch/optaplanner-all_ws-cleanup_1662957454132/optaplanner/optaplanner-persistence/optaplanner-persistence-jackson/target/surefire-reports/TEST-org.optaplanner.persistence.jackson.api.score.buildin.hardmediumsoftbigdecimal.HardMediumSoftBigDecimalScoreJacksonRoundTripTest.xml’: No such file or directory<br/>[2022-09-12T04:37:38.346Z] 975M	/home/jenkins/workspace/KIE/optaplanner/8.27.x<br/>[2022-09-12T04:37:38.346Z] 975M	/home/jenkins/workspace/KIE/optaplanner<br/>[2022-09-12T04:37:38.346Z] 977M	/home/jenkins/workspace/KIE<br/>[2022-09-12T04:37:38.346Z] 977M	/home/jenkins/workspace<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Install build-chain tool)<br/>Stage "Install build-chain tool" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>Stage "Build projects" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Sonar analysis)<br/>Stage "Sonar analysis" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space after build)<br/>Stage "check space after build" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-09-12T04:37:39.127Z] + wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.27.x/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/11/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by cristianonicolai** [comment]
jenkins run quarkus-lts

**Review by radtriste — APPROVED** [review]

**Review by fjtirado — CHANGES_REQUESTED** [review]
We need to wait for the pom update to refer to the right quarkiverse open api release and the integration test to verifty that the isssue is fixed. 
By itself, this PR is not fixing anything

**Comment by cristianonicolai** [comment]
jenkins run quarkus-lts

**Review by fjtirado — APPROVED** [review]
Thanks Cristiano

**Comment by cristianonicolai** [comment]
jenkins run quarkus-lts

**Comment by kie-ci3** [comment]
**(tests) - kogito-runtimes job** `#14` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.27.x/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/14/display/redirect

**Test results:**
- PASSED: 2895
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.27.x/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/14/testReport/org.kie.kogito.quarkus.it.openapi.client/ApiWithSecurityContextIT/verifyAuthHeadersOpenApi2_0/">org.kie.kogito.quarkus.it.openapi.client.ApiWithSecurityContextIT.verifyAuthHeadersOpenApi2_0</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <201> but was <500>.<br/><br/>	at org.kie.kogito.quarkus.it.openapi.client.ApiWithSecurityContextIT.verifyAuthHeadersOpenApi2_0(ApiWithSecurityContextIT.java:62)<br/>
</details>

**Comment by kie-ci3** [comment]
**(quarkus-lts) - kogito-runtimes job** `#15` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.27.x/job/pullrequest.quarkus-lts/job/kogito-runtimes.quarkus-lts.kogito-runtimes/15/display/redirect

**Test results:**
- PASSED: 1935
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.27.x/job/pullrequest.quarkus-lts/job/kogito-runtimes.quarkus-lts.kogito-runtimes/15/testReport/org.kie.kogito.quarkus.it.openapi.client/ApiWithSecurityContextIT/verifyAuthHeadersOpenApi2_0/">org.kie.kogito.quarkus.it.openapi.client.ApiWithSecurityContextIT.verifyAuthHeadersOpenApi2_0</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <201> but was <500>.<br/><br/>	at org.kie.kogito.quarkus.it.openapi.client.ApiWithSecurityContextIT.verifyAuthHeadersOpenApi2_0(ApiWithSecurityContextIT.java:62)<br/>
</details>

**Comment by fjtirado** [comment]
@cristianonicolai Looks like there is a related issue in one of the openapi test

**Comment by cristianonicolai** [comment]
jenkins run quarkus-lts

**Pull request merged**
