### PR TITLE
DROOLS-5601 Review kogito-runtimes DMN examples version in codebase

### PR DESCRIPTION
**Pull request by tarilabs**

### CODE REVIEW

**Comment by tarilabs** [comment]
```
New failing - 1
testProcessSignals – org.kie.kogito.integrationtests.quarkus.SignalProcessTest
```

?? 🤷‍♂️

**Comment by tarilabs** [comment]
Jenkins test again

**Comment by tarilabs** [comment]
Jenkins retest this

**Review by hellowdan — APPROVED** [review]

**Comment by tarilabs** [comment]
```
New failing - 6
testDeleteTimerCycle – org.kie.kogito.it.jobs.ProcessTimerIT
2s
testBoundaryTimersOnTask – org.kie.kogito.it.jobs.ProcessTimerIT
<1s
testTimerCycle – org.kie.kogito.it.jobs.ProcessTimerIT
<1s
testTimers – org.kie.kogito.it.jobs.ProcessTimerIT
<1s
testDeleteBoundaryTimersOnTask – org.kie.kogito.it.jobs.ProcessTimerIT
<1s
testCancelTimer – org.kie.kogito.it.jobs.ProcessTimerIT
```

??? 🤷‍♂️ 🎱 

Jenkins retest this

**Pull request merged**
