### PR TITLE
[KOGITO-5459] MultiCloudEvent addon fails if there is no consumer

### PR DESCRIPTION
**Pull request by fjtirado**
This is quick fix for a dummy error I found while doing performance testing

### CODE REVIEW

**Review by tiagodolphine — APPROVED** [review]

**Comment by tiagodolphine** [comment]
LGTM, @fjtirado can you add some test to check this condition?

**Comment by fjtirado** [comment]
jenkins rerun runtimes tests

**Comment by fjtirado** [comment]
jenkins rerun examples tests

**Review by ricardozanini — APPROVED** [review]

**Comment by fjtirado** [comment]
jenkins rerun examples tests

**Comment by fjtirado** [comment]
jenkins rerun examples tests

**Comment by fjtirado** [comment]
jenkins rerun examples tests

**Comment by fjtirado** [comment]
jenkins rerun examples tests

**Comment by fjtirado** [comment]
jenkins rerun examples tests

**Comment by fjtirado** [comment]
jenkins rerun examples tests

**Comment by mbiarnes** [comment]
jenkins rerun examples tests

**Comment by fjtirado** [comment]
jenkins rerun examples tests

**Comment by fjtirado** [comment]
jenkins rerun examples tests

**Pull request merged**
