### PR TITLE
[WIP] [KOGITO-1248] Case Management process generation

### PR DESCRIPTION
**Pull request by ruromero**
Signed-off-by: ruromero <rromerom@redhat.com>

* Added CaseFile and CaseRoleInstance to model
* Added DynamicNodeVisitor and MilestoneVisitor
* Added AbstractNodeVisitor and other intermediate classes to reduce duplicated code.
* Refactored Process generation logic into ProcessVisitor
* Added ProcessGenerationTest class to validate all the generated processes are equivalent to the processes parsed from XML.
* Added all the case management processes from the jbpm project
* Fixed multiple imports
* Filter out metadata attributes related to graphical representation
* Small clean up

### CODE REVIEW

**Comment by ruromero** [comment]
This is a WIP pull request to try to get some feedback on situations that are failing in the ProcessGenerationTest.

An example are 
Or 

Can anyone take look at this PR and answer the following:
* Do you think the added test is useful to make sure the processes are generated as expected?
* Why the actions not properly added to BoundaryEventNodes as they seem to be added to other nodes like the EndStateNode
* Why the actions are not exactly the same as the parsed process? See https://github.com/kiegroup/kogito-runtimes/pull/410/files#diff-212e4a63b3ab85c0e9f7c53d34b27c8fR350
* Is the refactoring missing something?
* Are the CaseManagement classes added to the model sufficient?

**Comment by tiagodolphine** [comment]
Hi @ruromero I'll take a look at the PR and help on the review.

**Comment by mbiarnes** [comment]
Jenkins retest this please

**Comment by ruromero** [comment]
Closing in order to split in to simpler and more specific PR.

**Pull request closed without merging**
