### PR TITLE
KOGITO-7769 Update rpkgtests maven plugin version

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/KOGITO-7769

To new 1.0.0 version, where version of artifacts is included. See also https://github.com/ppalaga/rpkgtests-maven-plugin/pull/16

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](CONTRIBUTING.md)
- [ ] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/main/kogito-build/kogito-ide-config)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] tests</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] native</b>

- for <b>mandrel checks</b>  
  Run native checks against Mandrel image
  Please add comment: <b>Jenkins run mandrel</b>

- for a <b>specific mandrel check</b>  
  Run native checks against Mandrel image  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] mandrel</b>

- <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

### CODE REVIEW

**Review by mbiarnes — APPROVED** [review]
LGTM

**Comment by jstastny-cz** [comment]
Is this a temporary workaround? Permanent solution should be added in https://github.com/ppalaga/rpkgtests-maven-plugin I think.

**Comment by radtriste** [comment]
> Is this a temporary workaround? Permanent solution should be added in https://github.com/ppalaga/rpkgtests-maven-plugin I think.

Good suggestion. Gonna provide a PR on the rpkgtests plugin repository then

**Comment by kie-ci3** [comment]
**(tests) - kogito-apps job** `#790` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/790/display/redirect

**Test results:**
- PASSED: 1909
- FAILED: 16

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/790/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-10-default/kie_maven_plugin_test_kjar_10_default/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-10-default.kie-maven-plugin-test-kjar-10-default</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-apps/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-10-default/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/790/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-10-yes-generate/kie_maven_plugin_test_kjar_10_yes_generate/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-10-yes-generate.kie-maven-plugin-test-kjar-10-yes-generate</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-apps/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-10-yes-generate/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/790/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-11-default/kie_maven_plugin_test_kjar_11_default/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-11-default.kie-maven-plugin-test-kjar-11-default</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-apps/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-11-default/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/790/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-11-yes-generate/kie_maven_plugin_test_kjar_11_yes_generate/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-11-yes-generate.kie-maven-plugin-test-kjar-11-yes-generate</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-apps/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-11-yes-generate/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/790/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-12/kie_maven_plugin_test_kjar_12/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-12.kie-maven-plugin-test-kjar-12</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-apps/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-12/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/790/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-13/kie_maven_plugin_test_kjar_13/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-13.kie-maven-plugin-test-kjar-13</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-apps/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-13/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/790/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-14-ruleunits/kie_maven_plugin_test_kjar_14_ruleunits/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-14-ruleunits.kie-maven-plugin-test-kjar-14-ruleunits</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-apps/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-14-ruleunits/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/790/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-2/kie_maven_plugin_test_kjar_2/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-2.kie-maven-plugin-test-kjar-2</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-apps/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-2/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/790/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-3/kie_maven_plugin_test_kjar_3/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-3.kie-maven-plugin-test-kjar-3</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-apps/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-3/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/790/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-7-exec-model/kie_maven_plugin_test_kjar_7_exec_model/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-7-exec-model.kie-maven-plugin-test-kjar-7-exec-model</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-apps/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-7-exec-model/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/790/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-7-no-exec-model/kie_maven_plugin_test_kjar_7_no_exec_model/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-7-no-exec-model.kie-maven-plugin-test-kjar-7-no-exec-model</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-apps/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-7-no-exec-model/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/790/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-8-exec-model/kie_maven_plugin_test_kjar_8_exec_model/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-8-exec-model.kie-maven-plugin-test-kjar-8-exec-model</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-apps/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-8-exec-model/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/790/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-8-no-exec-model/kie_maven_plugin_test_kjar_8_no_exec_model/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-8-no-exec-model.kie-maven-plugin-test-kjar-8-no-exec-model</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-apps/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-8-no-exec-model/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/790/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-9-exec-model/kie_maven_plugin_test_kjar_9_exec_model/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-9-exec-model.kie-maven-plugin-test-kjar-9-exec-model</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-apps/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-9-exec-model/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/790/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-9-no-exec-model/kie_maven_plugin_test_kjar_9_no_exec_model/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-9-no-exec-model.kie-maven-plugin-test-kjar-9-no-exec-model</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-apps/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-9-no-exec-model/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/790/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-setup/kie_maven_plugin_test_kjar_setup/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-setup.kie-maven-plugin-test-kjar-setup</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-apps/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-setup/build.log for details.
</details>

**Comment by kie-ci3** [comment]
**(tests) - kogito-examples job** `#707` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/707/display/redirect

**Test results:**
- PASSED: 549
- FAILED: 16

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/707/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-10-default/kie_maven_plugin_test_kjar_10_default/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-10-default.kie-maven-plugin-test-kjar-10-default</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-10-default/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/707/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-10-yes-generate/kie_maven_plugin_test_kjar_10_yes_generate/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-10-yes-generate.kie-maven-plugin-test-kjar-10-yes-generate</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-10-yes-generate/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/707/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-11-default/kie_maven_plugin_test_kjar_11_default/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-11-default.kie-maven-plugin-test-kjar-11-default</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-11-default/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/707/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-11-yes-generate/kie_maven_plugin_test_kjar_11_yes_generate/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-11-yes-generate.kie-maven-plugin-test-kjar-11-yes-generate</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-11-yes-generate/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/707/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-12/kie_maven_plugin_test_kjar_12/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-12.kie-maven-plugin-test-kjar-12</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-12/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/707/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-13/kie_maven_plugin_test_kjar_13/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-13.kie-maven-plugin-test-kjar-13</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-13/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/707/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-14-ruleunits/kie_maven_plugin_test_kjar_14_ruleunits/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-14-ruleunits.kie-maven-plugin-test-kjar-14-ruleunits</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-14-ruleunits/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/707/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-2/kie_maven_plugin_test_kjar_2/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-2.kie-maven-plugin-test-kjar-2</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-2/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/707/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-3/kie_maven_plugin_test_kjar_3/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-3.kie-maven-plugin-test-kjar-3</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-3/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/707/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-7-exec-model/kie_maven_plugin_test_kjar_7_exec_model/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-7-exec-model.kie-maven-plugin-test-kjar-7-exec-model</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-7-exec-model/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/707/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-7-no-exec-model/kie_maven_plugin_test_kjar_7_no_exec_model/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-7-no-exec-model.kie-maven-plugin-test-kjar-7-no-exec-model</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-7-no-exec-model/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/707/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-8-exec-model/kie_maven_plugin_test_kjar_8_exec_model/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-8-exec-model.kie-maven-plugin-test-kjar-8-exec-model</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-8-exec-model/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/707/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-8-no-exec-model/kie_maven_plugin_test_kjar_8_no_exec_model/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-8-no-exec-model.kie-maven-plugin-test-kjar-8-no-exec-model</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-8-no-exec-model/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/707/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-9-exec-model/kie_maven_plugin_test_kjar_9_exec_model/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-9-exec-model.kie-maven-plugin-test-kjar-9-exec-model</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-9-exec-model/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/707/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-9-no-exec-model/kie_maven_plugin_test_kjar_9_no_exec_model/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-9-no-exec-model.kie-maven-plugin-test-kjar-9-no-exec-model</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-9-no-exec-model/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/707/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-setup/kie_maven_plugin_test_kjar_setup/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-setup.kie-maven-plugin-test-kjar-setup</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-setup/build.log for details.
</details>

**Comment by radtriste** [comment]
created https://github.com/ppalaga/rpkgtests-maven-plugin/pull/16

**Comment by radtriste** [comment]
@jstastny-cz and here is the update :)

**Review by jstastny-cz — APPROVED** [review]
Thank you, looks perfect.

**Pull request merged**
