### PR TITLE
KOGITO-5295 Remove Infinispan Conditional

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by cristianonicolai** [comment]
Jenkins rerun runtimes tests

**Comment by cristianonicolai** [comment]
Jenkins rerun apps tests

**Comment by cristianonicolai** [comment]
Jenkins rerun runtimes tests

**Comment by cristianonicolai** [comment]
@tiagodolphine @nmirasch removing some leftover from persistence test refactor.

**Review by tiagodolphine — APPROVED** [review]

**Comment by cristianonicolai** [comment]
Jenkins rerun runtimes tests

**Comment by nmirasch** [comment]
Jenkins rerun runtimes tests

**Review by nmirasch — APPROVED** [review]

**Pull request merged**
