### PR TITLE
Update developers section with KIE group reference

### PR DESCRIPTION
**Pull request by rsynek**
There is also https://github.com/kiegroup/kogito-examples/pull/261

### CODE REVIEW

**Comment by rsynek** [comment]
Do we have any way of restarting the PR check? I don't see how the failure could be related to this PR.

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
@rsynek can you try rebasing please.

**Comment by danielezonca** [comment]
jenkins retest this please

**Pull request merged**
