### PR TITLE
KOGITO-5560 remove 'preview'label from community website

### PR DESCRIPTION
**Pull request by tarilabs**
ref https://issues.redhat.com/browse/KOGITO-5560

Left UNchanged for 
https://github.com/kiegroup/kogito-runtimes/blob/22ea3901db6410efccaeeaa287a294e540c69a82/quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow/src/main/resources/META-INF/quarkus-extension.yaml#L13

as requested

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Run all builds</b>  
  Please add comment: <b>Jenkins retest this</b>

* <b>Run (or rerun) specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [runtimes|optaplanner|apps|examples] tests</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Run (or rerun) LTS specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [runtimes|optaplanner|apps|examples] LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

* <b>Run (or rerun) native specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [runtimes|optaplanner|apps|examples] native</b>

* <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

### CODE REVIEW

**Review by cristianonicolai — APPROVED** [review]

**Review by danielezonca — APPROVED** [review]

**Review by ricardozanini — APPROVED** [review]

**Review by mariofusco — APPROVED** [review]

**Review by evacchi — APPROVED** [review]

**Review by gitgabrio — APPROVED** [review]
HI @tarilabs 
Thanks for the PR: LGTM!

**Comment by evacchi** [comment]
for some reason most extensions are still showing up as `preview`? @gsmet https://code.quarkus.io/?extension-search=kogito

**Comment by gsmet** [comment]
I don't see any status in your extension descriptor and I don't see any override anywhere either (but I might have missed something). Maybe @i3andy or @aloubyansky would know more about what is the default in this case.

**Comment by ia3andy** [comment]
AFAIK default is stable

**Comment by tarilabs** [comment]
Hi @gsmet @ia3andy @aloubyansky I have checked again today (forced browser cache refresh) but these are still showing as preview:

image

I thought removing from extension descriptor, per this PR, would have show them without the `Preview` boxed label. What am I missing, please?

**Comment by ia3andy** [comment]
I don't think this PR is already available in code.quarkus.io, @gsmet?

**Comment by aloubyansky** [comment]
If I build the current platform main branch, only the serverless workflow is preview.

**Comment by aloubyansky** [comment]
Actually, you controlled it, see for example https://github.com/kiegroup/kogito-runtimes/blob/1.9.0.Final/kogito-quarkus-parent/kogito-quarkus-decisions-extension/kogito-quarkus-decisions/src/main/resources/META-INF/quarkus-extension.yaml#L12
Which is removed from https://github.com/kiegroup/kogito-runtimes/blob/1.10.0.Final/quarkus/extensions/kogito-quarkus-decisions-extension/kogito-quarkus-decisions/src/main/resources/META-INF/quarkus-extension.yaml
So once a platform including 1.10 is released, you'll see the effects of it.

**Comment by tarilabs** [comment]
> once a platform including 1.10 is released, you'll see the effects of it.

thank you @aloubyansky

**Pull request merged**
