### PR TITLE
Add toString to allow better message for checking expected argument t…

### PR DESCRIPTION
**Pull request by cristianonicolai**
…ypes

### CODE REVIEW

**Comment by kie-ci1** [comment]
**(tests) - kogito-examples job** `#1229` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 433
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1229/testReport/org.acme.travel.tests.multimessaging.quarkus/MultiMessagingIT/testProcess/">org.acme.travel.tests.multimessaging.quarkus.MultiMessagingIT.testProcess</a></summary>
org.opentest4j.AssertionFailedError: expected: <0> but was: <1><br/>	at org.acme.travel.tests.multimessaging.quarkus.MultiMessagingIT.testProcess(MultiMessagingIT.java:105)<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1229/display/redirect

**Comment by kie-ci1** [comment]
**(tests) - kogito-apps job** `#1147` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 2665
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/1147/testReport/org.kie.kogito.index/ProcessDataIndexMongoDBIT/testProcessInstanceEvents/">org.kie.kogito.index.ProcessDataIndexMongoDBIT.testProcessInstanceEvents</a></summary>
org.junit.ComparisonFailure: expected:<[NewTaskComm]ent> but was:<[newCommentCont]ent><br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/1147/display/redirect

**Comment by cristianonicolai** [comment]
> [org.kie.kogito.index.ProcessDataIndexMongoDBIT.testProcessInstanceEvents](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/1147/testReport/org.kie.kogito.index/ProcessDataIndexMongoDBIT/testProcessInstanceEvents/)
> org.junit.ComparisonFailure: expected:<[NewTaskComm]ent> but was:<[newCommentCont]ent>

@nmirasch could you take a look at this random failure.

**Comment by cristianonicolai** [comment]
Jenkins rerun kogito-apps tests

**Comment by cristianonicolai** [comment]
Jenkins rerun kogito-examples tests

**Comment by kie-ci1** [comment]
**(tests) - kogito-examples job** `#1231` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 433
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1231/testReport/org.kie.kogito.examples.demo/OutboxIT/___/">org.kie.kogito.examples.demo.OutboxIT.(?)</a></summary>
java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [8080, 49257] should be listening)<br/>	at org.kie.kogito.examples.demo.OutboxIT.before(OutboxIT.java:81)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [8080, 49257] should be listening)<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1231/display/redirect

**Comment by cristianonicolai** [comment]
Jenkins rerun kogito-examples tests

**Review by ricardozanini — APPROVED** [review]

**Comment by kie-ci1** [comment]
**(tests) - kogito-examples job** `#1232` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 432
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1232/testReport/org.acme.travel.tests.avro.quarkus/MultiMessagingIT/testProcess/">org.acme.travel.tests.avro.quarkus.MultiMessagingIT.testProcess</a></summary>
org.opentest4j.AssertionFailedError: expected: <0> but was: <3><br/>	at org.acme.travel.tests.avro.quarkus.MultiMessagingIT.testProcess(MultiMessagingIT.java:89)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1232/testReport/org.kie.kogito.examples.demo/OutboxIT/testSendProcessEvents/">org.kie.kogito.examples.demo.OutboxIT.testSendProcessEvents</a></summary>
org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a lambda expression in org.kie.kogito.examples.demo.OutboxIT null within 5 minutes.<br/>	at org.kie.kogito.examples.demo.OutboxIT.testSendProcessEvents(OutboxIT.java:117)<br/>Caused by: org.apache.http.NoHttpResponseException: localhost:49512 failed to respond<br/>	at org.kie.kogito.examples.demo.OutboxIT.lambda$testSendProcessEvents$0(OutboxIT.java:120)<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1232/display/redirect

**Pull request merged**
