### PR TITLE
KOGITO-2769 Set master version to 1.0.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/KOGITO-2769

Change master version to 1.0.0-SNAPSHOT as it makes more sense

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.md)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by evacchi** [comment]
i see that repos (e.g. Google's auto https://github.com/google/auto/blob/master/factory/pom.xml#L30) use HEAD-SNAPSHOT instead of a specific version, this way they don't have to bump each time. WDYT?

**Comment by radtriste** [comment]
I see your point but operator does only handle version in the format X.Y.Z ... and I would like to have it harmonoized on all repo.
`1.0.0` is set because it is the main next major.
The next time we need to change will be in a really big time, so the change won't be a big issue IMO

**Comment by radtriste** [comment]
Jenkins, please retest this

**Comment by radtriste** [comment]
Jenkins, please retest this

**Comment by radtriste** [comment]
Jenkins test this

**Comment by radtriste** [comment]
Jenkins retest this

**Comment by radtriste** [comment]
Jenkins retest this

**Pull request merged**
