### PR TITLE
[1.9.x][KOGITO-5511] Downgrade SpringBoot to 2.3.10

### PR DESCRIPTION
**Pull request by ricardozanini**
Cherry pick for #1440

### CODE REVIEW

**Review by cristianonicolai — APPROVED** [review]

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
@ricardozanini needs to revert cors related method changes too in examples

**Comment by ricardozanini** [comment]
Jenkins rerun examples tests

**Review by danielezonca — APPROVED** [review]

**Comment by ricardozanini** [comment]
Jenkins rerun apps tests

**Pull request merged**
