### PR TITLE
[KOGITO-3985] Remove deprecated field injection usages of Quarkus BuildProducer

### PR DESCRIPTION
**Pull request by danielezonca**
https://issues.redhat.com/browse/KOGITO-3985

Quarkus produces this warning during the execution

```
Dec 09, 2020 11:06:26 AM io.quarkus.deployment.ExtensionLoader deprecatedProducer
WARN: Producing values from constructors and fields is no longer supported and will be removed in a future release: io.quarkus.deployment.annotations.BuildProducer org.kie.kogito.quarkus.deployment.KogitoAssetsProcessor.generatedBeans
Dec 09, 2020 11:06:26 AM io.quarkus.deployment.ExtensionLoader deprecatedProducer
WARN: Producing values from constructors and fields is no longer supported and will be removed in a future release: io.quarkus.deployment.annotations.BuildProducer org.kie.kogito.quarkus.deployment.KogitoAssetsProcessor.resource
Dec 09, 2020 11:06:26 AM io.quarkus.deployment.ExtensionLoader deprecatedProducer
WARN: Producing values from constructors and fields is no longer supported and will be removed in a future release: io.quarkus.deployment.annotations.BuildProducer org.kie.kogito.quarkus.deployment.KogitoAssetsProcessor.reflectiveClass
Dec 09, 2020 11:06:26 AM io.quarkus.deployment.ExtensionLoader deprecatedProducer
WARN: Producing values from constructors and fields is no longer supported and will be removed in a future release: io.quarkus.deployment.annotations.BuildProducer org.kie.kogito.quarkus.deployment.KogitoAssetsProcessor.genResBI
```

So we should remove field injection of BuildProducer to prevent future incompatibilities

### CODE REVIEW

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by danielezonca** [comment]
Failed test `testForcingCreateExpiredJob – org.kie.kogito.jobs.service.resource.JobResourceIT`
Let's wait another build

**Review by evacchi — APPROVED** [review]

**Pull request merged**
