### PR TITLE
KOGITO-5705 - Review productized db scripts

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by cristianonicolai** [comment]
Jenkins run kogito-runtimes quarkus-lts

**Comment by kie-ci3** [comment]
**(tests) - serverless-workflow-examples job** `#617` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.serverless-workflow-examples/617/display/redirect

**Test results:**
- PASSED: 77
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.serverless-workflow-examples/617/testReport/org.kie.kogito.examples/DataIndexRestIT/testDataIndexRest/">org.kie.kogito.examples.DataIndexRestIT.testDataIndexRest</a></summary>
1 expectation failed.<br/>JSON path data.ProcessInstances[0].state doesn't match.<br/>Expected: is "COMPLETED"<br/>  Actual: ACTIVE<br/>
</details>

**Review by radtriste — APPROVED** [review]

**Comment by radtriste** [comment]
jenkins run kogito-runtimes quarkus-lts

**Comment by radtriste** [comment]
@cristianonicolai looks like org.kie.kogito.examples.DataIndexRestIT.testDataIndexRest is flaky... Can you have a look ?

**Review by akumar074 — APPROVED** [review]

**Comment by radtriste** [comment]
issues not related

**Pull request merged**
