### PR TITLE
[1.1.x] KOGITO-4146 updated version of kubernetes-client

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/KOGITO-4146

Also integrate https://github.com/kiegroup/kogito-runtimes/pull/959

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.md)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Review by evacchi — APPROVED** [review]

**Comment by radtriste** [comment]
Jenkins retest this

**Comment by radtriste** [comment]
PR checks is ok but native tests report a problem on optaplanner example ...
https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/custom/job/tradisso/job/kogito-4146-native/job/kogito-4146/2/testReport/
investigating

**Review by danielezonca — APPROVED** [review]

**Comment by danielezonca** [comment]
> PR checks is ok but native tests report a problem on optaplanner example ...
> https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/custom/job/tradisso/job/kogito-4146-native/job/kogito-4146/2/testReport/
> investigating

@lucamolteni @triceo 
The native build of this PR failed with a stackoverflow on `IntrospectableLambda.generateFingerprint`. Any idea?
```java
        at java.lang.Object.toString(Object.java:246)
	at org.drools.model.functions.IntrospectableLambda.generateFingerprint(IntrospectableLambda.java:59)
	at org.drools.model.functions.IntrospectableLambda.toString(IntrospectableLambda.java:43)
	at org.drools.model.functions.IntrospectableLambda.hashCode(IntrospectableLambda.java:72)
	at java.lang.Object.toString(Object.java:246)
	at org.drools.model.functions.IntrospectableLambda.generateFingerprint(IntrospectableLambda.java:59)
	at org.drools.model.functions.IntrospectableLambda.toString(IntrospectableLambda.java:43)
	at org.drools.model.functions.IntrospectableLambda.hashCode(IntrospectableLambda.java:72)
	at java.lang.Object.toString(Object.java:246)
```

**Comment by lucamolteni** [comment]
@danielezonca @triceo 

As `LambdbaIntrospector` doens't work with native image (it heavily uses reflection) lambdas need to implement the `HashedExpression` interface so that we can compare them.

 https://github.com/kiegroup/drools/blob/f006e17502d21e591370533596fe6775e4e5ab43/drools-model/drools-canonical-model/src/main/java/org/drools/model/functions/IntrospectableLambda.java#L60

It goes in the third branch that triggers the SO

```
else {
            logger.debug("No HashedExpression provided, using Object.class.toString(), node sharing might not work correctly");
            return super.toString();
        }
```

**Comment by lucamolteni** [comment]
Fix here https://github.com/kiegroup/drools/pull/3321

**Comment by radtriste** [comment]
ok so fix will be in drools 7.49 ?

**Comment by radtriste** [comment]
anyway, I guess this is unrelated to this PR. I created https://issues.redhat.com/browse/KOGITO-4164 for that. @danielezonca or @evacchi can we merge this one ?

**Pull request merged**
