### PR TITLE
KOGITO-5664 - Rename KafkaClient package to avoid Sonar conflict

### PR DESCRIPTION
**Pull request by cristianonicolai**
Assembly:
- https://github.com/kiegroup/kogito-runtimes/pull/1544
- https://github.com/kiegroup/kogito-apps/pull/992
- https://github.com/kiegroup/kogito-examples/pull/854

### CODE REVIEW

**Review by radtriste — APPROVED** [review]

**Review by fjtirado — APPROVED** [review]

**Comment by cristianonicolai** [comment]
Jenkins rerun apps tests

**Comment by cristianonicolai** [comment]
Jenkins rerun examples tests

**Comment by cristianonicolai** [comment]
Jenkins rerun examples tests

**Comment by cristianonicolai** [comment]
Jenkins rerun examples tests

**Pull request merged**
