### PR TITLE
KOGITO-6982 - Isolate DB operations per Process Id

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Review by tiagodolphine — COMMENTED** [review]
LGTM, thanks for the PR this is a step to make sharding easier per process in case we need it. 
It would be great to update the index creation in the SQL DDLs, to include `process_id + id`.
For example:
```
CREATE INDEX idx_process_instances_process_id ON process_instances
    ( id, process_id);
```

**Comment by kie-ci1** [comment]
**(tests) - kogito-apps job** `#1545` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 2722
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/1545/testReport/org.kie.kogito.trusty.service.common/KeycloakTrustyServiceIT/___/">org.kie.kogito.trusty.service.common.KeycloakTrustyServiceIT.(?)</a></summary>
java.lang.RuntimeException: <br/>java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors<br/>	[error]: Build step io.quarkus.kafka.client.deployment.DevServicesKafkaProcessor#startKafkaDevService threw an exception: java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/>	at io.quarkus.kafka.client.deployment.DevServicesKafkaProcessor.startKafkaDevService(DevServicesKafkaProcessor.java:100)<br/>	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>	at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:925)<br/>	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)<br/>	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)<br/>	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)<br/>	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)<br/>	at java.base/java.lang.Thread.run(Thread.java:829)<br/>	at org.jboss.threads.JBossThread.run(JBossThread.java:501)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/>	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:336)<br/>	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:317)<br/>	at io.quarkus.kafka.client.deployment.DevServicesKafkaProcessor.lambda$startKafka$5(DevServicesKafkaProcessor.java:249)<br/>	at java.base/java.util.Optional.orElseGet(Optional.java:369)<br/>	at io.quarkus.kafka.client.deployment.DevServicesKafkaProcessor.startKafka(DevServicesKafkaProcessor.java:263)<br/>	at io.quarkus.kafka.client.deployment.DevServicesKafkaProcessor.startKafkaDevService(DevServicesKafkaProcessor.java:94)<br/>	... 11 more<br/>Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception<br/>	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)<br/>	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:329)<br/>	... 16 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container<br/>	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:525)<br/>	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:331)<br/>	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)<br/>	... 17 more<br/>Caused by: java.lang.IllegalStateException: Container did not start correctly.<br/>	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:463)<br/>	... 19 more<br/><br/>Caused by: java.lang.RuntimeException: <br/>io.quarkus.builder.BuildException: Build failure: Build failed due to errors<br/>	[error]: Build step io.quarkus.kafka.client.deployment.DevServicesKafkaProcessor#startKafkaDevService threw an exception: java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/>	at io.quarkus.kafka.client.deployment.DevServicesKafkaProcessor.startKafkaDevService(DevServicesKafkaProcessor.java:100)<br/>	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>	at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:925)<br/>	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)<br/>	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)<br/>	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)<br/>	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)<br/>	at java.base/java.lang.Thread.run(Thread.java:829)<br/>	at org.jboss.threads.JBossThread.run(JBossThread.java:501)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/>	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:336)<br/>	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:317)<br/>	at io.quarkus.kafka.client.deployment.DevServicesKafkaProcessor.lambda$startKafka$5(DevServicesKafkaProcessor.java:249)<br/>	at java.base/java.util.Optional.orElseGet(Optional.java:369)<br/>	at io.quarkus.kafka.client.deployment.DevServicesKafkaProcessor.startKafka(DevServicesKafkaProcessor.java:263)<br/>	at io.quarkus.kafka.client.deployment.DevServicesKafkaProcessor.startKafkaDevService(DevServicesKafkaProcessor.java:94)<br/>	... 11 more<br/>Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception<br/>	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)<br/>	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:329)<br/>	... 16 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container<br/>	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:525)<br/>	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:331)<br/>	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)<br/>	... 17 more<br/>Caused by: java.lang.IllegalStateException: Container did not start correctly.<br/>	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:463)<br/>	... 19 more<br/><br/>Caused by: io.quarkus.builder.BuildException: <br/>Build failure: Build failed due to errors<br/>	[error]: Build step io.quarkus.kafka.client.deployment.DevServicesKafkaProcessor#startKafkaDevService threw an exception: java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/>	at io.quarkus.kafka.client.deployment.DevServicesKafkaProcessor.startKafkaDevService(DevServicesKafkaProcessor.java:100)<br/>	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>	at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:925)<br/>	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)<br/>	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)<br/>	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)<br/>	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)<br/>	at java.base/java.lang.Thread.run(Thread.java:829)<br/>	at org.jboss.threads.JBossThread.run(JBossThread.java:501)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/>	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:336)<br/>	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:317)<br/>	at io.quarkus.kafka.client.deployment.DevServicesKafkaProcessor.lambda$startKafka$5(DevServicesKafkaProcessor.java:249)<br/>	at java.base/java.util.Optional.orElseGet(Optional.java:369)<br/>	at io.quarkus.kafka.client.deployment.DevServicesKafkaProcessor.startKafka(DevServicesKafkaProcessor.java:263)<br/>	at io.quarkus.kafka.client.deployment.DevServicesKafkaProcessor.startKafkaDevService(DevServicesKafkaProcessor.java:94)<br/>	... 11 more<br/>Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception<br/>	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)<br/>	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:329)<br/>	... 16 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container<br/>	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:525)<br/>	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:331)<br/>	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)<br/>	... 17 more<br/>Caused by: java.lang.IllegalStateException: Container did not start correctly.<br/>	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:463)<br/>	... 19 more<br/><br/>Caused by: java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/>Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container<br/>Caused by: java.lang.IllegalStateException: Container did not start correctly.<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/1545/display/redirect

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Review by ricardozanini — APPROVED** [review]

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Pull request merged**
