### PR TITLE
KOGITO-4316 Bump 7.49.0.Final

### PR DESCRIPTION
**Pull request by evacchi**

### CODE REVIEW

**Comment by danielezonca** [comment]
You might need this PR too
https://github.com/kiegroup/kogito-runtimes/pull/973

**Comment by radtriste** [comment]
@danielezonca should also cherry-pick https://github.com/kiegroup/kogito-runtimes/pull/973 to 1.2.x ?
as we are also bumping 7.49.0 there ...

**Comment by evacchi** [comment]
I think so @radtriste

**Review by mariofusco — APPROVED** [review]

**Comment by danielezonca** [comment]
jenkins retest this please

**Pull request merged**
