### PR TITLE
KOGITO-6551 Disable Dev Service producer if Docker isn't available

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by cristianonicolai** [comment]
Jenkins rerun kogito-examples tests

**Comment by cristianonicolai** [comment]
Jenkins rerun kogito-examples tests

**Review by nmirasch — APPROVED** [review]

**Comment by radtriste** [comment]
@cristianonicolai do you want to cherry-pick for future 1.16.1 ?

**Comment by cristianonicolai** [comment]
@radtriste will do.

**Pull request merged**
