### PR TITLE
Removed unnecessary dependencies

### PR DESCRIPTION
**Pull request by hbelmiro**

### CODE REVIEW

**Comment by kie-ci3** [comment]
**(tests) - kogito-runtimes job** `#2949` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-T 1C -Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-runtimes -u https://github.com/kiegroup/kogito-runtimes/pull/3139 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/2949/display/redirect

**Test results:**
- PASSED: 3346
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/2949/testReport/org.kie.kogito.persistence.kafka/KafkaProcessInstancesIT/testFindByIdReadMode/">org.kie.kogito.persistence.kafka.KafkaProcessInstancesIT.testFindByIdReadMode</a></summary>
<br/>expected: 5<br/> but was: 0
</details>

**Comment by hbelmiro** [comment]
jenkins rerun kogito-runtimes tests

**Comment by kie-ci3** [comment]
**(tests) - kogito-runtimes job** `#2950` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-T 1C -Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-runtimes -u https://github.com/kiegroup/kogito-runtimes/pull/3139 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/2950/display/redirect

**Test results:**
- PASSED: 3346
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/2950/testReport/org.kie.kogito.it/KafkaPersistenceIT/testAsyncWIH/">org.kie.kogito.it.KafkaPersistenceIT.testAsyncWIH</a></summary>
Assertion condition defined as a lambda expression in org.kie.kogito.it.PersistenceTest that uses java.lang.String 1 expectation failed.<br/>Expected status code <404> but was <200>.<br/> within 10 seconds.
</details>

**Comment by hbelmiro** [comment]
jenkins rerun kogito-runtimes tests

**Review by radtriste — APPROVED** [review]

**Pull request merged**
