### PR TITLE
[KOGITO-7523] Collector action should setValue to trigger event change

### PR DESCRIPTION
**Pull request by fjtirado**
While manually testing Kogito-7524, I realize there is a case that is not currently covered and will not trigger an event change when it should. 
This PR is a quick fix, because Kogito-7524 may not be merged after all (we need to discuss, there are issues I will try do summarize [here](https://github.com/kiegroup/kogito-runtimes/pull/2380))

### CODE REVIEW

**Review by ricardozanini — APPROVED** [review]
I'm assuming you have tests covering this feature in #2380?

**Comment by kie-ci3** [comment]
**(tests) - kogito-apps job** `#764` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/764/display/redirect

**Test results:**
- PASSED: 1890
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/764/testReport/org.kie.kogito.index.mongodb/ProcessDataIndexMongoDBIT/testProcessInstanceEvents/">org.kie.kogito.index.mongodb.ProcessDataIndexMongoDBIT.testProcessInstanceEvents</a></summary>
java.lang.RuntimeException: java.lang.IllegalStateException: Unable to determine the status of the running process. See the above logs for details<br/>Caused by: java.lang.IllegalStateException: Unable to determine the status of the running process. See the above logs for details<br/>
</details>

**Comment by ricardozanini** [comment]
jenkins rerun kogito-apps tests

**Review by tiagodolphine — APPROVED** [review]

**Comment by kie-ci3** [comment]
**(tests) - kogito-apps job** `#765` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/765/display/redirect

**Test results:**
- PASSED: 1884
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/765/testReport/org.kie.kogito.it.jobs/CallbackStateTimeoutsIT/Build_projects___callbackStateTimeoutsExceeded/">Build projects / org.kie.kogito.it.jobs.CallbackStateTimeoutsIT.callbackStateTimeoutsExceeded</a></summary>
java.lang.RuntimeException: java.lang.IllegalStateException: Unable to determine the status of the running process. See the above logs for details<br/>Caused by: java.lang.IllegalStateException: Unable to determine the status of the running process. See the above logs for details<br/>
</details>

**Comment by fjtirado** [comment]
jenkins rerun kogito-apps tests

**Pull request merged**
