### PR TITLE
KOGITO-2138 - Process with adhoc subprocess will fail when used with …

### PR DESCRIPTION
**Pull request by mswiderski**
…persistence

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@mswiderski could you add some sort of test for this, perhpaps in the infisnispan/file add on?

**Comment by mswiderski** [comment]
@cristianonicolai I could add it but frankly speaking it has nothing to do with the mechanism used by persistence and the failure I ran into was simply because of triggerDate not being set. So I'd say if you want this kind of tests with persistence it should go into separate integration test module that could use engine tests with enabled persistence .. of various types. What do you think?

**Comment by cristianonicolai** [comment]
@mswiderski sure that's ok, I thought was a specific thing regarding persistence. In that case, is there any test that we could check that the triggerTime is now set?

**Comment by mswiderski** [comment]
@cristianonicolai isn't this enough https://github.com/kiegroup/kogito-runtimes/pull/498/files#diff-15fa3183e6865094973de2150bbc3b78R739

**Comment by cristianonicolai** [comment]
@mswiderski sorry missed it completely, yep it's good :)

**Comment by mswiderski** [comment]
@tiagodolphine it is considered mandatory value as it will also be pushed to data index (and other consumers) as the date and time when given node was executed so it must be non null.

**Pull request merged**
