### PR TITLE
KOGITO-308: Avoid XStream "Illegal reflective access operation"

### PR DESCRIPTION
**Pull request by evacchi**
this should address https://github.com/quarkusio/quarkus/pull/4092#issuecomment-533005395

before 
```
[INFO] --- quarkus-maven-plugin:0.21.2:dev (default-cli) @ kogito-travel-agency ---
Listening for transport dt_socket at address: 5005
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.Fields (file:/home/evacchi/.m2/repository/com/thoughtworks/xstream/xstream/1.4.11.1/xstream-1.4.11.1.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2019-09-19 15:03:05,708 INFO  [io.qua.dep.QuarkusAugmentor] (main) Beginning quarkus augmentation
2019-09-19 15:03:09,620 INFO  [io.qua.dep.QuarkusAugmentor] (main) Quarkus augmentation completed in 3912ms
2019-09-19 15:03:09,689 INFO  [io.qua.swa.run.SwaggerUiServletExtension] (main) Swagger UI available at /swagger-ui
2019-09-19 15:03:10,056 INFO  [io.quarkus] (main) Quarkus 0.21.2 started in 4.477s. Listening on: http://[::]:8080
2019-09-19 15:03:10,057 INFO  [io.quarkus] (main) Installed features: [cdi, kogito, resteasy, resteasy-jsonb, smallrye-openapi, swagger-ui]
^C2019-09-19 15:03:10,323 INFO  [io.quarkus] (Quarkus Shutdown Thread) Quarkus stopped in 0.020s
```

after:
```
[INFO] --- quarkus-maven-plugin:0.21.2:dev (default-cli) @ kogito-travel-agency ---
Listening for transport dt_socket at address: 5005
2019-09-19 15:12:03,582 INFO  [io.qua.dep.QuarkusAugmentor] (main) Beginning quarkus augmentation
2019-09-19 15:12:07,289 INFO  [io.qua.dep.QuarkusAugmentor] (main) Quarkus augmentation completed in 3707ms
2019-09-19 15:12:07,343 INFO  [io.qua.swa.run.SwaggerUiServletExtension] (main) Swagger UI available at /swagger-ui
2019-09-19 15:12:07,655 INFO  [io.quarkus] (main) Quarkus 0.21.2 started in 4.202s. Listening on: http://[::]:8080
2019-09-19 15:12:07,656 INFO  [io.quarkus] (main) Installed features: [cdi, kogito, resteasy, resteasy-jsonb, smallrye-openapi, swagger-ui]
```

### CODE REVIEW

**Comment by evacchi** [comment]
shall we go ahead and merge? examples did not break so I guess that selection of (un)marshallers should be fine for us (we can always revert.. it's pretty self-contained) @mariofusco

**Comment by mswiderski** [comment]
have we tested that on native image? not sure it's relevant but just double checking ... as tomorrow I will do the 0.4.0 release...

**Comment by evacchi** [comment]
nope. good point

**Comment by evacchi** [comment]
I run a `mvn -Pnative package` on examples with and without 

```
MAVEN_OPTS='-Dsun.reflect.debugModuleAccessChecks=true --illegal-access=deny ' 
JAVA_OPTS='-Dsun.reflect.debugModuleAccessChecks=true --illegal-access=deny ' 
```

and it succeeded in both cases, you may want to do another test run on your machine to stay on the safe side

**Pull request merged**
