### PR TITLE
[KOGITO-8210] Fixing native issue related with Avro schema

### PR DESCRIPTION
**Pull request by fjtirado**
Merge with https://github.com/kiegroup/kogito-examples/pull/1467

### CODE REVIEW

**Comment by kie-ci3** [comment]
**(tests) - kogito-apps job** `#1576` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/1576/display/redirect

**Test results:**
- PASSED: 1933
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/1576/testReport/org.kie.kogito.index/ProcessDataIndexInfinispanIT/testProcessInstanceEvents/">org.kie.kogito.index.ProcessDataIndexInfinispanIT.testProcessInstanceEvents</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>JSON path data.UserTaskInstances[0].comments.size() doesn't match.<br/>Expected: is <1><br/>  Actual: <0><br/><br/>
</details>

**Review by tiagodolphine — APPROVED** [review]

**Review by hbelmiro — APPROVED** [review]

**Review by radtriste — APPROVED** [review]

**Comment by radtriste** [comment]
jenkins run native

**Comment by kie-ci3** [comment]
**(native) - kogito-apps job** `#131` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.native/job/kogito-runtimes.native.downstream.kogito-apps/131/display/redirect

**Test results:**
- PASSED: 1353
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.native/job/kogito-runtimes.native.downstream.kogito-apps/131/testReport/org.kie.kogito.it.jobs/SwitchStateTimeoutsIT/Build_projects___switchStateEventConditionTimeoutsTransitionTimeoutsExceeded/">Build projects / org.kie.kogito.it.jobs.SwitchStateTimeoutsIT.switchStateEventConditionTimeoutsTransitionTimeoutsExceeded</a></summary>
org.awaitility.core.ConditionTimeoutException: <br/>Assertion condition defined as a lambda expression in org.kie.kogito.it.jobs.SwitchStateTimeoutsIT No requests exactly matched. Most similar request was:  expected:<<br/>POST<br/>/<br/><br/>kogitoprocinstanceid [equalTo] 72ee0c0c-97a5-4e60-b92e-e5668959347d<br/>type [equalTo] process_result_event<br/>data.decision [equalTo] NoDecision> but was:<<br/>POST<br/>/<br/><br/>{}<br/>{}<br/>{}> within 50 seconds.<br/>	at org.kie.kogito.it.jobs.SwitchStateTimeoutsIT.verifyNoDecisionEventWasProduced(SwitchStateTimeoutsIT.java:48)<br/>Caused by: com.github.tomakehurst.wiremock.client.VerificationException: <br/>No requests exactly matched. Most similar request was:  expected:<<br/>POST<br/>/<br/><br/>kogitoprocinstanceid [equalTo] 72ee0c0c-97a5-4e60-b92e-e5668959347d<br/>type [equalTo] process_result_event<br/>data.decision [equalTo] NoDecision> but was:<<br/>POST<br/>/<br/><br/>{}<br/>{}<br/>{}><br/>	at org.kie.kogito.it.jobs.SwitchStateTimeoutsIT.lambda$verifyNoDecisionEventWasProduced$0(SwitchStateTimeoutsIT.java:48)<br/>
</details>

**Comment by kie-ci3** [comment]
**(native) - kogito-runtimes job** `#133` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.native/job/kogito-runtimes.native.kogito-runtimes/133/display/redirect

**Test results:**
- PASSED: 3113
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.native/job/kogito-runtimes.native.kogito-runtimes/133/testReport/org.kie.kogito.quarkus.workflows/EventFlowIT/testNotStartingMultipleEventRainy/">org.kie.kogito.quarkus.workflows.EventFlowIT.testNotStartingMultipleEventRainy</a></summary>
org.awaitility.core.ConditionTimeoutException: <br/>Condition with alias 'dead' didn't complete within 5 seconds because assertion condition defined as a lambda expression in org.kie.kogito.quarkus.workflows.EventFlowIT that uses java.lang.String, java.lang.Stringjava.lang.String 1 expectation failed.<br/>Expected status code <404> but was <200>.<br/>.<br/>	at org.kie.kogito.quarkus.workflows.EventFlowIT.waitForFinish(EventFlowIT.java:133)<br/>	at org.kie.kogito.quarkus.workflows.EventFlowIT.testNotStartingMultipleEventRainy(EventFlowIT.java:94)<br/>Caused by: java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <404> but was <200>.<br/><br/>	at org.kie.kogito.quarkus.workflows.EventFlowIT.lambda$waitForFinish$1(EventFlowIT.java:138)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.native/job/kogito-runtimes.native.kogito-runtimes/133/testReport/org.kie.kogito.quarkus.workflows/EventFlowIT/testNotStartingMultipleEvent/">org.kie.kogito.quarkus.workflows.EventFlowIT.testNotStartingMultipleEvent</a></summary>
org.awaitility.core.ConditionTimeoutException: <br/>Condition with alias 'dead' didn't complete within 15 seconds because assertion condition defined as a lambda expression in org.kie.kogito.quarkus.workflows.EventFlowIT that uses java.lang.String, java.lang.Stringjava.lang.String 1 expectation failed.<br/>Expected status code <404> but was <200>.<br/>.<br/>	at org.kie.kogito.quarkus.workflows.EventFlowIT.waitForFinish(EventFlowIT.java:133)<br/>	at org.kie.kogito.quarkus.workflows.EventFlowIT.doIt(EventFlowIT.java:144)<br/>	at org.kie.kogito.quarkus.workflows.EventFlowIT.testNotStartingMultipleEvent(EventFlowIT.java:69)<br/>Caused by: java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <404> but was <200>.<br/><br/>	at org.kie.kogito.quarkus.workflows.EventFlowIT.lambda$waitForFinish$1(EventFlowIT.java:138)<br/>
</details>

**Comment by radtriste** [comment]
jenkins rerun kogito-runtimes native

**Comment by radtriste** [comment]
jenkins rerun kogito-apps native

**Comment by kie-ci3** [comment]
**(native) - kogito-examples job** `#129` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.native/job/kogito-runtimes.native.downstream.kogito-examples/129/display/redirect

**Test results:**
- PASSED: 274
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.native/job/kogito-runtimes.native.downstream.kogito-examples/129/testReport/org.acme.newsletter.subscription.flow/SubscriptionFlowIT/verifySubscription/">org.acme.newsletter.subscription.flow.SubscriptionFlowIT.verifySubscription</a></summary>
Assertion condition defined as a lambda expression in org.acme.newsletter.subscription.flow.SubscriptionFlowIT No requests exactly matched. Most similar request was:  expected:<<br/>POST<br/>/<br/><br/>new.subscription<br/>yeneffer@witch.com<br/>Yeneffer> but was:<<br/>POST<br/>/<br/><br/>{}<br/>{}<br/>{}> within 10 seconds.
</details>

**Comment by kie-ci3** [comment]
**(native) - kogito-runtimes job** `#134` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.native/job/kogito-runtimes.native.kogito-runtimes/134/display/redirect

**Test results:**
- PASSED: 3113
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.native/job/kogito-runtimes.native.kogito-runtimes/134/testReport/org.kie.kogito.quarkus.workflows/EventFlowIT/testNotStartingMultipleEventRainy/">org.kie.kogito.quarkus.workflows.EventFlowIT.testNotStartingMultipleEventRainy</a></summary>
org.awaitility.core.ConditionTimeoutException: <br/>Condition with alias 'dead' didn't complete within 5 seconds because assertion condition defined as a lambda expression in org.kie.kogito.quarkus.workflows.EventFlowIT that uses java.lang.String, java.lang.Stringjava.lang.String 1 expectation failed.<br/>Expected status code <404> but was <200>.<br/>.<br/>	at org.kie.kogito.quarkus.workflows.EventFlowIT.waitForFinish(EventFlowIT.java:133)<br/>	at org.kie.kogito.quarkus.workflows.EventFlowIT.testNotStartingMultipleEventRainy(EventFlowIT.java:94)<br/>Caused by: java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <404> but was <200>.<br/><br/>	at org.kie.kogito.quarkus.workflows.EventFlowIT.lambda$waitForFinish$1(EventFlowIT.java:138)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.native/job/kogito-runtimes.native.kogito-runtimes/134/testReport/org.kie.kogito.quarkus.workflows/EventFlowIT/testNotStartingMultipleEvent/">org.kie.kogito.quarkus.workflows.EventFlowIT.testNotStartingMultipleEvent</a></summary>
org.awaitility.core.ConditionTimeoutException: <br/>Condition with alias 'dead' didn't complete within 15 seconds because assertion condition defined as a lambda expression in org.kie.kogito.quarkus.workflows.EventFlowIT that uses java.lang.String, java.lang.Stringjava.lang.String 1 expectation failed.<br/>Expected status code <404> but was <200>.<br/>.<br/>	at org.kie.kogito.quarkus.workflows.EventFlowIT.waitForFinish(EventFlowIT.java:133)<br/>	at org.kie.kogito.quarkus.workflows.EventFlowIT.doIt(EventFlowIT.java:144)<br/>	at org.kie.kogito.quarkus.workflows.EventFlowIT.testNotStartingMultipleEvent(EventFlowIT.java:69)<br/>Caused by: java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <404> but was <200>.<br/><br/>	at org.kie.kogito.quarkus.workflows.EventFlowIT.lambda$waitForFinish$1(EventFlowIT.java:138)<br/>
</details>

**Comment by radtriste** [comment]
native examples and runtimes are known issues

**Pull request merged**
