### PR TITLE
KOGITO-807 - Prediction service as add on for user tasks

### PR DESCRIPTION
**Pull request by mswiderski**
depends on https://github.com/kiegroup/kogito-bom/pull/75

examples can be found in kogito quick starts 
https://github.com/mswiderski/kogito-quickstarts/tree/master/kogito-usertasks-with-predictions-quarkus
https://github.com/mswiderski/kogito-quickstarts/tree/master/kogito-usertasks-with-predictions-springboot

best to use spring boot as it does not depend on master of quarkus so does not require additional work.

@ruivieira @DuncanDoyle you might be interested in this....

### CODE REVIEW

**Comment by spolti** [comment]
Will this need a new image?

**Comment by mswiderski** [comment]
@spolti not, at least not now. Depending if there will be need to have external service for predictions then we might need new image

**Comment by mswiderski** [comment]
ok, this now is ready from my point of view ... with some extra test coverage.

**Comment by ruivieira** [comment]
@mswiderski It seems to work as expected. lgtm!

**Pull request merged**
