### PR TITLE
KOGITO-6553 MissingInternalObjectMapper exception in Native Mode 

### PR DESCRIPTION
**Pull request by evacchi**
Many thanks for submitting your Pull Request :heart:! 

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Run all builds</b>  
  Please add comment: <b>Jenkins retest this</b>

* <b>Run (or rerun) specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] tests</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Run (or rerun) LTS specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

* <b>Run (or rerun) native specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] native</b>

* <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

### CODE REVIEW

**Comment by evacchi** [comment]
jenkins run kogito-examples tests

**Comment by evacchi** [comment]
jenkins run kogito-runtimes native

**Review by tarilabs — APPROVED** [review]

**Review by radtriste — APPROVED** [review]

**Comment by radtriste** [comment]
jenkins rerun kogito-runtimes native

**Comment by radtriste** [comment]
@evacchi I thought that this problem was solved or ?

**Comment by radtriste** [comment]
oh it is not for now ... https://kie.zulipchat.com/#narrow/stream/236603-kogito-ci/topic/.5Bmain.5D.20Kogito.20Runtimes/near/268810722

**Comment by radtriste** [comment]
merging as it will be solved in another PR

**Comment by radtriste** [comment]
cherry-pick: https://github.com/kiegroup/kogito-runtimes/pull/1920

**Pull request merged**
