### PR TITLE
[1.3.x] KOGITO-4504  Upgrade Kie 7.50.0.Final

### PR DESCRIPTION
**Pull request by evacchi**
https://issues.redhat.com/browse/KOGITO-4504

### CODE REVIEW

**Comment by evacchi** [comment]
Jenkins retest this

**Comment by evacchi** [comment]
Jenkins please retest this

**Review by danielezonca — APPROVED** [review]

**Comment by evacchi** [comment]
stopped because it was sitting there for too long.

jenkins please retest this

**Comment by evacchi** [comment]
again :(

jenkins please retest this

**Pull request merged**
