### PR TITLE
[KOGITO-3833] Json Schema generation whitespaces

### PR DESCRIPTION
**Pull request by fjtirado**
Fixing and adding test

### CODE REVIEW

**Comment by fjtirado** [comment]
jenkins retest this

**Comment by fjtirado** [comment]
@MarianMacik @evacchi please review this easy one

**Review by MarianMacik — APPROVED** [review]

**Comment by evacchi** [comment]
@cristianonicolai should we backport to 1.0.x ? it's not a blocker...

**Comment by cristianonicolai** [comment]
@evacchi yeah, I would be tempted but lets keep on blockers only mode.

**Comment by fjtirado** [comment]
> @evacchi yeah, I would be tempted but lets keep on blockers only mode.

Yes, its tempting ;), but I agree, lets merge for master and backport if requested

**Comment by fjtirado** [comment]
@kiegroup/gatekeepers Please merge this

**Pull request merged**
