### PR TITLE
KOGITO-4447: Fix kogito-cloudevents-spring-boot-addon-it to pick the latest version of kogito-maven-plugin

### PR DESCRIPTION
**Pull request by xieshenzh**
Description: 
`kogito-cloudevents-spring-boot-addon-it` doesn't pick the latest version of [kogito-maven-plugin](https://github.com/kiegroup/kogito-runtimes/blob/dfd4920a2a3b8f49b3361f6fe3aee4b6b80598f5/addons/cloudevents/cloudevents-spring-boot-addon-it/pom.xml#L58).
Followed the example of [integration-tests-springboot](https://github.com/kiegroup/kogito-runtimes/blob/dfd4920a2a3b8f49b3361f6fe3aee4b6b80598f5/integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/pom.xml#L132) to fix `kogito-cloudevents-spring-boot-addon-it` with `maven-invoker-plugin`.

Jira: https://issues.redhat.com/browse/KOGITO-4447

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.md)
- [x] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/droolsjbpm-build-bootstrap/tree/master/ide-configuration)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
Overall looks good, just be aware that properties naming are changing, see: https://github.com/kiegroup/kogito-runtimes/pull/1059

**Comment by xieshenzh** [comment]
> Overall looks good, just be aware that properties naming are changing, see: #1059

Thanks @cristianonicolai . Property names are updated.

**Comment by mareknovotny** [comment]
@xieshenzh please rebase from master the https://github.com/kiegroup/kogito-runtimes/pull/1059 was merged

**Comment by xieshenzh** [comment]
Thanks @mareknovotny . It is based.

**Comment by xieshenzh** [comment]
Jenkins retest this

**Comment by cristianonicolai** [comment]
@xieshenzh seems like Sonar is icking up a duplicate class: `org/drools/project/model/ProjectModel`, most likely you need to exclude the new module in https://github.com/kiegroup/kogito-runtimes/blob/master/kogito-build-parent/pom.xml#L1539

**Comment by xieshenzh** [comment]
Jenkins retest this

**Comment by xieshenzh** [comment]
Jenkins retest this

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by xieshenzh** [comment]
Jenkins retest this

**Comment by xieshenzh** [comment]
Thanks @cristianonicolai @danielezonca . It is fixed now.

**Review by cristianonicolai — APPROVED** [review]

**Review by kostola — APPROVED** [review]

**Pull request merged**
