### PR TITLE
KOGITO-4404 use local repository in invoker tests

### PR DESCRIPTION
**Pull request by jstastny-cz**
As discsussed in https://issues.redhat.com/browse/KOGITO-4404, having "offline" settings.xml for invoker might lead to issues while running the tests with empty local repo (when not being run as part of full-project reactor).
This PR attempts at fixing that issue, while still keeping the amount of downloaded data at minimum - by making invoker to use local repository, where things already downloaded are available.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

* <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

### CODE REVIEW

**Review by evacchi — APPROVED** [review]

**Comment by jstastny-cz** [comment]
jenkins retest this.

**Review by MarianMacik — APPROVED** [review]

**Comment by jstastny-cz** [comment]
@r00ta @cristianonicolai any feedback on this please?

**Review by cristianonicolai — APPROVED** [review]

**Comment by evacchi** [comment]
everything looks good, shall we merge?

**Comment by evacchi** [comment]
let's make sure everything is in order 

jenkins retest this.

**Comment by radtriste** [comment]
job timeout ... jenkins retest this.

**Comment by jstastny-cz** [comment]
@r00ta do you want to review or should I ask @evacchi to merge already?

**Review by r00ta — APPROVED** [review]
Thank you @jstastny-cz !

**Comment by jstastny-cz** [comment]
@kiegroup/gatekeepers can we merge?

**Pull request merged**
