### PR TITLE
KOGITO-4545 Disable header validation for generated sources and fix t…

### PR DESCRIPTION
**Pull request by cristianonicolai**
…emplates to create valid header

Many thanks for submitting your Pull Request :heart:!

### CODE REVIEW

**Review by nmirasch — APPROVED** [review]

**Review by danielezonca — COMMENTED** [review]
@cristianonicolai 
Thanks for the PR, can you please remove license from templates? I don't think they are necessary at all

**Comment by cristianonicolai** [comment]
@danielezonca agree but that will require some work. If fine with you, I would like to just fix the examples and look into that in a follow-up PR/JIRA.

**Comment by danielezonca** [comment]
> @danielezonca agree but that will require some work. If fine with you, I would like to just fix the examples and look into that in a follow-up PR/JIRA.

Sure, fine for me 👍

**Review by danielezonca — APPROVED** [review]

**Review by MarianMacik — APPROVED** [review]
FYI it worked for me (both the check and formatting) even without package declarations.

**Pull request merged**
