### PR TITLE
[KOGITO-2943] Link events doesn't work in Kogito

### PR DESCRIPTION
**Pull request by fjtirado**
Adding link support.
As you can see, code change performed is pretty simple, but I have doubts
about the line that has to be removed in visitNode methods to make it
work.

### CODE REVIEW

**Comment by fjtirado** [comment]
jenkins retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by fjtirado** [comment]
jenkins retest this

**Comment by fjtirado** [comment]
@kiegroup/gatekeepers please merge this

**Comment by tarilabs** [comment]
Can somebody comment why this move was required as part of this PR, please?
https://github.com/kiegroup/kogito-runtimes/pull/683/files#diff-823c91db8c899ddeb3fb92d96d244435
thanks

**Comment by fjtirado** [comment]
> Can somebody comment why this move was required as part of this PR, please?
> https://github.com/kiegroup/kogito-runtimes/pull/683/files#diff-823c91db8c899ddeb3fb92d96d244435
> thanks

That was clearly an accident. Can someone put it back?

**Pull request merged**
