### PR TITLE
[KOGITO-2016] Better error message when a DMN model doesn't have a name

### PR DESCRIPTION
**Pull request by tkobayas**
See https://issues.redhat.com/browse/KOGITO-2016 for the issue description.
 
- [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by tkobayas** [comment]
I faced this issue while testing various values for Name property in both VSCode extension and online editor (https://kiegroup.github.io/kogito-online/#/editor/dmn). If I leave the "Name" blank, the resulted XML will have `name=""`.

Note that "Name" is filled with a value in both editors by default (e.g. "new-file"), so usually, users don't hit this issue.

**Comment by tarilabs** [comment]
make sense; on other hand the work to port validation as part of the build shall also help to avoid this problem with a more general approach, later

You can ask to merge this when suitable thanks!

**Comment by tkobayas** [comment]
Rebased because of conflict

**Comment by tkobayas** [comment]
Jenkins test again

**Pull request merged**
