### PR TITLE
[1.11.x] KOGITO-5854 - Remove kogito-serverless-workflow-runtime from kogito-s…

### PR DESCRIPTION
**Pull request by MarianMacik**
…pring-boot-starter

[KOGITO-5854](https://issues.redhat.com/browse/KOGITO-5854)

PR set:
* kiegroup/kogito-runtimes#1594
* kiegroup/kogito-examples#882

### CODE REVIEW

**Comment by MarianMacik** [comment]
jenkins rerun apps tests

**Comment by MarianMacik** [comment]
jenkins rerun examples

**Comment by MarianMacik** [comment]
jenkins rerun examples tests

**Review by ricardozanini — APPROVED** [review]

**Review by jstastny-cz — APPROVED** [review]
Thank you.

**Comment by MarianMacik** [comment]
PR for kogito-examples added.

jenkins rerun examples tests

**Pull request merged**
