### PR TITLE
KOGITO-6735 Support for multi instance task

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by kie-ci1** [comment]
**(tests) - kogito-runtimes job** `#984` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 2476
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/984/testReport/org.kie.kogito.integrationtests.springboot/PingPongMessageTest/testPingPongBetweenProcessInstances/">org.kie.kogito.integrationtests.springboot.PingPongMessageTest.testPingPongBetweenProcessInstances</a></summary>
org.awaitility.core.ConditionTimeoutException: <br/>Assertion condition defined as a org.kie.kogito.integrationtests.springboot.PingPongMessageTest 1 expectation failed.<br/>JSON path $.size() doesn't match.<br/>Expected: <1><br/>  Actual: 0<br/> within 10 seconds.<br/>	at org.kie.kogito.integrationtests.springboot.PingPongMessageTest.validateSubProcess(PingPongMessageTest.java:85)<br/>	at org.kie.kogito.integrationtests.springboot.PingPongMessageTest.testPingPongBetweenProcessInstances(PingPongMessageTest.java:56)<br/>Caused by: java.lang.AssertionError: <br/>1 expectation failed.<br/>JSON path $.size() doesn't match.<br/>Expected: <1><br/>  Actual: 0<br/><br/>	at org.kie.kogito.integrationtests.springboot.PingPongMessageTest.lambda$validateSubProcess$1(PingPongMessageTest.java:91)<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/984/display/redirect

**Comment by cristianonicolai** [comment]
Jenkins rerun kogito-runtimes tests

**Review by elguardian — APPROVED** [review]
LGTM

**Comment by kie-ci1** [comment]
**(tests) - kogito-examples job** `#1065` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 431
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1065/testReport/org.acme.travel.tests.multimessaging.quarkus/MultiMessagingIT/testProcess/">org.acme.travel.tests.multimessaging.quarkus.MultiMessagingIT.testProcess</a></summary>
org.opentest4j.AssertionFailedError: expected: <0> but was: <3><br/>	at org.acme.travel.tests.multimessaging.quarkus.MultiMessagingIT.testProcess(MultiMessagingIT.java:105)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1065/testReport/org.acme.travel.tests.messaging.quarkus/MessagingIT/testProcess/">org.acme.travel.tests.messaging.quarkus.MessagingIT.testProcess</a></summary>
org.opentest4j.AssertionFailedError: expected: <0> but was: <1><br/>	at org.acme.travel.tests.messaging.quarkus.MessagingIT.testProcess(MessagingIT.java:110)<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1065/display/redirect

**Comment by kie-ci1** [comment]
**(tests) - kogito-examples job** `#1066` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 431
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1066/testReport/org.acme.travel.tests.multimessaging.quarkus/MultiMessagingIT/testProcess/">org.acme.travel.tests.multimessaging.quarkus.MultiMessagingIT.testProcess</a></summary>
org.opentest4j.AssertionFailedError: expected: <0> but was: <3><br/>	at org.acme.travel.tests.multimessaging.quarkus.MultiMessagingIT.testProcess(MultiMessagingIT.java:105)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1066/testReport/org.acme.travel.tests.messaging.quarkus/MessagingIT/testProcess/">org.acme.travel.tests.messaging.quarkus.MessagingIT.testProcess</a></summary>
org.opentest4j.AssertionFailedError: expected: <0> but was: <3><br/>	at org.acme.travel.tests.messaging.quarkus.MessagingIT.testProcess(MessagingIT.java:110)<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1066/display/redirect

**Comment by cristianonicolai** [comment]
Jenkins rerun kogito-examples tests

**Review by MarianMacik — APPROVED** [review]

**Pull request merged**
