### PR TITLE
KOGITO-4093 quarkus bump 1.11.0.Beta2 + smallrye reactive messaging

### PR DESCRIPTION
**Pull request by evacchi**
https://issues.redhat.com/browse/KOGITO-4093
- [x] depends on workaround https://github.com/kiegroup/kogito-apps/pull/576
- [ ] depends on https://github.com/kiegroup/kogito-examples/pull/499

### CODE REVIEW

**Comment by evacchi** [comment]
can someone from trusty investigate this?

      [INFO] Kogito Apps :: Integration Tests :: Trusty Service . FAILURE [  0.370 s]
      
@kostola @danielezonca

**Comment by evacchi** [comment]
jenkins please retest this

**Comment by evacchi** [comment]
jenkins please retest this

**Comment by evacchi** [comment]
restarted manually https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/blue/organizations/jenkins/KIE%2Fkogito%2Fghprb-webhooks%2Fkogito-runtimes/detail/kogito-runtimes/2489/pipeline

**Comment by evacchi** [comment]
@r00ta I have seen you are the last one working on that submodule, are you able to figure out what's going on? neither @kostola nor I can see what's wrong. Honestly I can't even reproduce locally -- I have issues with docker, but I am not getting the same error 

/cc @danielezonca @cristianonicolai @tiagodolphine

**Comment by evacchi** [comment]
@tiagodolphine @cristianonicolai can you take a look at that submodule? 

    <artifactId>integration-tests-trusty-service</artifactId>

neither I nor @kostola understand what is going on. I cannot reproduce locally (I also have some issues with docker, but I doubt it's related) /cc @danielezonca 

it looks like a Maven config issue but I can't tell what is wrong 

```
[INFO] --- maven-failsafe-plugin:2.22.2:integration-test (default) @ integration-tests-trusty-service ---

[INFO] Downloading from mirror-central: https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/org/apache/maven/shared/maven-shared-utils/0.9/maven-shared-utils-0.9.pom

[INFO] Downloaded from mirror-central: https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/org/apache/maven/shared/maven-shared-utils/0.9/maven-shared-utils-0.9.pom (6.2 kB at 519 kB/s)

[INFO] Downloading from mirror-central: https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/org/apache/maven/shared/maven-shared-utils/0.9/maven-shared-utils-0.9.jar

[INFO] Downloaded from mirror-central: https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/org/apache/maven/shared/maven-shared-utils/0.9/maven-shared-utils-0.9.jar (172 kB at 11 MB/s)

[WARNING] ClassRealm[plugin>org.apache.maven.plugins:maven-failsafe-plugin:2.22.2--929073976, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@5bc2b487]

com.google.inject.CreationException: Unable to create injector, see the following errors:


1) Scope org.apache.maven.execution.scope.internal.MojoExecutionScope@3e30646a is already bound to org.apache.maven.execution.scope.MojoExecutionScoped at org.apache.maven.execution.scope.internal.MojoExecutionScopeModule.configure(MojoExecutionScopeModule.java:52) (via modules: org.eclipse.sisu.wire.WireModule -> org.apache.maven.execution.scope.internal.MojoExecutionScopeModule).

 Cannot bind org.apache.maven.execution.scope.internal.MojoExecutionScope@237f4395.

  at ClassRealm[plugin>org.apache.maven.plugins:maven-failsafe-plugin:2.22.2--929073976, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@5bc2b487] (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.plexus.PlexusBindingModule -> org.apache.maven.execution.scope.internal.MojoExecutionScopeCoreModule)


1 error

    at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist (Errors.java:543)

    at com.google.inject.internal.InternalInjectorCreator.initializeStatically (InternalInjectorCreator.java:159)

    at com.google.inject.internal.InternalInjectorCreator.build (InternalInjectorCreator.java:106)

    at com.google.inject.Guice.createInjector (Guice.java:87)

    at com.google.inject.Guice.createInjector (Guice.java:69)

    at com.google.inject.Guice.createInjector (Guice.java:59)

    at org.codehaus.plexus.DefaultPlexusContainer.addPlexusInjector (DefaultPlexusContainer.java:481)

    at org.codehaus.plexus.DefaultPlexusContainer.discoverComponents (DefaultPlexusContainer.java:460)

    at org.apache.maven.plugin.internal.DefaultMavenPluginManager.discoverPluginComponents (DefaultMavenPluginManager.java:436)

    at org.apache.maven.plugin.internal.DefaultMavenPluginManager.createPluginRealm (DefaultMavenPluginManager.java:415)

    at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupPluginRealm (DefaultMavenPluginManager.java:374)

    at org.apache.maven.plugin.DefaultBuildPluginManager.getPluginRealm (DefaultBuildPluginManager.java:234)

    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:105)

    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)

    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)

    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)

    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)

    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)

    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)

    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)

    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)

    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)

    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)

    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)

    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)

    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)

    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)

    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)

    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)

    at java.lang.reflect.Method.invoke (Method.java:566)

    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)

    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)

    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)

    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```

**Comment by evacchi** [comment]
So I think we've figured out what is going on.
@aloubyansky @gsmet I think you'll find this interesting

On https://github.com/kiegroup/kogito-apps `explainability-service-messaging` creates a Quarkus uber jar

This is is put in as a dependency of  maven failsafe

```
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-failsafe-plugin</artifactId>
          <dependencies>
            <!-- ensure dependent modules were built, but not added in the classpath -->
            <dependency>
              <groupId>org.kie.kogito</groupId>
              <artifactId>explainability-service-messaging</artifactId>
              <version>${project.version}</version>
              <classifier>runner</classifier>
              <scope>runtime</scope>
            </dependency>
            <dependency>
              <groupId>org.kie.kogito</groupId>
              <artifactId>trusty-service</artifactId>
              <version>${project.version}</version>
              <classifier>runner</classifier>
              <scope>runtime</scope>
            </dependency>
          </dependencies>
```

now, we know this is not kosher; nonetheless I know the reason was to force Maven recognize a dependency between projects while _not_ putting that dependency on the project classpath (these are integration tests). Regardless this is good practice, what is happening is that Maven now gets confused. So **the hotfix for us is "well, don't do that"**

But the underlying reason is that the uber jar contains... Maven code! In fact:

```
[INFO] --- quarkus-maven-plugin:1.11.0.Beta2:build (default) @ explainability-service-messaging ---
Downloading from jboss-public-repository-group: https://repository.jboss.org/nexus/content/groups/public/io/quarkus/quarkus-hibernate-validator-deployment/1.11.0.Beta2/quarkus-hibernate-validator-deployment-1.11.0.Beta2.pom
Downloading from central: https://repo.maven.apache.org/maven2/io/quarkus/quarkus-hibernate-validator-deployment/1.11.0.Beta2/quarkus-hibernate-validator-deployment-1.11.0.Beta2.pom
Downloaded from central: https://repo.maven.apache.org/maven2/io/quarkus/quarkus-hibernate-validator-deployment/1.11.0.Beta2/quarkus-hibernate-validator-deployment-1.11.0.Beta2.pom (3.0 kB at 9.7 kB/s)
Downloading from jboss-public-repository-group: https://repository.jboss.org/nexus/content/groups/public/io/quarkus/quarkus-hibernate-validator-deployment/1.11.0.Beta2/quarkus-hibernate-validator-deployment-1.11.0.Beta2.jar
Downloading from central: https://repo.maven.apache.org/maven2/io/quarkus/quarkus-hibernate-validator-deployment/1.11.0.Beta2/quarkus-hibernate-validator-deployment-1.11.0.Beta2.jar
Downloaded from central: https://repo.maven.apache.org/maven2/io/quarkus/quarkus-hibernate-validator-deployment/1.11.0.Beta2/quarkus-hibernate-validator-deployment-1.11.0.Beta2.jar (19 kB at 73 kB/s)
[INFO] [org.jboss.threads] JBoss Threads version 3.2.0.Final
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building fat jar: /home/evacchi/Devel/redhat/pr/submarine/kogito-apps/explainability/explainability-service-messaging/target/explainability-service-messaging-2.0.0-SNAPSHOT-runner.jar
[WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Duplicate entry javax/el/PrivateMessages.properties entry from org.glassfish:jakarta.el::jar:3.0.3(compile) will be ignored. Existing file was provided by jakarta.el:jakarta.el-api::jar:3.0.3(compile)
[WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Duplicate entry META-INF/sisu/javax.inject.Named entry from org.apache.maven:maven-model-builder::jar:3.6.3(compile) will be ignored. Existing file was provided by org.apache.maven:maven-core::jar:3.6.2(compile)
[WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Duplicate entry META-INF/sisu/javax.inject.Named entry from org.apache.maven:maven-embedder::jar:3.6.3(compile) will be ignored. Existing file was provided by org.apache.maven:maven-core::jar:3.6.2(compile)
[WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Duplicate entry META-INF/plexus/components.xml entry from org.eclipse.sisu:org.eclipse.sisu.plexus::jar:0.3.4(compile) will be ignored. Existing file was provided by org.apache.maven:maven-core::jar:3.6.2(compile)
[WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Duplicate entry META-INF/plexus/components.xml entry from org.sonatype.plexus:plexus-cipher::jar:1.4(compile) will be ignored. Existing file was provided by org.apache.maven:maven-core::jar:3.6.2(compile)
[WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Duplicate entry META-INF/plexus/components.xml entry from org.sonatype.plexus:plexus-sec-dispatcher::jar:1.4(compile) will be ignored. Existing file was provided by org.apache.maven:maven-core::jar:3.6.2(compile)
[WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Duplicate entry META-INF/sisu/javax.inject.Named entry from org.apache.maven:maven-settings-builder::jar:3.6.3(compile) will be ignored. Existing file was provided by org.apache.maven:maven-core::jar:3.6.2(compile)
[WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Duplicate entry META-INF/sisu/javax.inject.Named entry from org.apache.maven.resolver:maven-resolver-impl::jar:1.4.1(compile) will be ignored. Existing file was provided by org.apache.maven:maven-core::jar:3.6.2(compile)
[WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Duplicate entry META-INF/sisu/javax.inject.Named entry from org.apache.maven:maven-resolver-provider::jar:3.6.3(compile) will be ignored. Existing file was provided by org.apache.maven:maven-core::jar:3.6.2(compile)
[WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Duplicate entry META-INF/sisu/javax.inject.Named entry from org.apache.maven.resolver:maven-resolver-connector-basic::jar:1.4.1(compile) will be ignored. Existing file was provided by org.apache.maven:maven-core::jar:3.6.2(compile)
[WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Duplicate entry META-INF/sisu/javax.inject.Named entry from org.apache.maven.resolver:maven-resolver-transport-wagon::jar:1.4.1(compile) will be ignored. Existing file was provided by org.apache.maven:maven-core::jar:3.6.2(compile)
[WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Duplicate entry META-INF/plexus/components.xml entry from org.apache.maven.wagon:wagon-http::jar:3.3.4(compile) will be ignored. Existing file was provided by org.apache.maven:maven-core::jar:3.6.2(compile)
[WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Duplicate entry META-INF/plexus/components.xml entry from org.apache.maven.wagon:wagon-file::jar:3.3.4(compile) will be ignored. Existing file was provided by org.apache.maven:maven-core::jar:3.6.2(compile)
[WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Duplicate entry about.html entry from org.eclipse.sisu:org.eclipse.sisu.inject::jar:0.3.4(runtime) will be ignored. Existing file was provided by org.eclipse.sisu:org.eclipse.sisu.plexus::jar:0.3.4(compile)
[WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Dependencies with duplicate files detected. The dependencies [jakarta.el:jakarta.el-api::jar:3.0.3(compile), org.glassfish:jakarta.el::jar:3.0.3(compile)] contain duplicate files, e.g. javax/el/BeanELResolver$BPSoftReference.class
[WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Dependencies with duplicate files detected. The dependencies [org.eclipse.sisu:org.eclipse.sisu.inject::jar:0.3.4(runtime), org.eclipse.sisu:org.eclipse.sisu.plexus::jar:0.3.4(compile)] contain duplicate files, e.g. about.html
[WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Dependencies with duplicate files detected. The dependencies [org.apache.maven.resolver:maven-resolver-impl::jar:1.4.1(compile), org.apache.maven:maven-embedder::jar:3.6.3(compile), org.apache.maven:maven-resolver-provider::jar:3.6.3(compile), org.apache.maven:maven-model-builder::jar:3.6.3(compile), org.apache.maven:maven-core::jar:3.6.2(compile), org.apache.maven:maven-settings-builder::jar:3.6.3(compile), org.apache.maven.resolver:maven-resolver-transport-wagon::jar:1.4.1(compile), org.apache.maven.resolver:maven-resolver-connector-basic::jar:1.4.1(compile)] contain duplicate files, e.g. META-INF/sisu/javax.inject.Named
[WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Dependencies with duplicate files detected. The dependencies [org.sonatype.plexus:plexus-cipher::jar:1.4(compile), org.sonatype.plexus:plexus-sec-dispatcher::jar:1.4(compile), org.apache.maven:maven-core::jar:3.6.2(compile), org.apache.maven.wagon:wagon-http::jar:3.3.4(compile), org.eclipse.sisu:org.eclipse.sisu.plexus::jar:0.3.4(compile), org.apache.maven.wagon:wagon-file::jar:3.3.4(compile)] contain duplicate files, e.g. META-INF/plexus/components.xml
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] Starting container image build
[WARNING] [io.quarkus.container.image.jib.deployment.JibProcessor] Base image 'fabric8/java-alpine-openjdk11-jre' does not use a specific image digest - build may not be reproducible
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] The base image requires auth. Trying again for fabric8/java-alpine-openjdk11-jre...
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] LogEvent [level=INFO, message=Docker config auths section defines credentials for index.docker.io]
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] LogEvent [level=LIFECYCLE, message=Using credentials from Docker config (/home/evacchi/.docker/config.json) for fabric8/java-alpine-openjdk11-jre]
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] Using base image with digest: sha256:b459cc59d6c7ddc9fd52f981fc4c187f44a401f2433a1b4110810d2dd9e98a07
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] Container entrypoint set to [java, -Djava.util.logging.manager=org.jboss.logmanager.LogManager, -cp, /app/resources:/app/classes, io.quarkus.runner.GeneratedMain]
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] Created container image org.kie.kogito/explainability-service-messaging:2.0.0-SNAPSHOT (sha256:bac384c997d7c5d267f34d2be323eb1af3eed364389bf8b3daa39ace248f0730)

[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 21881ms
```

and I can only assume this is not intended. If I run `dependency:tree` on this subproject I can see a lot of `compile` dependencies, even if the root is `test` (junit5):

```
[INFO] +- io.quarkus:quarkus-junit5:jar:1.11.0.Beta2:test
[INFO] |  +- io.quarkus:quarkus-bootstrap-core:jar:1.11.0.Beta2:compile
[INFO] |  |  +- io.quarkus:quarkus-bootstrap-app-model:jar:1.11.0.Beta2:compile
[INFO] |  |  +- io.quarkus:quarkus-bootstrap-maven-resolver:jar:1.11.0.Beta2:compile
[INFO] |  |  |  +- org.apache.maven:maven-embedder:jar:3.6.3:compile
[INFO] |  |  |  |  +- org.apache.maven:maven-settings:jar:3.6.3:compile
[INFO] |  |  |  |  +- org.apache.maven:maven-core:jar:3.6.2:compile
[INFO] |  |  |  |  |  +- org.apache.maven:maven-artifact:jar:3.6.2:compile
[INFO] |  |  |  |  |  \- org.codehaus.plexus:plexus-component-annotations:jar:1.6:compile
[INFO] |  |  |  |  +- org.apache.maven:maven-plugin-api:jar:3.6.2:compile
[INFO] |  |  |  |  +- org.apache.maven:maven-model:jar:3.6.3:compile
[INFO] |  |  |  |  +- org.apache.maven:maven-model-builder:jar:3.6.3:compile
[INFO] |  |  |  |  +- org.apache.maven:maven-builder-support:jar:3.6.3:compile
[INFO] |  |  |  |  +- org.apache.maven.resolver:maven-resolver-api:jar:1.4.1:compile
[INFO] |  |  |  |  +- org.apache.maven.resolver:maven-resolver-util:jar:1.4.1:compile
[INFO] |  |  |  |  +- org.apache.maven.shared:maven-shared-utils:jar:3.2.1:compile
[INFO] |  |  |  |  |  \- commons-io:commons-io:jar:2.8.0:compile
[INFO] |  |  |  |  +- com.google.inject:guice:jar:no_aop:4.2.1:compile
[INFO] |  |  |  |  |  \- com.google.guava:guava:jar:30.1-jre:compile
[INFO] |  |  |  |  |     +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |  |  |  |  |     \- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO] |  |  |  |  +- org.codehaus.plexus:plexus-utils:jar:3.2.1:compile
[INFO] |  |  |  |  +- org.codehaus.plexus:plexus-classworlds:jar:2.5.2:compile
[INFO] |  |  |  |  \- commons-cli:commons-cli:jar:1.4:compile
[INFO] |  |  |  +- org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.4:compile
[INFO] |  |  |  +- org.apache.maven:maven-settings-builder:jar:3.6.3:compile
[INFO] |  |  |  |  +- org.codehaus.plexus:plexus-interpolation:jar:1.25:compile
[INFO] |  |  |  |  \- org.sonatype.plexus:plexus-sec-dispatcher:jar:1.4:compile
[INFO] |  |  |  |     \- org.sonatype.plexus:plexus-cipher:jar:1.4:compile
[INFO] |  |  |  +- org.apache.maven:maven-resolver-provider:jar:3.6.3:compile
[INFO] |  |  |  |  +- org.apache.maven:maven-repository-metadata:jar:3.6.3:compile
[INFO] |  |  |  |  +- org.apache.maven.resolver:maven-resolver-spi:jar:1.4.1:compile
[INFO] |  |  |  |  \- org.apache.maven.resolver:maven-resolver-impl:jar:1.4.1:compile
[INFO] |  |  |  +- org.apache.maven.resolver:maven-resolver-connector-basic:jar:1.4.1:compile
[INFO] |  |  |  +- org.apache.maven.resolver:maven-resolver-transport-wagon:jar:1.4.1:compile
[INFO] |  |  |  +- org.apache.maven.wagon:wagon-http:jar:3.3.4:compile
[INFO] |  |  |  |  +- org.apache.maven.wagon:wagon-http-shared:jar:3.3.4:compile
[INFO] |  |  |  |  |  \- org.jsoup:jsoup:jar:1.12.1:compile
[INFO] |  |  |  |  +- org.apache.httpcomponents:httpclient:jar:4.5.13:compile
[INFO] |  |  |  |  |  \- commons-codec:commons-codec:jar:1.14:compile
[INFO] |  |  |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.13:compile
[INFO] |  |  |  |  \- org.apache.maven.wagon:wagon-provider-api:jar:3.3.4:compile
[INFO] |  |  |  \- org.apache.maven.wagon:wagon-file:jar:3.3.4:compile
[INFO] |  |  +- io.quarkus:quarkus-bootstrap-gradle-resolver:jar:1.11.0.Beta2:compile
[INFO] |  |  \- io.smallrye.common:smallrye-common-io:jar:1.5.0:compile
[INFO] |  +- org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.3.4:runtime
```

**Comment by gsmet** [comment]
I have seen this issue in our regular Quarkus build too. Wasn't sure if it was new or not. I suppose it is.

@evacchi could you create a Quarkus issue with a reproducer and ping Alexey there?

**Comment by evacchi** [comment]
@gsmet we didn't have this issue with Quarkus 1.10.x the project layout was the same, we would have noticed

**Comment by gsmet** [comment]
Yes, I noticed that with master too so I suspect it's a 1.11 regression.

**Comment by evacchi** [comment]
depends on https://github.com/kiegroup/kogito-apps/pull/576

**Comment by evacchi** [comment]
filed issue https://github.com/quarkusio/quarkus/issues/14114

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by radtriste** [comment]
Jenkins retest this

**Comment by radtriste** [comment]
Jenkins retest this

**Comment by radtriste** [comment]
Jenkins retest this

**Comment by radtriste** [comment]
Jenkins retest this

**Review by cristianonicolai — APPROVED** [review]

**Pull request merged**
