### PR TITLE
[1.1.x] KOGITO-4093 quarkus bump 1.11.0.Beta2 + smallrye reactive messaging (…

### PR DESCRIPTION
**Pull request by cristianonicolai**
…#956)

* quarkus bump 1.11.0.Beta2 + smallrye reactive messaging

* bump other versions

(cherry picked from commit e26b0184b3a4dc23bd674e99cbe02313cf348a67)

### CODE REVIEW

**Review by evacchi — APPROVED** [review]

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by evacchi** [comment]
jenkins please retest this

**Comment by radtriste** [comment]
@evacchi it needs rebase to take the correct Jenkinsfile. for now still taking the one from your branch

**Comment by evacchi** [comment]
@radtriste rebased my copy https://github.com/kiegroup/kogito-runtimes/pull/965

**Pull request merged**
