### PR TITLE
KOGITO-3599 Remove dependency to quarkus-bom from addons that are use…

### PR DESCRIPTION
**Pull request by cristianonicolai**
Assembly:
- https://github.com/kiegroup/kogito-apps/pull/516
- https://github.com/kiegroup/kogito-runtimes/pull/831

### CODE REVIEW

**Review by evacchi — APPROVED** [review]

**Review by ricardozanini — APPROVED** [review]

**Review by radtriste — APPROVED** [review]

**Comment by evacchi** [comment]
there are conflicts @cristianonicolai

**Review by tiagodolphine — APPROVED** [review]

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Review by ricardozanini — APPROVED** [review]

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Pull request merged**
