### PR TITLE
[KOGITO-4548] Test for collection coercion

### PR DESCRIPTION
**Pull request by jomarko**
Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](CONTRIBUTING.md)
- [ ] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/master/kogito-ide-config)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by jomarko** [comment]
@tarilabs marked you as reviewer as default assignee, feel free to delegate to proper person, both jira and this PR. Thank you.

**Review by tarilabs — CHANGES_REQUESTED** [review]
This test is invalid, for the reasons explained here: https://issues.redhat.com/browse/KOGITO-4548?focusedCommentId=15847485&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-15847485

**Comment by jomarko** [comment]
@tarilabs PR updated.

**Comment by tarilabs** [comment]
Having clarified there is no bug,
I am having a remaining doubt, at the end, what's this test covering more than what we had already here:

https://github.com/kiegroup/kogito-runtimes/blob/a4e93297c8b5ee3083c62e9a9cd7faf5dfcfa7f0/integration-tests/integration-tests-quarkus-decisions/src/test/java/org/kie/kogito/integrationtests/quarkus/BasicAddTest.java#L56-L65

or here:

https://github.com/kiegroup/kogito-runtimes/blob/a4e93297c8b5ee3083c62e9a9cd7faf5dfcfa7f0/integration-tests/integration-tests-quarkus-decisions/src/test/java/org/kie/kogito/integrationtests/quarkus/DSCoercionTest.java#L41-L66

I think the existing tests already cover the case of whole-model, DS coercion, and DS.
What am I missing?

**Comment by jomarko** [comment]
@tarilabs my intention was to double check coercion works for `collection` data types. `DScoercion` test cover just built in types if I am not wrong.

**Review by tarilabs — COMMENTED** [review]
This tests imho is not covering anything more specifically than what I've already linked, if only is testing a feature of the marshaller (can marshall a list of string when Kogito-on-Quarkus).

I have no objection if you want to merge anyway this as an additional test; in that case it would be meaningful to have the analogous Spring Boot variant too, like it happens for these integration tests.

**Comment by jomarko** [comment]
@tarilabs yes, thank you, I will include analogous for a *SpringBoot* soon, will let you know once done.

**Comment by jomarko** [comment]
@tarilabs build is green finally, I had trouble with proper formatting of files. If would like to ask you for re-review. No rush. Take your time.

**Comment by jomarko** [comment]
@tarilabs just friendly reminder, could you please re-review?

**Comment by tarilabs** [comment]
I thought I already did in https://github.com/kiegroup/kogito-runtimes/pull/1102#pullrequestreview-600536309 and you said you indeed wanted to add SB variant as part of this PR as well, so that's fine 

To be clear I do NOT have merge rights, you need to chase somebody who can maybe @danielezonca can you merge this please

**Comment by jomarko** [comment]
@tarilabs yes, springboot variant is added https://github.com/kiegroup/kogito-runtimes/pull/1102/files#diff-a76fc6fbd73176a1208be410b1250b2f1e6888c10f102ef9b07a55567f0dcc5d

**Comment by jomarko** [comment]
Not approved in a month, Closing.

**Comment by tarilabs** [comment]
It was in https://github.com/kiegroup/kogito-runtimes/pull/1102#issuecomment-799233594 and as I mentioned I do not have Merge rights. Maybe the right thing to do instead of closing and with that nullify both you efforts but also those who participated, would have been to follow the suggestion to ask those who have Merge rights to merge it, like I did have suggested in https://github.com/kiegroup/kogito-runtimes/pull/1102#issuecomment-799233594 ?

**Pull request closed without merging**
