### PR TITLE
KOGITO-6322 Restore jandex on processes quarkus extension + lazily initialize DataIndexEventPublisher

### PR DESCRIPTION
**Pull request by evacchi**
Jandex was not configured on the quarkus extension (which causes weird startup issues with the new API I am working on, but only in some cases; go figure). I am setting here jandex again, but that causes the dev services to be instantiated. If the config property is not set, because it is not optional, then it throws an error. 

~~I am refactoring the event emitter so that it takes a delegate.~~

EDIT: no need! by annotating with `@UnlessBuildProperty(name = DataIndexEventPublisher.KOGITO_DATA_INDEX, stringValue = "")` the bean won't be created unless the property is set

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@evacchi I intentionally disabled that, see https://github.com/kiegroup/kogito-runtimes/pull/1689#discussion_r740782459, at the time, it seems to me that most Quarkus extensions create beans manually/selectively in the codegen. Would that approach work in your use case?

**Comment by evacchi** [comment]
ok I see, I will look into it

**Comment by evacchi** [comment]
so that's
     
```java
@BuildStep
    public AdditionalBeanBuildItem additionalBeans() {
        return AdditionalBeanBuildItem.builder().addBeanClasses(QuarkusStraightThroughProcessService.class, QuarkusProcessIdFactory.class).build(); 
```        

why `QuarkusStraightThroughProcessService` kept working. That was driving me totally crazy. Sure that'll work. I must have missed that comment there

**Comment by evacchi** [comment]
well that makes this patch irrelevant then!

**Pull request closed without merging**
