### PR TITLE
KOGITO-3549 - Introducing TopicsResource Endpoint

### PR DESCRIPTION
**Pull request by ricardozanini**
Signed-off-by: Ricardo Zanini <zanini@redhat.com>

See: https://issues.redhat.com/browse/KOGITO-3549

TODO:

- [x] Finish Unit Tests for the resource gen
- [x] Integrate this new generator to codegen
- [x] Create a test in the kogito-examples

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.md)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by ricardozanini** [comment]
/jenkins test

Jenkins test this please

JeNkInS TeST ThIs now

**Review by cristianonicolai — COMMENTED** [review]
@ricardozanini overall looks good, would just recommend adding a integration test to verify and interact with the new endpoint.

**Comment by ricardozanini** [comment]
> @ricardozanini overall looks good, would just recommend adding a integration test to verify and interact with the new endpoint.

I'd love to, but I haven't found an example in our code base, do you have an example of integration tests running on `kogito-codegen`? I would use it as a reference. My idea was to generate the code itself, compile and run the rest calls within this module.

**Comment by cristianonicolai** [comment]
@ricardozanini, all projects under https://github.com/kiegroup/kogito-runtimes/tree/master/integration-tests should be useful in that way, is not that you're testing the codegen alone, but a complete and final app that you can interact with the generated endpoint. Perhaps you just need to add some process with a topic usage to _integration-tests-quarkus-processes_ if none is there already.

**Comment by ricardozanini** [comment]
Cool! I'll add more tests in there, I didn't know about this! Thanks for pointing that out.

**Review by cristianonicolai — APPROVED** [review]

**Comment by ricardozanini** [comment]
@evacchi @MarianMacik could you please review? This PR is rotting here for some time. I need it for an operator work with Knative integration.

**Review by evacchi — APPROVED** [review]
looks good let's make sure this does not break though: https://github.com/kiegroup/kogito-runtimes/pull/807

**Comment by ricardozanini** [comment]
@evacchi I believe we can review this use case, since will impact the operator as well.

**Pull request merged**
