### PR TITLE
KOGITO-2705 - Add kie-dmn-jpmml and kie-dmn-validation to parent pom

### PR DESCRIPTION
**Pull request by mswiderski**
Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](CONTRIBUTING.md)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by mswiderski** [comment]
@cristianonicolai @tarilabs would you mind to take a look?

**Comment by tarilabs** [comment]
I am not sure it makes sense to add the jpmml one, being an optional, opt-in extension. Otherwise good for me! 👍

**Comment by mswiderski** [comment]
it just adds to use managed version otherwise it has to be manually updated as reuse of `version.org.kie7` in the downstream applications is not really possible. So it's easy to get into mixed version and conflicts by forgetting one small update of the version :)

**Comment by mswiderski** [comment]
@danielezonca both are fine for me which still requires this changes anyway, right?

I can add the additional pom.xml changes to the Kogito-dmn module, would someone else be willing to add changes in kie-dmn-jpmml?

**Comment by danielezonca** [comment]
@mswiderski 
Yes both comments are in addition to these changes :)
Can you please apply suggested changed to this repo?

Here is the PR to `kie-dmn-jpmml` https://github.com/kiegroup/kie-jpmml-integration/pull/33

**Comment by mswiderski** [comment]
@danielezonca updated, please have a look if this is what you had in mind

**Pull request merged**
