### PR TITLE
[KOGITO-6561] Fix native compilation issue for json node

### PR DESCRIPTION
**Pull request by fjtirado**

### CODE REVIEW

**Review by radtriste — APPROVED** [review]

**Comment by radtriste** [comment]
jenkins run native

**Comment by fjtirado** [comment]
There are additional failures in native compilation that deserve attention. Looking into them

**Comment by fjtirado** [comment]
Ok, It seems that Kogito-6022 change some things that break changes performed by Kogito-6430 to make native work. Need to discuss with @elguardian to find out a common approach

**Review by evacchi — APPROVED** [review]

**Comment by fjtirado** [comment]
@radtriste I have to work more on this. I need to incorporate the  Kogito-6430 changes that were made innefective when Kogito-6022 was merged

**Comment by fjtirado** [comment]
jenkins run native

**Comment by fjtirado** [comment]
jenkins run native

**Pull request merged**
