### PR TITLE
[KOGITO-5366]  Incorrect object type returned in a DMN business-rule task of a BPMN (RuleSetNode Instance)

### PR DESCRIPTION
**Pull request by elguardian**
jira: https://issues.redhat.com/browse/KOGITO-5366

### CODE REVIEW

**Review by tiagodolphine — APPROVED** [review]
LGTM, thanks!!

**Comment by tiagodolphine** [comment]
Hi, @MarianMacik can you take a look at this one? it is just porting the solution implemented in v7. Thanks.

**Comment by cristianonicolai** [comment]
Jenkins rerun examples tests

**Review by cristianonicolai — APPROVED** [review]

**Review by cristianonicolai — COMMENTED** [review]
@elguardian could you add some test to verify the types are correctly returned now?

**Comment by tiagodolphine** [comment]
@cristianonicolai can we merge? we can add the tests later on a new JIRA or port the same tests from V7. Just to unblock the PR wdyt?

**Review by cristianonicolai — APPROVED** [review]

**Pull request merged**
