### PR TITLE
[master] [KOGITO-1666] Updated pipelines to checkout from env.BRANCH_NAME

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/KOGITO-1666

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@radtriste can you please also add the branch name to the email subject

**Comment by radtriste** [comment]
Latest deploy run with this change:

https://repository.jboss.org/nexus/content/repositories/snapshots/org/kie/kogito/kogito-bom/0.9.1-SNAPSHOT/
https://repository.jboss.org/nexus/content/repositories/snapshots/org/kie/kogito/jobs-service/0.9.1-SNAPSHOT/
https://repository.jboss.org/nexus/content/repositories/snapshots/org/kie/kogito/examples/jbpm-quarkus-example/0.9.1-SNAPSHOT/

**Comment by radtriste** [comment]
This is PR https://github.com/kiegroup/kogito-runtimes/pull/411 :)

Indeed I enabled the deploy pipeline on 0.9.x branch

**Comment by MarianMacik** [comment]
Sorry, didn't notice :)

**Comment by radtriste** [comment]
worked on master

**Pull request merged**
