### PR TITLE
Bump Quarkus 2.1.0.Final

### PR DESCRIPTION
**Pull request by radtriste**
Related PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/1465
- https://github.com/kiegroup/optaplanner/pull/1451
- https://github.com/kiegroup/optaplanner-quickstarts/pull/145
- https://github.com/kiegroup/kogito-apps/pull/964
- https://github.com/kiegroup/kogito-examples/pull/810

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](CONTRIBUTING.md)
- [ ] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/master/kogito-build/kogito-ide-config)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Run all builds</b>  
  Please add comment: <b>Jenkins retest this</b>

* <b>Run (or rerun) specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [runtimes|optaplanner|apps|examples] tests</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Run (or rerun) LTS specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [runtimes|optaplanner|apps|examples] LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

* <b>Run (or rerun) native specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [runtimes|optaplanner|apps|examples] native</b>

* <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

### CODE REVIEW

**Review by danielezonca — APPROVED** [review]

**Review by cristianonicolai — APPROVED** [review]

**Comment by radtriste** [comment]
@danielezonca for runtimes, it is setting `mongo` version 4.3.0 as stated in `quarkus-bom` for the [mongo-client](https://github.com/quarkusio/quarkus/blob/2.1/bom/application/pom.xml#L165)
One problem is that the `mongo:4.3.0` image [does not exist](https://github.com/docker-library/mongo) ...
Should we stay with mongo `4.2.3` ? or separate client and image version ?

**Comment by radtriste** [comment]
@cristianonicolai for apps, there is this error coming often in tests
```
org.kie.kogito.persistence.protobuf.ProtobufValidationException: Method "property('kogito.cache.domain.template')" not found on the base object "null" in expression {config:property('kogito.cache.domain.template')} in template kogito-cache-default.xml on line 3
```
can you have a look ?

**Comment by radtriste** [comment]
For examples, I increased the timeout there: https://github.com/kiegroup/kogito-examples/pull/810

**Comment by radtriste** [comment]
jenkins rerun examples tests

**Comment by danielezonca** [comment]
> @danielezonca for runtimes, it is setting `mongo` version 4.3.0 as stated in `quarkus-bom` for the [mongo-client](https://github.com/quarkusio/quarkus/blob/2.1/bom/application/pom.xml#L165)
> One problem is that the `mongo:4.3.0` image [does not exist](https://github.com/docker-library/mongo) ...
> Should we stay with mongo `4.2.3` ? or separate client and image version ?

Yes let's try with `4.2.3` 👍

**Comment by radtriste** [comment]
jenkins rerun runtimes tests

**Pull request merged**
