### PR TITLE
[KOGITO-4052] Changed type of kie-pmml-dependencies and bump kie7 to 7.48.0.Final

### PR DESCRIPTION
**Pull request by gitgabrio**
@danielezonca @mariofusco @jiripetrlik

See https://issues.redhat.com/browse/KOGITO-4052

Reflecting change of kie-pmml-dependencies pom -> jar

### CODE REVIEW

**Comment by gitgabrio** [comment]
Superseded by https://github.com/kiegroup/kogito-runtimes/pull/973

**Comment by gitgabrio** [comment]
@danielezonca @mariofusco @jiripetrlik

Could you please review/approve/merge this that is needed by next Kogito release ? Thanks

**Review by danielezonca — APPROVED** [review]

**Comment by danielezonca** [comment]
Thanks for the PR, approved but cannot be merged before `7.48.0.Final` release

@radtriste @evacchi @cristianonicolai 
Reminder that this PR has to be merged together with `7.48.0.Final` bump to have a green build

**Comment by radtriste** [comment]
do we have also a backport to 1.1.x ?

**Comment by evacchi** [comment]
@radtriste yes
@danielezonca this is red, even though it's bumping to snapshot. Is it ok?

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by danielezonca** [comment]
> @radtriste yes
> @danielezonca this is red, even though it's bumping to snapshot. Is it ok?

@evacchi 
Guess what? Forked kie-internal to be aligned :) 

@gitgabrio 
Thanks for fixing it :+1:

**Comment by evacchi** [comment]
@danielezonca shall we just bump to final with this PR ? if this is _required_ then bumping to Final alone will never be green

**Comment by danielezonca** [comment]
Yes if `7.48.0.Final` has been published we can use this PR for bump and then cherry pick on 1.1.x

**Comment by evacchi** [comment]
ok thx @danielezonca

**Comment by danielezonca** [comment]
jenkins retest this please

**Review by mariofusco — APPROVED** [review]

**Comment by danielezonca** [comment]
jenkins retest this please

**Review by jiripetrlik — COMMENTED** [review]
I'm a little bit confused about the scope and intentions in this PR. According to description and JIRA you are trying to change "dependencies declaration", but it seems that there are some changes about how PMML commands are handled. Please provide more info about what is the intention of these changes. Also it seems there is no code coverage for new code.

**Comment by danielezonca** [comment]
> I'm a little bit confused about the scope and intentions in this PR. According to description and JIRA you are trying to change "dependencies declaration", but it seems that there are some changes about how PMML commands are handled. Please provide more info about what is the intention of these changes. Also it seems there is no code coverage for new code.

@jiripetrlik 
The problem is the `kie-api` fork that we have [in Kogito](https://github.com/kiegroup/kogito-runtimes/tree/master/api/kogito-internal). So it is not enough to propagate the new behavior (aka different dependency type) but also copy some classes from `kie-internal` (this module https://github.com/kiegroup/droolsjbpm-knowledge/tree/master/kie-internal/src/main/java/org/kie/internal/pmml )
We plan to refactor api to avoid this fork soon but for now it is necessary to perform manual forward port

**Review by jiripetrlik — APPROVED** [review]
@danielezonca 
Thank you for your explanation. Approved.

**Pull request merged**
