### PR TITLE
[KOGITO-5511] - Downgrade SpringBoot to 2.3.x

### PR DESCRIPTION
**Pull request by ricardozanini**
Signed-off-by: Ricardo Zanini <zanini@redhat.com>

See: https://issues.redhat.com/browse/KOGITO-5511

Downgrading to SB 2.3.x to align with the Runtimes release. I've kept the Junit 5 migration since SB 2.3.x supports it. There's no reason to revert that.

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.md)
- [x] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/master/kogito-build/kogito-ide-config)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Run all builds</b>  
  Please add comment: <b>Jenkins retest this</b>

* <b>Run (or rerun) specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [runtimes|optaplanner|apps|examples] tests</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Run (or rerun) LTS specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [runtimes|optaplanner|apps|examples] LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

* <b>Run (or rerun) native specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [runtimes|optaplanner|apps|examples] native</b>

* <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

### CODE REVIEW

**Comment by ricardozanini** [comment]
jenkins rerun runtimes test

**Comment by ricardozanini** [comment]
Jenkins rerun runtimes tests

**Comment by ricardozanini** [comment]
Jenkins rerun apps tests

**Comment by ricardozanini** [comment]
Jenkins rerun examples tests

**Comment by ricardozanini** [comment]
Jenkins rerun runtimes tests

**Review by cristianonicolai — APPROVED** [review]

**Review by danielezonca — APPROVED** [review]

**Comment by ricardozanini** [comment]
Updated to 2.3.**10** based on internal conversation and other projects aligments.

**Comment by ricardozanini** [comment]
Jenkins rerun Optaplanner tests

**Comment by ricardozanini** [comment]
Jenkins rerun runtimes tests

**Comment by ricardozanini** [comment]
Jenkins rerun apps tests

**Comment by ricardozanini** [comment]
Jenkins rerun optaplanner tests
Jenkins rerun runtimes tests

**Comment by ricardozanini** [comment]
@cristianonicolai @danielezonca can you guys please keep running the CI if it fails in your TZ?

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
Jenkins rerun runtimes tests

**Comment by ricardozanini** [comment]
Jenkins rerun examples tests

**Pull request merged**
