### PR TITLE
Bump Quarkus 2.0.1.Final

### PR DESCRIPTION
**Pull request by evacchi**
bundle:

- https://github.com/kiegroup/kogito-runtimes/pull/1422
- https://github.com/kiegroup/optaplanner/pull/1413
- https://github.com/kiegroup/optaplanner-quickstarts/pull/133

### CODE REVIEW

**Comment by radtriste** [comment]
jenkins rerun apps checks

**Comment by cristianonicolai** [comment]
Jenkins rerun apps tests

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
Jenkins rerun apps tests

**Review by cristianonicolai — APPROVED** [review]

**Pull request merged**
