### PR TITLE
KOGITO-5070 Setup multijob pipeline

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/KOGITO-5070

This will allow to run Jenkins pr check, if `multijob-pr` label is set, in separate jobs.
Also, each project check is responsible to set correct Jenkinsfile and this avoids to rewrite the commands to run in each repo for the downstream projects.

_For now, this does not replace the current global PR check. It is only activated with the `multijob-pr` label._

Depends on https://github.com/kiegroup/kogito-pipelines/pull/148

Related PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/1284
- https://github.com/kiegroup/optaplanner/pull/1304
- https://github.com/kiegroup/kogito-apps/pull/805
- https://github.com/kiegroup/kogito-examples/pull/671

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.md)
- [x] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/master/kogito-ide-config)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

* <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

_Final note: Current run PR checks for this PR are from my custom folder on Jenkins and will be moved to Kogito folder once all the PRs are merged. Please do not use before ..._

### CODE REVIEW

**Review by msmagnanijr — APPROVED** [review]

**Comment by radtriste** [comment]
Jenkins test this

**Comment by radtriste** [comment]
jenkins run multijob tests

**Comment by radtriste** [comment]
jenkins run multijob tests

**Comment by radtriste** [comment]
jenkins run multijob lts

**Comment by radtriste** [comment]
jenkins retest this

**Comment by radtriste** [comment]
jenkins retest this

**Comment by radtriste** [comment]
Jenkins retest this

**Review by danielezonca — APPROVED** [review]

**Comment by radtriste** [comment]
Jenkins retest this

**Comment by radtriste** [comment]
jenkins retest this

**Comment by radtriste** [comment]
jenkins run multijob runtimes tests

**Comment by radtriste** [comment]
Jenkins run LTS

**Comment by radtriste** [comment]
Jenkins run native

**Comment by radtriste** [comment]
Jenkins retest this

**Comment by radtriste** [comment]
Jenkins rerun apps tests

**Comment by radtriste** [comment]
jenkins rerun apps tests

**Comment by radtriste** [comment]
Jenkins retest this

**Comment by radtriste** [comment]
Jenkins retest this

**Comment by radtriste** [comment]
Jenkins rerun runtimes tests

**Comment by radtriste** [comment]
Jenkins rerun optaplanner

**Comment by radtriste** [comment]
jenkins rerun apps tests

**Comment by radtriste** [comment]
jenkins rerun optaplanner tests

**Comment by radtriste** [comment]
Jenkins rerun examples

**Comment by radtriste** [comment]
Jenkins rerun apps

**Comment by radtriste** [comment]
Jenkins rerun examples tests

**Comment by radtriste** [comment]
Jenkins rerun apps tests

**Comment by radtriste** [comment]
jenkins rerun optaplanner tests

**Comment by radtriste** [comment]
jenkins rerun apps tests

**Comment by radtriste** [comment]
jenkins rerun apps tests

**Comment by radtriste** [comment]
Tests on a release branch: https://github.com/kiegroup/kogito-runtimes/pull/1338

**Comment by radtriste** [comment]
jenkins retest this

**Comment by radtriste** [comment]
jenkins rerun apps tests

**Comment by radtriste** [comment]
jenkins rerun apps tests

**Comment by radtriste** [comment]
jenkins rerun apps tests

**Pull request merged**
