### PR TITLE
KOGITO-6145 DMN codegen heuristic for DMN Editor encoding

### PR DESCRIPTION
**Pull request by tarilabs**
https://issues.redhat.com/browse/KOGITO-6145

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Run all builds</b>  
  Please add comment: <b>Jenkins retest this</b>

* <b>Run (or rerun) specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] tests</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Run (or rerun) LTS specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

* <b>Run (or rerun) native specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] native</b>

* <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

### CODE REVIEW

**Comment by tarilabs** [comment]
Before. On Win10 with default encoding for EMEA (non-UTF8) breaks with:

Screenshot 2021-11-09 110047

**Comment by tarilabs** [comment]
Before. On Mac OSX (EMEA located) the problem does not replicate as by default UTF8 is accounted.

Screenshot 2021-11-09 at 11 32 58 (2)

**Comment by tarilabs** [comment]
After.  On Win10 with default encoding for EMEA (non-UTF8) the heuristic kicks-in and the file is explicitly read by Reader with UTF8 encoding:

Screenshot 2021-11-09 130518

**Comment by tarilabs** [comment]
Jenkins retest this

**Comment by tarilabs** [comment]
Jenkins issue not related
```
java.nio.file.NoSuchFileException: /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.kogito-runtimes/.ci/actions/build-chain/action.yml
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at hudson.FilePath.newInputStreamDenyingSymlinkAsNeeded(FilePath.java:2113)
	at hudson.FilePath$Read.invoke(FilePath.java:2195)
	at hudson.FilePath$Read.invoke(FilePath.java:2182)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3317)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:376)
	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
Caused: java.io.IOException
```

**Comment by Ginxo** [comment]
Jenkins retest

**Comment by Ginxo** [comment]
Jenkins retest this

**Comment by tarilabs** [comment]
the Jenkins -examples failure likely unrelated since the analogous GHA is passing

image

(it also pertains to unrelated tests)

**Review by pibizza — APPROVED** [review]
Looks good to me

**Pull request merged**
