### PR TITLE
KOGITO-4594 kogito-runtimes has dependency for narayana

### PR DESCRIPTION
**Pull request by evacchi**
Exclude useless transitive dependency on narayana-bom

### CODE REVIEW

**Review by danielezonca — COMMENTED** [review]
What about create a `kie7-bom` where we declare all 7 modules with exclusions (if needed) instead of this?
The current PR is probably solving the issue because `kie-api` is a transitive dependency if many modules and it is enough to reach any kie7 API to have again to add a similar exclusion

**Comment by jomarko** [comment]
reading the discussion on jira, I think we should close his PR, am I right?

**Comment by MarianMacik** [comment]
@danielezonca As I said in the JIRA, even if you create such a bom, it won't help as the pulled dependencies are BOMs (Narayana BOM, Thorntail BOM etc.) which Maven needs to download in order to properly resolve kie-parent.

**Comment by mareknovotny** [comment]
First the idea of BOM is just for dependency management not for including dependency into build chain.
Second we know that drools or kie-api will pull the  v7 dependencies and kie-parent behind it. So better to limit only real dependencies, not the BOM itself.

Is it really problem to let maven resolve BOMs or actual dependencies?

**Comment by evacchi** [comment]
Closing this as it doesn't really solve the issue (well, if any)

**Pull request closed without merging**
