### PR TITLE
bump to kie 7.45

### PR DESCRIPTION
**Pull request by mariofusco**

### CODE REVIEW

**Comment by mariofusco** [comment]
This includes and replaces both https://github.com/kiegroup/kogito-runtimes/pull/829 and https://github.com/kiegroup/kogito-runtimes/pull/838

**Comment by danielezonca** [comment]
@mariofusco 
You need to include these changes too
https://github.com/kiegroup/kogito-apps/pull/490

**Review by danielezonca — APPROVED** [review]
LGTM :+1:

**Comment by mariofusco** [comment]
Build succeeded here https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/blue/organizations/jenkins/KIE%2Fkogito%2Fghprb-webhooks%2Fkogito-runtimes/detail/kogito-runtimes/1757/pipeline/

**Pull request merged**
