### PR TITLE
[KOGITO-4231] Create codegen API and core + SPI for generators

### PR DESCRIPTION
**Pull request by danielezonca**
https://issues.redhat.com/browse/KOGITO-4231

Details:
- Created `kogito-codegen-modules` as root module for codegen modules
- Created `kogito-codegen-api` with only interfaces and utility classes (like `TemplatedGenerator`) all grouped in `api` package
- Created `kogito-codegen-core` with all wiring classes like `ApplicationGenerator` etc all grouped in `core` package
- Split `CollectedResource` and created `CollectedResourceProducer` with factory methods to avoid a `drools-core` dependency in api module
- Updated `CollectedResourceProducer` factory methods to use the same logic to create `CollectedResource`
- Updated `updateConfig` method in `Generator` to just return the generator and avoid an hard relation on `ApplicationConfigGenerator` class in API module
- Created `GeneratorFactory` to unify generator creations
- Updated `ApplicationGeneratorDiscovery` to use SPI to load `GeneratorFactory`
- Added `priority` to `Generator` to impose a generator ordering. This is not ideal but it is the simplest way to have ordering, we will probably revisit this in the future because it is still not clear to me if the order is really relevant
- Renamed `FileGenerator` as `RuleFileGenerator` because it is Drools specific (`DroolsError`)

### CODE REVIEW

**Review by evacchi — APPROVED** [review]

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by danielezonca** [comment]
jenkins retest this please

**Review by MarianMacik — APPROVED** [review]

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by danielezonca** [comment]
jenkins retest this please

**Pull request merged**
