### PR TITLE
[1.13.x] KOGITO-6805 Remove dependencies to jbpm-flow

### PR DESCRIPTION
**Pull request by cristianonicolai**
Backport of https://github.com/kiegroup/kogito-runtimes/pull/2063

### CODE REVIEW

**Comment by kie-ci1** [comment]
**(tests) - kogito-examples job** `#53` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 415
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/53/testReport/org.acme.travel/MultiMessagingIT/Build_projects___testProcess/">Build projects / org.acme.travel.MultiMessagingIT.testProcess</a></summary>
org.opentest4j.AssertionFailedError: expected: <0> but was: <3><br/>	at org.acme.travel.MultiMessagingIT.testProcess(MultiMessagingIT.java:104)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/53/testReport/org.kie.kogito.examples.demo/OutboxIT/testSendProcessEvents/">org.kie.kogito.examples.demo.OutboxIT.testSendProcessEvents</a></summary>
org.awaitility.core.ConditionTimeoutException: Condition with lambda expression in org.kie.kogito.examples.demo.OutboxIT was not fulfilled within 4 minutes  10 seconds.<br/>	at org.kie.kogito.examples.demo.OutboxIT.testSendProcessEvents(OutboxIT.java:70)<br/>Caused by: java.net.ConnectException: Connection refused (Connection refused)<br/>	at org.kie.kogito.examples.demo.OutboxIT.lambda$testSendProcessEvents$0(OutboxIT.java:74)<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/53/display/redirect

**Review by ricardozanini — APPROVED** [review]

**Comment by cristianonicolai** [comment]
Jenkins rerun kogito-examples tests

**Review by tiagodolphine — APPROVED** [review]

**Comment by kie-ci1** [comment]
**(tests) - kogito-examples job** `#58` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 416
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/58/testReport/org.acme.travel/MultiMessagingIT/Build_projects___testProcess/">Build projects / org.acme.travel.MultiMessagingIT.testProcess</a></summary>
org.opentest4j.AssertionFailedError: expected: <0> but was: <3><br/>	at org.acme.travel.MultiMessagingIT.testProcess(MultiMessagingIT.java:104)<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/58/display/redirect

**Comment by cristianonicolai** [comment]
Jenkins rerun kogito-examples tests

**Review by MarianMacik — APPROVED** [review]

**Pull request merged**
