### PR TITLE
KOGITO-4092 Bump kie7 to 7.52.0.Final

### PR DESCRIPTION
**Pull request by evacchi**
related: https://github.com/kiegroup/optaplanner/pull/1256

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](CONTRIBUTING.md)
- [ ] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/master/kogito-ide-config)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

* <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

### CODE REVIEW

**Comment by triceo** [comment]
New PR: https://github.com/kiegroup/optaplanner/pull/1259

**Comment by evacchi** [comment]
jenkins retest this

**Comment by evacchi** [comment]
jenkins retest this

**Comment by evacchi** [comment]
Jenkins retest this

**Comment by danielezonca** [comment]
`Cannot contact kie-psi-rhel7-xlarge-1907: java.lang.InterruptedException`

jenkins retest this please

**Comment by evacchi** [comment]
jenkins retest this please

**Comment by evacchi** [comment]
jenkins retest

**Comment by evacchi** [comment]
jenkins retest this

**Comment by evacchi** [comment]
jenkins retest this

**Comment by evacchi** [comment]
restarted manually https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/blue/organizations/jenkins/KIE%2Fkogito%2Fpullrequest%2Fkogito-runtimes/detail/kogito-runtimes/1114/pipeline

**Comment by evacchi** [comment]
jenkins please retest this

**Comment by evacchi** [comment]
exit code 143 ?

jenkins please retest this

**Comment by evacchi** [comment]
redis timeout..

**Comment by evacchi** [comment]
jenkins please retest this

**Comment by evacchi** [comment]
jenkins retest this

**Comment by radtriste** [comment]
jenkins retest this

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
> exit code 143 ?
> 
exitcode = 128 + signal number. 

that means signal number is  15 -> SIGTERM from https://man7.org/linux/man-pages/man7/signal.7.html

**Comment by evacchi** [comment]
jenkins retest this please

**Comment by evacchi** [comment]
jenkins retest this please

**Comment by evacchi** [comment]
jenkins please retest this

**Review by radtriste — APPROVED** [review]

**Pull request merged**
