### PR TITLE
KOGITO-5806 FEEL in gateway, integration tests

### PR DESCRIPTION
**Pull request by tarilabs**
https://issues.redhat.com/browse/KOGITO-5806

follows up on 

* specifically: https://github.com/kiegroup/kogito-runtimes/pull/1562#issuecomment-910069114

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Run all builds</b>  
  Please add comment: <b>Jenkins retest this</b>

* <b>Run (or rerun) specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [runtimes|optaplanner|apps|examples] tests</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Run (or rerun) LTS specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [runtimes|optaplanner|apps|examples] LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

* <b>Run (or rerun) native specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [runtimes|optaplanner|apps|examples] native</b>

* <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

### CODE REVIEW

**Comment by tarilabs** [comment]
Jenkins retest this

**Comment by tarilabs** [comment]
```
testGatewayFEEL – org.kie.kogito.integrationtests.quarkus.GatewayFEELIT
<1s
Stacktrace
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
Caused by: java.lang.RuntimeException: Failed to start quarkus
Caused by: java.lang.RuntimeException: Unable to start HTTP server
Caused by: java.util.concurrent.ExecutionException: java.net.BindException: Address already in use
Caused by: java.net.BindException: Address already in use
```

🤔 

Jenkins rerun runtimes test

**Comment by tarilabs** [comment]
Jenkins run runtimes tests

**Comment by tarilabs** [comment]
```
testBoundaryTimersOnTask – org.kie.kogito.it.jobs.ProcessTimerIT
3s
Stacktrace
org.awaitility.core.ConditionTimeoutException: 
Assertion condition defined as a lambda expression in org.kie.kogito.it.jobs.BaseProcessTimerIT 1 expectation failed.
Expected status code <404> but was <200>.
 within 3 seconds.
Caused by: java.lang.AssertionError: 
1 expectation failed.
Expected status code <404> but was <200>.
```

Jenkins run apps tests

**Review by fjtirado — APPROVED** [review]
Great work Matteo!

**Comment by tarilabs** [comment]
```

[2021-09-10T11:28:56.178Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common FAILURE [  0.237 s]

[2021-09-10T11:28:56.178Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus SKIPPED

[2021-09-10T11:28:56.178Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Spring Boot SKIPPED

[2021-09-10T11:28:56.178Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service . SUCCESS [  0.038 s]

[2021-09-10T11:28:56.178Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Common SUCCESS [  0.467 s]

[2021-09-10T11:28:56.178Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Quarkus SUCCESS [01:36 min]

[2021-09-10T11:28:56.178Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Spring Boot SUCCESS [01:34 min]

[2021-09-10T11:28:56.178Z] [INFO] Kogito Apps :: Integration Tests :: Data Index ..... SUCCESS [  0.050 s]

[2021-09-10T11:28:56.178Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Common FAILURE [  0.515 s]

[2021-09-10T11:28:56.178Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Quarkus SKIPPED

[2021-09-10T11:28:56.178Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Spring Boot SKIPPED

[2021-09-10T11:28:56.178Z] [INFO] Kogito Apps :: Integration Tests :: Task Assigning Service SUCCESS [  0.051 s]

[2021-09-10T11:28:56.178Z] [INFO] Kogito Apps :: Integration Tests :: Task Assigning Service :: Processes SUCCESS [ 51.339 s]

[2021-09-10T11:28:56.178Z] [INFO] Kogito Apps :: Integration Tests :: Task Assigning Service :: Quarkus SKIPPED

[2021-09-10T11:28:56.178Z] [INFO] Runtime Tools Quarkus Extension - Parent ........... SUCCESS [  0.037 s]

[2021-09-10T11:28:56.178Z] [INFO] Runtime Tools Quarkus Extension - Runtime .......... SUCCESS [  3.062 s]

[2021-09-10T11:28:56.178Z] [INFO] Runtime Tools Quarkus Extension - Deployment ....... SUCCESS [  0.574 s]

[2021-09-10T11:28:56.178Z] [INFO] ------------------------------------------------------------------------

[2021-09-10T11:28:56.178Z] [INFO] BUILD FAILURE

[2021-09-10T11:28:56.178Z] [INFO] ------------------------------------------------------------------------

[2021-09-10T11:28:56.178Z] [INFO] Total time:  01:08 h

[2021-09-10T11:28:56.178Z] [INFO] Finished at: 2021-09-10T07:28:55-04:00

[2021-09-10T11:28:56.178Z] [INFO] ------------------------------------------------------------------------

[2021-09-10T11:28:56.178Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project integration-tests-jobs-service-common: Compilation failure: Compilation failure: 

[2021-09-10T11:28:56.178Z] [ERROR] /home/jenkins/workspace/KIE/kogito/pullrequest/main/kogito-runtimes.tests.downstream.apps/kogito-apps/apps-integration-tests/integration-tests-jobs-service/integration-tests-jobs-service-common/src/main/java/org/kie/kogito/it/KogitoServiceRandomPortTestResource.java:[19,33] package org.kie.kogito.test.utils does not exist

[2021-09-10T11:28:56.178Z] [ERROR] /home/jenkins/workspace/KIE/kogito/pullrequest/main/kogito-runtimes.tests.downstream.apps/kogito-apps/apps-integration-tests/integration-tests-jobs-service/integration-tests-jobs-service-common/src/main/java/org/kie/kogito/it/KogitoServiceRandomPortTestResource.java:[37,20] cannot find symbol

[2021-09-10T11:28:56.178Z] [ERROR]   symbol:   variable SocketUtils

[2021-09-10T11:28:56.178Z] [ERROR]   location: class org.kie.kogito.it.KogitoServiceRandomPortTestResource

[2021-09-10T11:28:56.178Z] [ERROR] -> [Help 1]

[2021-09-10T11:28:56.178Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project integration-tests-data-index-service-common: Compilation failure: Compilation failure: 

[2021-09-10T11:28:56.178Z] [ERROR] /home/jenkins/workspace/KIE/kogito/pullrequest/main/kogito-runtimes.tests.downstream.apps/kogito-apps/apps-integration-tests/integration-tests-data-index-service/integration-tests-data-index-service-common/src/main/java/org/kie/kogito/index/resources/KogitoServiceRandomPortTestResource.java:[19,33] package org.kie.kogito.test.utils does not exist

[2021-09-10T11:28:56.436Z] [ERROR] /home/jenkins/workspace/KIE/kogito/pullrequest/main/kogito-runtimes.tests.downstream.apps/kogito-apps/apps-integration-tests/integration-tests-data-index-service/integration-tests-data-index-service-common/src/main/java/org/kie/kogito/index/resources/KogitoServiceRandomPortTestResource.java:[37,20] cannot find symbol

[2021-09-10T11:28:56.436Z] [ERROR]   symbol:   variable SocketUtils

[2021-09-10T11:28:56.436Z] [ERROR]   location: class org.kie.kogito.index.resources.KogitoServiceRandomPortTestResource
```

Jenkins run apps tests

**Review by cristianonicolai — APPROVED** [review]

**Review by MarianMacik — APPROVED** [review]

**Review by tiagodolphine — APPROVED** [review]

**Pull request merged**
