### PR TITLE
KOGITO-8597: Jobs Service OpenAPI document generation addings

### PR DESCRIPTION
**Pull request by wmedvede**
Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [X] You have read the [contributors guide](CONTRIBUTING.md)
- [X] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/main/kogito-build/kogito-ide-config)
- [X] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [X] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [X] Pull Request contains link to the JIRA issue
- [X] Pull Request contains link to any dependent or related Pull Request
- [X] Pull Request contains description of the issue
- [X] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] tests</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] quarkus-main</b>

- for <b>quarkus lts checks</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins run quarkus-lts</b>

- for a <b>specific quarkus lts check</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] quarkus-lts</b>

- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] native</b>

- for <b>native lts checks</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins run native-lts</b>

- for a <b>specific native lts check</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] native-lts</b>
 
- <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

### CODE REVIEW

**Comment by wmedvede** [comment]
Jenkins rerun kogito-runtimes tests

**Comment by wmedvede** [comment]
Jeninks rerun kogito-apps tests

**Comment by wmedvede** [comment]
Jenkins rerun kogito-apps tests

**Comment by wmedvede** [comment]
Jenkins rerun kogito-springboot-examples tests

**Comment by wmedvede** [comment]
Jenkins rerun kogito-quarkus-examples tests

**Comment by kie-ci3** [comment]
**(tests) - kogito-apps job** `#2163` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/2163/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
using credential kie-ci3<br/> > git rev-parse --resolve-git-dir /var/jenkins_home/jobs/KIE/jobs/kogito/jobs/main/jobs/pullrequest/jobs/kogito-runtimes.tests.downstream.kogito-apps/workspace@script/ee10b829cbd0ac763d0be6f0356db3418b2d4469e9daa1842e842313521cde92/.git # timeout=10<br/>Fetching changes from the remote Git repository<br/> > git config remote.origin.url https://github.com/kiegroup/kogito-pipelines.git # timeout=10<br/>Cleaning workspace<br/> > git rev-parse --verify HEAD # timeout=10<br/>Resetting working tree<br/> > git reset --hard # timeout=10<br/> > git clean -fdx # timeout=10<br/>Fetching upstream changes from https://github.com/kiegroup/kogito-pipelines.git<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.31.1'<br/>using GIT_ASKPASS to set credentials PSSWD: kie-ci3 account to access GitHub via token<br/> > git fetch --tags --force --progress -- https://github.com/kiegroup/kogito-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git rev-parse origin/main^{commit} # timeout=10<br/>Checking out Revision 01d059b0bddd0c07ed658566c831a32633e34256 (origin/main)<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f 01d059b0bddd0c07ed658566c831a32633e34256 # timeout=10<br/>Commit message: "KOGITO-8737 Setup integration branch nightlies on pipelines (#895)"<br/> > git rev-list --no-walk 01d059b0bddd0c07ed658566c831a32633e34256 # timeout=10<br/>Loading library jenkins-pipeline-shared-libraries@main<br/>Attempting to resolve main from remote references...<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.31.1'<br/>using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space<br/>[INFO] Currently running in a labeled security context<br/> > /usr/bin/chcon --type=ssh_home_t /tmp/jenkins-gitclient-ssh11434129977407002817.key<br/>Verifying host key using manually-configured host key entries<br/> > git ls-remote -h -- https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10<br/>Found match: refs/heads/main revision 5fa4e6902164a47f3f332b1810639068dfd51426<br/>The recommended git tool is: NONE<br/>using credential kie-ci-user-key<br/> > git rev-parse --resolve-git-dir /var/jenkins_home/jobs/KIE/jobs/kogito/jobs/main/jobs/pullrequest/jobs/kogito-runtimes.tests.downstream.kogito-apps/workspace@libs/d03f8b53ef89e88ec2b15428a250a4b1fb7910bfcdd3e1c33e4e95c3adb758bb/.git # timeout=10<br/>Fetching changes from the remote Git repository<br/> > git config remote.origin.url https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10<br/>Fetching without tags<br/>Fetching upstream changes from https://github.com/kiegroup/jenkins-pipeline-shared-libraries<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.31.1'<br/>using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space<br/>[INFO] Currently running in a labeled security context<br/> > /usr/bin/chcon --type=ssh_home_t /var/jenkins_home/jobs/KIE/jobs/kogito/jobs/main/jobs/pullrequest/jobs/kogito-runtimes.tests.downstream.kogito-apps/workspace@libs/d03f8b53ef89e88ec2b15428a250a4b1fb7910bfcdd3e1c33e4e95c3adb758bb@tmp/jenkins-gitclient-ssh14751784304219153527.key<br/>Verifying host key using manually-configured host key entries<br/> > git fetch --no-tags --force --progress -- https://github.com/kiegroup/jenkins-pipeline-shared-libraries +refs/heads/*:refs/remotes/origin/* # timeout=10<br/>Checking out Revision 5fa4e6902164a47f3f332b1810639068dfd51426 (main)<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f 5fa4e6902164a47f3f332b1810639068dfd51426 # timeout=10<br/>Commit message: "Added Maven Settings server (#265)"<br/> > git rev-list --no-walk 5fa4e6902164a47f3f332b1810639068dfd51426 # timeout=10<br/>[Pipeline] Start of Pipeline<br/>[Pipeline] node<br/>Running on rhos-01-kie-psi-rhel7-xlarge-338 in /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-apps<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Checkout SCM)<br/>[Pipeline] checkout<br/>The recommended git tool is: NONE<br/>using credential kie-ci3<br/>Cloning the remote Git repository<br/>Avoid second fetch<br/>Checking out Revision 01d059b0bddd0c07ed658566c831a32633e34256 (origin/main)<br/>Commit message: "KOGITO-8737 Setup integration branch nightlies on pipelines (#895)"<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] timestamps<br/>[Pipeline] {<br/>[Pipeline] timeout<br/>[2023-03-02T14:14:45.144Z] Timeout set to expire in 3 hr 0 min<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Tool Install)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] }<br/>Cloning repository https://github.com/kiegroup/kogito-pipelines.git<br/> > git init /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-apps # timeout=10<br/>Fetching upstream changes from https://github.com/kiegroup/kogito-pipelines.git<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.39.2'<br/>using GIT_ASKPASS to set credentials PSSWD: kie-ci3 account to access GitHub via token<br/> > git fetch --tags --force --progress -- https://github.com/kiegroup/kogito-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git config remote.origin.url https://github.com/kiegroup/kogito-pipelines.git # timeout=10<br/> > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git rev-parse origin/main^{commit} # timeout=10<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f 01d059b0bddd0c07ed658566c831a32633e34256 # timeout=10<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Initialize)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2023-03-02T14:14:45.750Z] + printenv<br/>[Pipeline] archiveArtifacts<br/>[2023-03-02T14:14:45.780Z] Archiving artifacts<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space before build)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] dir<br/>[2023-03-02T14:14:46.256Z] Running in /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-apps<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2023-03-02T14:14:46.290Z] [INFO] space left on the machine<br/>[Pipeline] sh<br/>[2023-03-02T14:14:46.568Z] + df -h<br/>[2023-03-02T14:14:46.569Z] Filesystem      Size  Used Avail Use% Mounted on<br/>[2023-03-02T14:14:46.569Z] devtmpfs        7.8G     0  7.8G   0% /dev<br/>[2023-03-02T14:14:46.569Z] tmpfs           7.8G     0  7.8G   0% /dev/shm<br/>[2023-03-02T14:14:46.569Z] tmpfs           7.8G   17M  7.8G   1% /run<br/>[2023-03-02T14:14:46.569Z] tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup<br/>[2023-03-02T14:14:46.569Z] /dev/vda1        80G   21G   60G  26% /<br/>[2023-03-02T14:14:46.569Z] tmpfs           1.6G     0  1.6G   0% /run/user/1000<br/>[Pipeline] echo<br/>[2023-03-02T14:14:46.597Z] [INFO] space of /home/jenkins<br/>[Pipeline] sh<br/>[2023-03-02T14:14:46.877Z] + du -h -d1 /home/jenkins<br/>[2023-03-02T14:14:46.878Z] 4.0K	/home/jenkins/.ssh<br/>[2023-03-02T14:14:46.878Z] 0	/home/jenkins/go<br/>[2023-03-02T14:14:46.878Z] 8.0K	/home/jenkins/.vnc<br/>[2023-03-02T14:14:46.878Z] 19M	/home/jenkins/.m2<br/>[2023-03-02T14:14:46.878Z] 2.2G	/home/jenkins/git-repos<br/>[2023-03-02T14:14:46.878Z] 4.0K	/home/jenkins/.config<br/>[2023-03-02T14:14:46.878Z] 131M	/home/jenkins/virtenvs<br/>[2023-03-02T14:14:46.878Z] 4.0K	/home/jenkins/.cekit<br/>[2023-03-02T14:14:46.878Z] 33M	/home/jenkins/remoting<br/>[2023-03-02T14:14:46.878Z] 65M	/home/jenkins/.cache<br/>[2023-03-02T14:14:46.878Z] 4.0M	/home/jenkins/workspace<br/>[2023-03-02T14:14:46.878Z] 0	/home/jenkins/.pki<br/>[2023-03-02T14:14:46.878Z] 119M	/home/jenkins/tools<br/>[2023-03-02T14:14:46.878Z] 0	/home/jenkins/caches<br/>[2023-03-02T14:14:46.878Z] 17M	/home/jenkins/.npm<br/>[2023-03-02T14:14:46.878Z] 445M	/home/jenkins/.gradle<br/>[2023-03-02T14:14:46.878Z] 3.0G	/home/jenkins<br/>[Pipeline] echo<br/>[2023-03-02T14:14:46.901Z] [INFO] space of workspace<br/>[Pipeline] sh<br/>[2023-03-02T14:14:47.179Z] + du -h -d3 /home/jenkins/workspace<br/>[2023-03-02T14:14:47.179Z] 4.0M	/home/jenkins/workspace/KIE/kogito/main<br/>[2023-03-02T14:14:47.179Z] 0	/home/jenkins/workspace/KIE/kogito/1.35.x<br/>[2023-03-02T14:14:47.179Z] 4.0M	/home/jenkins/workspace/KIE/kogito<br/>[2023-03-02T14:14:47.179Z] 0	/home/jenkins/workspace/KIE/drools/8.35.x<br/>[2023-03-02T14:14:47.179Z] 0	/home/jenkins/workspace/KIE/drools<br/>[2023-03-02T14:14:47.179Z] 4.0M	/home/jenkins/workspace/KIE<br/>[2023-03-02T14:14:47.179Z] 4.0M	/home/jenkins/workspace<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Install build-chain tool)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2023-03-02T14:14:47.493Z] [INFO] Getting build-chain version from composite action file<br/>[Pipeline] readFile<br/>[Pipeline] echo<br/>[2023-03-02T14:14:47.566Z] [INFO] build-chain version recovered '^v3'<br/>[Pipeline] sh<br/>[2023-03-02T14:14:47.845Z] + npm install -g '@kie/build-chain-action@^v3' -registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/<br/>[2023-03-02T14:14:49.726Z] <br/>[2023-03-02T14:14:49.726Z] changed 75 packages, and audited 76 packages in 2s<br/>[2023-03-02T14:14:49.726Z] <br/>[2023-03-02T14:14:49.726Z] 5 packages are looking for funding<br/>[2023-03-02T14:14:49.726Z]   run `npm fund` for details<br/>[2023-03-02T14:14:49.726Z] <br/>[2023-03-02T14:14:49.726Z] found 0 vulnerabilities<br/>[Pipeline] sh<br/>[2023-03-02T14:14:50.011Z] + npm list -g<br/>[2023-03-02T14:14:50.012Z] + grep build-chain<br/>[2023-03-02T14:14:50.570Z] ├── @kie/build-chain-action@3.0.21<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build quarkus)<br/>Stage "Build quarkus" skipped due to when conditional<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2023-03-02T14:14:51.081Z] BUILD_MVN_OPTS_CURRENT =  <br/>[Pipeline] configFileProvider<br/>[2023-03-02T14:14:51.095Z] provisioning config files...<br/>[2023-03-02T14:14:51.099Z] copy managed file [kogito_pr_settings] to file:/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-apps@tmp/config18059395010909110995tmp<br/>[Pipeline] {<br/>[Pipeline] withCredentials<br/>[2023-03-02T14:14:51.139Z] Masking supported pattern matches of $GITHUB_TOKEN<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2023-03-02T14:14:51.181Z] BUILD_MVN_OPTS =  -s /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-apps@tmp/config18059395010909110995tmp -Dmaven.wagon.http.ssl.insecure=true -Dmaven.test.failure.ignore=true<br/>[Pipeline] sh<br/>[2023-03-02T14:14:51.201Z] Warning: A secret was passed to "sh" using Groovy String interpolation, which is insecure.<br/>[2023-03-02T14:14:51.201Z] 		 Affected argument(s) used the following variable(s): [GITHUB_TOKEN]<br/>[2023-03-02T14:14:51.201Z] 		 See https://jenkins.io/redirect/groovy-string-interpolation for details.<br/>[2023-03-02T14:14:51.467Z] + build-chain build cross_pr --token **** -f https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml -o bc -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-runtimes/pull/2844 --skipParallelCheckout<br/>[2023-03-02T14:14:53.380Z] # Executing pre section<br/>[2023-03-02T14:14:53.380Z] [command]/usr/bin/echo BUILD_MVN_OPTS= -s /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-apps@tmp/config18059395010909110995tmp -Dmaven.wagon.http.ssl.insecure=true -Dmaven.test.failure.ignore=true -nsu -ntp -fae -e -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3<br/>[2023-03-02T14:14:53.380Z] BUILD_MVN_OPTS= -s /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-apps@tmp/config18059395010909110995tmp -Dmaven.wagon.http.ssl.insecure=true -Dmaven.test.failure.ignore=true -nsu -ntp -fae -e -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3<br/>[2023-03-02T14:14:53.380Z] [command]/usr/bin/echo BUILD_MVN_OPTS_CURRENT=  dependency:tree<br/>[2023-03-02T14:14:53.380Z] BUILD_MVN_OPTS_CURRENT=  dependency:tree<br/>[2023-03-02T14:14:53.380Z] [command]/usr/bin/echo QUARKUS_VERSION=<br/>[2023-03-02T14:14:53.380Z] QUARKUS_VERSION=<br/>[2023-03-02T14:14:53.380Z] [command]/usr/bin/echo ENABLE_DEPLOY=<br/>[2023-03-02T14:14:53.380Z] ENABLE_DEPLOY=<br/>[2023-03-02T14:14:53.380Z]  <br/>[2023-03-02T14:14:53.380Z] # Execution Plan<br/>[2023-03-02T14:14:53.380Z] [INFO] 3 projects will be executed<br/>[2023-03-02T14:14:53.380Z] [INFO] [kiegroup/drools]<br/>[2023-03-02T14:14:53.380Z] [INFO] 	 Level type: upstream<br/>[2023-03-02T14:14:53.380Z] [INFO] 	 [before]<br/>[2023-03-02T14:14:53.380Z] [INFO] 		 export INTEGRATION_BRANCH=${{ env.INTEGRATION_BRANCH_UPSTREAM }}<br/>[2023-03-02T14:14:53.380Z] bash -c "if [ ! -z '${{ env.BUILD_ENVIRONMENT }}' ] && [ -f .ci/environments/update.sh ]; then .ci/environments/update.sh "${{ env.BUILD_ENVIRONMENT }}"; fi"<br/>[2023-03-02T14:14:53.380Z] [INFO] 	 [commands]<br/>[2023-03-02T14:14:53.380Z] [INFO] 		 mvn clean install -Dquickly ${{ env.BUILD_MVN_OPTS }} ${{ env.BUILD_MVN_OPTS_UPSTREAM }} ${{ env.DROOLS_BUILD_MVN_OPTS_UPSTREAM }}<br/>[2023-03-02T14:14:53.380Z] [INFO] 	 [after]<br/>[2023-03-02T14:14:53.380Z] [INFO] 		 docker system prune -f<br/>[2023-03-02T14:14:53.380Z] [INFO] [kiegroup/kogito-runtimes]<br/>[2023-03-02T14:14:53.380Z] [INFO] 	 Level type: upstream<br/>[2023-03-02T14:14:53.380Z] [INFO] 	 [before]<br/>[2023-03-02T14:14:53.380Z] [INFO] 		 export INTEGRATION_BRANCH=${{ env.INTEGRATION_BRANCH_UPSTREAM }}<br/>[2023-03-02T14:14:53.380Z] bash -c "if [ ! -z '${{ env.BUILD_ENVIRONMENT }}' ] && [ -f .ci/environments/update.sh ]; then .ci/environments/update.sh "${{ env.BUILD_ENVIRONMENT }}"; fi"<br/>[2023-03-02T14:14:53.380Z] [INFO] 	 [commands]<br/>[2023-03-02T14:14:53.380Z] [INFO] 		 mvn clean install -Dquickly ${{ env.BUILD_MVN_OPTS }} ${{ env.BUILD_MVN_OPTS_UPSTREAM }} ${{ env.KOGITO_RUNTIMES_BUILD_MVN_OPTS_UPSTREAM }}<br/>[2023-03-02T14:14:53.380Z] [INFO] 	 [after]<br/>[2023-03-02T14:14:53.380Z] [INFO] 		 docker system prune -f<br/>[2023-03-02T14:14:53.381Z] [INFO] [kiegroup/kogito-apps]<br/>[2023-03-02T14:14:53.381Z] [INFO] 	 Level type: current<br/>[2023-03-02T14:14:53.381Z] [INFO] 	 [before]<br/>[2023-03-02T14:14:53.381Z] [INFO] 		 export INTEGRATION_BRANCH=${{ env.INTEGRATION_BRANCH_CURRENT }}<br/>[2023-03-02T14:14:53.381Z] bash -c "if [ ! -z '${{ env.BUILD_ENVIRONMENT }}' ] && [ -f .ci/environments/update.sh ]; then .ci/environments/update.sh "${{ env.BUILD_ENVIRONMENT }}"; fi"<br/>[2023-03-02T14:14:53.381Z] [INFO] 	 [commands]<br/>[2023-03-02T14:14:53.381Z] [INFO] 		 export MVN_CMD=`bash -c "if [ '${{ env.ENABLE_DEPLOY }}' = 'true' ]; then printf 'deploy ${{ env.DEPLOY_MVN_OPTS }} ${{ env.KOGITO_APPS_DEPLOY_MVN_OPTS }}'; else printf 'install'; fi"`<br/>[2023-03-02T14:14:53.381Z] mvn clean ${{ env.MVN_CMD }} ${{ env.BUILD_MVN_OPTS }} ${{ env.BUILD_MVN_OPTS_CURRENT }} ${{ env.KOGITO_APPS_BUILD_MVN_OPTS }}<br/>[2023-03-02T14:14:53.381Z] [INFO] 	 [after]<br/>[2023-03-02T14:14:53.381Z] [INFO] 		 docker system prune -f<br/>[2023-03-02T14:14:53.381Z]  <br/>[2023-03-02T14:14:53.381Z] # Checking out kiegroup/kogito-apps and its dependencies (3 projects in total). It can take some time.<br/>[2023-03-02T14:15:39.969Z] [INFO] kiegroup/drools checked out<br/>[2023-03-02T14:17:46.333Z] [ERROR] [kiegroup/kogito-runtimes] Error cloning kiegroup/kogito-runtimes and switching to target branch main<br/>[Pipeline] }<br/>[Pipeline] // withCredentials<br/>[Pipeline] }<br/>[2023-03-02T14:17:46.405Z] Deleting 1 temporary files<br/>[Pipeline] // configFileProvider<br/>[Pipeline] }<br/>[Pipeline] // script<br/>Post stage<br/>[Pipeline] junit<br/>[2023-03-02T14:17:46.510Z] Recording test results<br/>[2023-03-02T14:17:46.670Z] [Checks API] No suitable checks publisher found.<br/>[Pipeline] archiveArtifacts<br/>[2023-03-02T14:17:46.687Z] Archiving artifacts<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2023-03-02T14:17:47.166Z] + rm -rf console.log<br/>[Pipeline] sh<br/>
</details>

**Comment by kie-ci3** [comment]
**(tests) - kogito-springboot-examples job** `#528` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-springboot-examples/528/display/redirect

**Test results:**
- PASSED: 129
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-springboot-examples/528/testReport/org.kie.kogito.springboot.outbox/OutboxIT/___/">org.kie.kogito.springboot.outbox.OutboxIT.(?)</a></summary>
org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/>	at org.kie.kogito.springboot.outbox.OutboxIT.before(OutboxIT.java:86)<br/>Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception<br/>	at org.kie.kogito.springboot.outbox.OutboxIT.before(OutboxIT.java:86)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container<br/>	at org.kie.kogito.springboot.outbox.OutboxIT.before(OutboxIT.java:86)<br/>Caused by: java.lang.IllegalStateException: Container did not start correctly.<br/>	at org.kie.kogito.springboot.outbox.OutboxIT.before(OutboxIT.java:86)<br/>
</details>

**Comment by wmedvede** [comment]
Jenkins rerun kogito-springboot-examples tests

**Review by tiagodolphine — APPROVED** [review]

**Pull request merged**
