### PR TITLE
KOGITO-250 - Generate REST endpoint for private processes but without…

### PR DESCRIPTION
**Pull request by mswiderski**
… option to create new instances, KOGITO-251 - Expose service url as part of the kogito events

### CODE REVIEW

**Comment by mswiderski** [comment]
Sonar was complaining about not high enough test coverage but the examples or should add to that to cover it

**Comment by cristianonicolai** [comment]
@mswiderski I think the real issue is the reported "code smells".

**Comment by mswiderski** [comment]
Ok, will take a look once back from PTO

**Comment by mswiderski** [comment]
@cristianonicolai [code smells eliminated ](https://github.com/kiegroup/kogito-runtimes/pull/149/checks?check_run_id=223031472)

**Pull request merged**
