### PR TITLE
KOGITO-8557 - Review tests missing timeout for await operations

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by kie-ci3** [comment]
**(tests) - serverless-workflow-examples job** `#300` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.serverless-workflow-examples/300/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] echo<br/>[2023-01-30T15:15:13.823Z] [INFO] build-chain version recovered '^v2.6.25'<br/>[Pipeline] sh<br/>[2023-01-30T15:15:14.105Z] + npm install -g '@kie/build-chain-action@^v2.6.25' -registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/<br/>[2023-01-30T15:15:14.361Z] npm ERR! code ETARGET<br/>[2023-01-30T15:15:14.361Z] npm ERR! notarget No matching version found for @kie/build-chain-action@^v2.6.25.<br/>[2023-01-30T15:15:14.361Z] npm ERR! notarget In most cases you or one of your dependencies are requesting<br/>[2023-01-30T15:15:14.361Z] npm ERR! notarget a package version that doesn't exist.<br/>[2023-01-30T15:15:14.361Z] <br/>[2023-01-30T15:15:14.361Z] npm ERR! A complete log of this run can be found in:<br/>[2023-01-30T15:15:14.361Z] npm ERR!     /home/jenkins/.npm/_logs/2023-01-30T15_15_13_785Z-debug.log<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build quarkus)<br/>Stage "Build quarkus" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>Stage "Build projects" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Sonar analysis)<br/>Stage "Sonar analysis" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Upload artifacts to repository)<br/>Stage "Upload artifacts to repository" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space after build)<br/>Stage "check space after build" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2023-01-30T15:15:15.260Z] + wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.serverless-workflow-examples/300/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by kie-ci3** [comment]
**(tests) - kogito-apps job** `#1935` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/1935/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] echo<br/>[2023-01-30T15:15:13.724Z] [INFO] build-chain version recovered '^v2.6.25'<br/>[Pipeline] sh<br/>[2023-01-30T15:15:14.005Z] + npm install -g '@kie/build-chain-action@^v2.6.25' -registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/<br/>[2023-01-30T15:15:14.261Z] npm ERR! code ETARGET<br/>[2023-01-30T15:15:14.261Z] npm ERR! notarget No matching version found for @kie/build-chain-action@^v2.6.25.<br/>[2023-01-30T15:15:14.261Z] npm ERR! notarget In most cases you or one of your dependencies are requesting<br/>[2023-01-30T15:15:14.261Z] npm ERR! notarget a package version that doesn't exist.<br/>[2023-01-30T15:15:14.261Z] <br/>[2023-01-30T15:15:14.261Z] npm ERR! A complete log of this run can be found in:<br/>[2023-01-30T15:15:14.261Z] npm ERR!     /home/jenkins/.npm/_logs/2023-01-30T15_15_14_262Z-debug.log<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build quarkus)<br/>Stage "Build quarkus" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>Stage "Build projects" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Sonar analysis)<br/>Stage "Sonar analysis" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Upload artifacts to repository)<br/>Stage "Upload artifacts to repository" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space after build)<br/>Stage "check space after build" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2023-01-30T15:15:15.208Z] + wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/1935/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by kie-ci3** [comment]
**(tests) - kogito-quarkus-examples job** `#299` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-quarkus-examples/299/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] echo<br/>[2023-01-30T15:15:13.865Z] [INFO] build-chain version recovered '^v2.6.25'<br/>[Pipeline] sh<br/>[2023-01-30T15:15:14.146Z] + npm install -g '@kie/build-chain-action@^v2.6.25' -registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/<br/>[2023-01-30T15:15:14.401Z] npm ERR! code ETARGET<br/>[2023-01-30T15:15:14.401Z] npm ERR! notarget No matching version found for @kie/build-chain-action@^v2.6.25.<br/>[2023-01-30T15:15:14.401Z] npm ERR! notarget In most cases you or one of your dependencies are requesting<br/>[2023-01-30T15:15:14.401Z] npm ERR! notarget a package version that doesn't exist.<br/>[2023-01-30T15:15:14.401Z] <br/>[2023-01-30T15:15:14.401Z] npm ERR! A complete log of this run can be found in:<br/>[2023-01-30T15:15:14.401Z] npm ERR!     /home/jenkins/.npm/_logs/2023-01-30T15_15_13_986Z-debug.log<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build quarkus)<br/>Stage "Build quarkus" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>Stage "Build projects" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Sonar analysis)<br/>Stage "Sonar analysis" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Upload artifacts to repository)<br/>Stage "Upload artifacts to repository" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space after build)<br/>Stage "check space after build" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2023-01-30T15:15:15.340Z] + wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-quarkus-examples/299/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by kie-ci3** [comment]
**(tests) - kogito-springboot-examples job** `#300` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-springboot-examples/300/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] echo<br/>[2023-01-30T15:15:22.680Z] [INFO] build-chain version recovered '^v2.6.25'<br/>[Pipeline] sh<br/>[2023-01-30T15:15:22.962Z] + npm install -g '@kie/build-chain-action@^v2.6.25' -registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/<br/>[2023-01-30T15:15:23.220Z] npm ERR! code ETARGET<br/>[2023-01-30T15:15:23.220Z] npm ERR! notarget No matching version found for @kie/build-chain-action@^v2.6.25.<br/>[2023-01-30T15:15:23.220Z] npm ERR! notarget In most cases you or one of your dependencies are requesting<br/>[2023-01-30T15:15:23.220Z] npm ERR! notarget a package version that doesn't exist.<br/>[2023-01-30T15:15:23.220Z] <br/>[2023-01-30T15:15:23.220Z] npm ERR! A complete log of this run can be found in:<br/>[2023-01-30T15:15:23.220Z] npm ERR!     /home/jenkins/.npm/_logs/2023-01-30T15_15_22_662Z-debug.log<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build quarkus)<br/>Stage "Build quarkus" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>Stage "Build projects" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Sonar analysis)<br/>Stage "Sonar analysis" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Upload artifacts to repository)<br/>Stage "Upload artifacts to repository" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space after build)<br/>Stage "check space after build" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2023-01-30T15:15:24.137Z] + wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-springboot-examples/300/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by kie-ci3** [comment]
**(tests) - kogito-runtimes job** `#1860` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/1860/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] echo<br/>[2023-01-30T15:15:22.839Z] [INFO] build-chain version recovered '^v2.6.25'<br/>[Pipeline] sh<br/>[2023-01-30T15:15:23.122Z] + npm install -g '@kie/build-chain-action@^v2.6.25' -registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/<br/>[2023-01-30T15:15:23.376Z] npm ERR! code ETARGET<br/>[2023-01-30T15:15:23.376Z] npm ERR! notarget No matching version found for @kie/build-chain-action@^v2.6.25.<br/>[2023-01-30T15:15:23.376Z] npm ERR! notarget In most cases you or one of your dependencies are requesting<br/>[2023-01-30T15:15:23.376Z] npm ERR! notarget a package version that doesn't exist.<br/>[2023-01-30T15:15:23.376Z] <br/>[2023-01-30T15:15:23.376Z] npm ERR! A complete log of this run can be found in:<br/>[2023-01-30T15:15:23.376Z] npm ERR!     /home/jenkins/.npm/_logs/2023-01-30T15_15_23_380Z-debug.log<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build quarkus)<br/>Stage "Build quarkus" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>Stage "Build projects" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Sonar analysis)<br/>Stage "Sonar analysis" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Upload artifacts to repository)<br/>Stage "Upload artifacts to repository" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space after build)<br/>Stage "check space after build" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2023-01-30T15:15:24.325Z] + wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/1860/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Review by ricardozanini — APPROVED** [review]

**Comment by ricardozanini** [comment]
jenkins retest this

**Pull request merged**
