### PR TITLE
KOGITO-3260  Bump Extension to Quarkus 1.8.0

### PR DESCRIPTION
**Pull request by evacchi**
https://github.com/kiegroup/kogito-apps/pull/447
https://github.com/kiegroup/kogito-examples/pull/353

### CODE REVIEW

**Comment by evacchi** [comment]
jenkins please retest this

**Comment by evacchi** [comment]
jenkins please retest this

(it's green on my machine)

wheel of fortune

**Comment by evacchi** [comment]
timeout on kogito-apps 

jenkins please retest this

**Comment by evacchi** [comment]
jenkins please retest this

**Comment by evacchi** [comment]
this is consistently failing on kogito-apps in kogito-apps/data-index/data-index-service/data-index-service-infinispan can someone take a look? @tiagodolphine @cristianonicolai or whoever may help :P also it looks like these are in TRACE logging so that may be a reason for timing out...

**Comment by evacchi** [comment]
jenkins please retest this

**Comment by evacchi** [comment]
I can actually reproduce locally:

       [ERROR]   InfinispanReactiveMessagingEventConsumerKafkaIT>AbstractReactiveMessagingEventConsumerKafkaIT.testProcessInstanceEvent:100 » ConditionTimeout

**Comment by evacchi** [comment]
I don't think the issue is the wait btw. @cristianonicolai @tiagodolphine need some assistance here :(

**Comment by evacchi** [comment]
jenkins please retest this

**Review by tiagodolphine — APPROVED** [review]

**Review by cristianonicolai — APPROVED** [review]

**Pull request merged**
