### PR TITLE
[KOGITO-6802] Ensure magic words are replaced

### PR DESCRIPTION
**Pull request by fjtirado**
Most cases were already working. 
I added some test to ensure this is the case
I'm also ensuring function references are replaced when used in function arguments.

### CODE REVIEW

**Review by ricardozanini — APPROVED** [review]

**Comment by kie-ci1** [comment]
**(tests) - kogito-apps job** `#1227` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 2693
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/1227/testReport/org.kie.kogito.index.mongodb/ProcessDataIndexMongoDBIT/testProcessInstanceEvents/">org.kie.kogito.index.mongodb.ProcessDataIndexMongoDBIT.testProcessInstanceEvents</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>JSON path data.UserTaskInstances[0].attachments[0].name doesn't match.<br/>Expected: newAttachmentContent<br/>  Actual: NewTaskAttachmentName<br/><br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/1227/testReport/org.kie.kogito.index.service/OracleIndexingServiceIT/testProcessInstanceIndex/">org.kie.kogito.index.service.OracleIndexingServiceIT.testProcessInstanceIndex</a></summary>
org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a lambda expression in org.kie.kogito.index.service.AbstractIndexingServiceIT null within 30 seconds.<br/>Caused by: java.util.concurrent.TimeoutException<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/1227/display/redirect

**Comment by kie-ci1** [comment]
**(tests) - kogito-apps job** `#1226` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 2694
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/1226/testReport/org.kie.kogito.index.messaging/OracleMessagingConsumerKafkaIT/testProcessInstanceEvent/">org.kie.kogito.index.messaging.OracleMessagingConsumerKafkaIT.testProcessInstanceEvent</a></summary>
org.awaitility.core.ConditionTimeoutException: <br/>Assertion condition defined as a lambda expression in org.kie.kogito.index.messaging.AbstractMessagingConsumerKafkaIT that uses java.lang.String 1 expectation failed.<br/>JSON path data.ProcessInstances.size() doesn't match.<br/>Expected: is <1><br/>  Actual: <0><br/> within 30 seconds.<br/>Caused by: java.lang.AssertionError: <br/>1 expectation failed.<br/>JSON path data.ProcessInstances.size() doesn't match.<br/>Expected: is <1><br/>  Actual: <0><br/><br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/1226/display/redirect

**Comment by kie-ci1** [comment]
**(tests) - kogito-runtimes job** `#1203` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 2530
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/1203/testReport/org.kie.kogito.mongodb.transaction/MongoDBTransactionManagerIT/testAbort/">org.kie.kogito.mongodb.transaction.MongoDBTransactionManagerIT.testAbort</a></summary>
com.mongodb.MongoCommandException: Command failed with error 246 (SnapshotUnavailable): 'Unable to read from a snapshot due to pending collection catalog changes; please retry the operation. Snapshot timestamp is Timestamp(1646389442, 2). Collection minimum is Timestamp(1646389442, 4)' on server localhost:49156. The full response is {"errorLabels": ["TransientTransactionError"], "operationTime": {"$timestamp": {"t": 1646389442, "i": 2}}, "ok": 0.0, "errmsg": "Unable to read from a snapshot due to pending collection catalog changes; please retry the operation. Snapshot timestamp is Timestamp(1646389442, 2). Collection minimum is Timestamp(1646389442, 4)", "code": 246, "codeName": "SnapshotUnavailable", "$clusterTime": {"clusterTime": {"$timestamp": {"t": 1646389443, "i": 1}}, "signature": {"hash": {"$binary": {"base64": "AAAAAAAAAAAAAAAAAAAAAAAAAAA=", "subType": "00"}}, "keyId": 0}}}<br/>	at org.kie.kogito.mongodb.transaction.MongoDBTransactionManagerIT.testAbort(MongoDBTransactionManagerIT.java:238)<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/1203/display/redirect

**Comment by fjtirado** [comment]
jenkins rerun kogito-runtimes tests

**Comment by kie-ci1** [comment]
**(tests) - kogito-runtimes job** `#1205` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 2530
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/1205/testReport/org.kie.kogito.mongodb.transaction/MongoDBTransactionManagerIT/testAbort/">org.kie.kogito.mongodb.transaction.MongoDBTransactionManagerIT.testAbort</a></summary>
com.mongodb.MongoCommandException: Command failed with error 246 (SnapshotUnavailable): 'Unable to read from a snapshot due to pending collection catalog changes; please retry the operation. Snapshot timestamp is Timestamp(1646393368, 0). Collection minimum is Timestamp(1646393368, 2)' on server localhost:49336. The full response is {"errorLabels": ["TransientTransactionError"], "operationTime": {"$timestamp": {"t": 1646393367, "i": 4}}, "ok": 0.0, "errmsg": "Unable to read from a snapshot due to pending collection catalog changes; please retry the operation. Snapshot timestamp is Timestamp(1646393368, 0). Collection minimum is Timestamp(1646393368, 2)", "code": 246, "codeName": "SnapshotUnavailable", "$clusterTime": {"clusterTime": {"$timestamp": {"t": 1646393368, "i": 3}}, "signature": {"hash": {"$binary": {"base64": "AAAAAAAAAAAAAAAAAAAAAAAAAAA=", "subType": "00"}}, "keyId": 0}}}<br/>	at org.kie.kogito.mongodb.transaction.MongoDBTransactionManagerIT.testAbort(MongoDBTransactionManagerIT.java:238)<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/1205/display/redirect

**Comment by ricardozanini** [comment]
Again, it looks like we have flaky tests in the runtimes.

**Comment by fjtirado** [comment]
> ain, it looks like we have flaky tests in the runtimes.

Yes, but this ne ins new. Yesterday it was not there. The only thing that was changed is the quarkus version, to 7.2.3, I guess this is the culprit

**Pull request merged**
