### PR TITLE
KOGITO-3596 Bump to Quarkus 1.9

### PR DESCRIPTION
**Pull request by evacchi**
let's run CI and see if something breaks.

Notice, I don't think we should merge for 0.17.0. Let's merge for 1.0.

related: https://github.com/kiegroup/kogito-examples/pull/396

----

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.md)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by evacchi** [comment]
jenkins please retest this

**Review by radtriste — APPROVED** [review]

**Comment by cristianonicolai** [comment]
@evacchi can we wait until 1.0 to have this alignment?

should we consider doing a minor update to 1.8.3 for 0.17 then?

**Comment by evacchi** [comment]
jenkins please retest this

**Comment by evacchi** [comment]
@cristianonicolai I would personally avoid merging before the start of the next sprint, unless it is vital for quarkus that we upgrade 1.9 platform

**Comment by evacchi** [comment]
jenkins please retest this

**Comment by evacchi** [comment]
jenkins please retest this

**Comment by evacchi** [comment]
@cristianonicolai there are failures on kogito-apps, can you take a look?

**Comment by tiagodolphine** [comment]
> @cristianonicolai @tiagodolphine there are failures on kogito-apps, can you take a look?

@evacchi I tried to reproduce the errors locally but the build was success... strange... it seems to be something on the CI

**Comment by evacchi** [comment]
yeah same here.. at least the patch I did is working... no clue

**Comment by evacchi** [comment]
jenkins please retest this

**Comment by evacchi** [comment]
jenkins please retest this

this is green on https://github.com/kiegroup/kogito-runtimes/pull/826

**Comment by evacchi** [comment]
something funky going on with mirrors? 

```
[INFO] Running org.kie.kogito.it.jobs.ProcessTimerIT
Downloading from mirror-central: https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/org/kie/kogito/integration-tests-common//integration-tests-common-.pom
Downloading from mirror-central: https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/org/kie/kogito/integration-tests-common//integration-tests-common-.jar
[ERROR] Tests run: 6, Failures: 0, Errors: 1, Skipped: 5, Time elapsed: 9.944 s <<< FAILURE! - in org.kie.kogito.it.jobs.ProcessTimerIT
[ERROR] testDeleteTimerCycle  Time elapsed: 0.012 s  <<< ERROR!
java.lang.RuntimeException: io.quarkus.bootstrap.BootstrapException: Failed to create the application model for null
Caused by: io.quarkus.bootstrap.BootstrapException: Failed to create the application model for null
Caused by: io.quarkus.bootstrap.resolver.maven.BootstrapMavenException: Failed to resolve dependencies for org.kie.kogito:integration-tests-quarkus:jar:1.0.0-SNAPSHOT
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact org.kie.kogito:integration-tests-common:jar: in mirror-central (https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/)
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.kie.kogito:integration-tests-common:jar: in mirror-central (https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/)
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.kie.kogito:integration-tests-common:jar: in mirror-central (https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/)
```

**Comment by evacchi** [comment]
jenkins please retest this

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
weird, its throwing `FileSystemNotFoundException`

**Comment by radtriste** [comment]
Jenkins and Openstack had some problems yesterday. Error might come from there.

**Comment by evacchi** [comment]
> weird, its throwing FileSystemNotFoundException

again? I thought I had fixed that (on kogito-apps)

**Comment by evacchi** [comment]
I think I fixed the issue on kogito-apps, so let's try again the build here

jenkins please retest this

**Comment by evacchi** [comment]
I have added a few version bumps. There is protobuf at 3.13.0 but I am not sure that is a backwards compatible change (IIRC they don't use semver and minor version bumps are actually major changes)

**Comment by tiagodolphine** [comment]
jenkins retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Review by radtriste — APPROVED** [review]

**Review by cristianonicolai — APPROVED** [review]

**Comment by tiagodolphine** [comment]
jenkins retest this

**Comment by evacchi** [comment]
i don't know why i had to explicitly add the version number in the last commit...

**Comment by cristianonicolai** [comment]
@evacchi see https://github.com/kiegroup/kogito-runtimes/pull/845, I think that might have fixed already.

**Comment by evacchi** [comment]
@cristianonicolai it didn't: the nested Maven run was complaining about the missing version (don't ask me why) /cc @danielezonca

**Comment by evacchi** [comment]
@cristianonicolai I thought that was already merged, but probably it wasn't (?)

**Comment by evacchi** [comment]
jenkins please retest this

**Comment by evacchi** [comment]
jenkins please retest this

**Comment by tiagodolphine** [comment]
It seems the last build failed in kogito-examples, `Serverless Workflow Github Showcase :: GitHub Service FAILURE [  0.704 s]`, but I don't think it is related to the PR.

**Comment by evacchi** [comment]
jenkins please retest this

**Comment by evacchi** [comment]
@tiagodolphine Quarkus 1.9 no longer ships with Google libraries, so this https://github.com/kiegroup/kogito-examples/pull/422 fixed that issue

**Pull request merged**
