### PR TITLE
KOGITO-5921 add oracle quarkus/sb test resource

### PR DESCRIPTION
**Pull request by Scuilion**
Required for testing new example in https://github.com/kiegroup/kogito-examples
https://issues.redhat.com/browse/KOGITO-5921

### CODE REVIEW

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Review by cristianonicolai — APPROVED** [review]

**Comment by cristianonicolai** [comment]
Jenkins rerun optaplanner tests

**Comment by cristianonicolai** [comment]
Jenkins rerun optaweb-vehicle-routing tests

**Review by danielezonca — APPROVED** [review]

**Comment by cristianonicolai** [comment]
@Scuilion thank you for the contribution!

**Pull request merged**
