### PR TITLE
KOGITO-4452 Setup LTS PR check

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/KOGITO-4452

In order to test against LTS version of Quarkus.

Command will be `Jenkins run LTS[ tests]`

Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/119
- https://github.com/kiegroup/kogito-runtimes/pull/1072
- https://github.com/kiegroup/optaplanner/pull/1201
- https://github.com/kiegroup/kogito-apps/pull/655
- https://github.com/kiegroup/kogito-examples/pull/606

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.md)
- [x] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/droolsjbpm-build-bootstrap/tree/master/ide-configuration)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by radtriste** [comment]
Jenkins run LTS tests

**Comment by radtriste** [comment]
Jenkins run LTS tests

**Comment by radtriste** [comment]
Jenkins run LTS tests

**Comment by radtriste** [comment]
Jenkins retest this

**Comment by radtriste** [comment]
Jenkins run LTS tests

**Comment by radtriste** [comment]
Jenkins run LTS tests

**Comment by radtriste** [comment]
Jenkins run LTS tests

**Comment by radtriste** [comment]
Jenkins run LTS tests

**Comment by radtriste** [comment]
Jenkins run LTS tests

**Review by evacchi — APPROVED** [review]

**Pull request merged**
