### PR TITLE
[KOGITO-5356] Moving addons to respective runtimes modules

### PR DESCRIPTION
**Pull request by ricardozanini**
Signed-off-by: Ricardo Zanini <zanini@redhat.com>

See: https://issues.redhat.com/browse/KOGITO-5356

In this PR we move the modules `addons/quarkus` and `addons/springboot` to their respective parent runtime module, having now:

```
- springboot
-- addons
-- kogito-springboot-starter (will change on KOGITO-5301)
- quarkus
-- addons
-- bom
-- extensions
``` 
Artifact ids for published libraries haven't changed. This PR is **exclusively** used to make this movement around the modules. No code changes, no documentation, no ids changed. See follow up PRs:

- https://issues.redhat.com/browse/KOGITO-5355 - To create a BOM module for `springboot` to be used internally on addons and starters. We already have `quarkus/bom` that we can evolve
- https://issues.redhat.com/browse/KOGITO-5301 - To create the `springboot/starters` module, introducing the new starters with the preconfigured addons.
- https://issues.redhat.com/browse/KOGITO-5300 - To document the existing addons

If you have any request, please add to the respective comment session or we can discuss opening a new JIRA for the upcoming sprint.

I kept the `addons/common` module because we have `addons/deprecated`. After releasing 7.12, we will probably get rid of the `deprecated` module, thus removing both submodules and keeping the addons in the root.

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.md)
- [x] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/master/kogito-build/kogito-ide-config)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Run all builds</b>  
  Please add comment: <b>Jenkins retest this</b>

* <b>Run (or rerun) specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [runtimes|optaplanner|apps|examples] tests</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Run (or rerun) LTS specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [runtimes|optaplanner|apps|examples] LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

* <b>Run (or rerun) native specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [runtimes|optaplanner|apps|examples] native</b>

* <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

### CODE REVIEW

**Comment by ricardozanini** [comment]
@danielezonca, I believe I'll have to change the Quarkus Platform CI as well because of this change. Can you help with this?

**Review by cristianonicolai — APPROVED** [review]

**Review by danielezonca — APPROVED** [review]
Overall looks good to me, I don't like too much that now the code of an add-on is in splitter in different hierarchy but I don't have a better proposal. Just a comment: can you please update the [README](https://github.com/kiegroup/kogito-runtimes/tree/a17f2321de08c60cef085b6511bea8fff6776a61/addons) to link the moved folders? Proper documentation will be provided in a future ticket but at least the readme is coherent

**Comment by danielezonca** [comment]
> @danielezonca, I believe I'll have to change the Quarkus Platform CI as well because of this change. Can you help with this?

Why do you think this will impact Quarkus platform CI?
As far as I know we have two jobs with Quarkus:
- daily job that executes [this job](https://github.com/kiegroup/kogito-runtimes/blob/master/.github/workflows/quarkus-snapshot.yaml)
- [platform](https://github.com/quarkusio/quarkus-platform/blob/main/pom.xml#L213) ci that only execute quarkus integration tests

As far as I can see none of these changes should impact those 🤔

**Comment by ricardozanini** [comment]
> Why do you think this will impact Quarkus platform CI?

hmmm I saw that we have a module to run the platform tests. I've changed its parent, so I figured the platform CI would fetch it somehow. Yeah, based on this information you shared, I think we are fine. :)

Just let me know if we are fine to merge. It will unlock a series of issues that I'm holding right now. Thanks my friend!

**Comment by ricardozanini** [comment]
> Overall looks good to me, I don't like too much that now the code of an add-on is in splitter in different hierarchy but I don't have a better proposal. Just a comment: can you please update the [README](https://github.com/kiegroup/kogito-runtimes/tree/a17f2321de08c60cef085b6511bea8fff6776a61/addons) to link the moved folders? Proper documentation will be provided in a future ticket but at least the readme is coherent

Ouch! I forgot to change the README. Of course.

**Comment by ricardozanini** [comment]
I think we need to change GHA and Jenkins to not run if we just update the certain docs files :sweat:

**Comment by ricardozanini** [comment]
Jenkins rerun runtimes tests

**Comment by ricardozanini** [comment]
Jenkins rerun apps tests

**Comment by ricardozanini** [comment]
@danielezonca want to take a look in the latest docs updates?

**Comment by MarianMacik** [comment]
@ricardozanini Hi, I was away and didn't have a chance to ask before merge, so I will now. What is the point of having shared addon modules under addons ans runtime-specific addons under runtime-specific modules? It looks quite mixed to me.

**Pull request merged**
