### PR TITLE
KOGITO-7238 - Ensure instances are disconnected in case of optimistic…

### PR DESCRIPTION
**Pull request by cristianonicolai**
… lock exception

### CODE REVIEW

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Review by ricardozanini — APPROVED** [review]

**Review by tiagodolphine — APPROVED** [review]

**Review by ricardozanini — APPROVED** [review]

**Review by radtriste — APPROVED** [review]

**Comment by radtriste** [comment]
jenkins retest this

**Comment by kie-ci3** [comment]
**(tests) - kogito-runtimes job** `#286` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/286/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-06-08T13:18:52.503Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/optaplanner.tests.downstream.optaweb-vehicle-routing_ws-cleanup_1654694327903/bc/kiegroup_optaweb_vehicle_routing/optaweb-vehicle-routing/optaweb-vehicle-routing-frontend/node_modules/@patternfly/react-tokens/dist/js/c_divider_after_Height.d.ts’: No such file or directory<br/>[2022-06-08T13:18:52.503Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/optaplanner.tests.downstream.optaweb-vehicle-routing_ws-cleanup_1654694327903/bc/kiegroup_optaweb_vehicle_routing/optaweb-vehicle-routing/optaweb-vehicle-routing-frontend/node_modules/@patternfly/react-tokens/dist/js/c_divider_after_Inset.d.ts’: No such file or directory<br/>[2022-06-08T13:18:52.503Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/optaplanner.tests.downstream.optaweb-vehicle-routing_ws-cleanup_1654694327903/bc/kiegroup_optaweb_vehicle_routing/optaweb-vehicle-routing/optaweb-vehicle-routing-frontend/node_modules/@patternfly/react-tokens/dist/js/c_divider_BackgroundColor.d.ts’: No such file or directory<br/>[2022-06-08T13:18:52.503Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/optaplanner.tests.downstream.optaweb-vehicle-routing_ws-cleanup_1654694327903/bc/kiegroup_optaweb_vehicle_routing/optaweb-vehicle-routing/optaweb-vehicle-routing-frontend/node_modules/@patternfly/react-tokens/dist/js/c_divider_Height.d.ts’: No such file or directory<br/>[2022-06-08T13:18:52.503Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/optaplanner.tests.downstream.optaweb-vehicle-routing_ws-cleanup_1654694327903/bc/kiegroup_optaweb_vehicle_routing/optaweb-vehicle-routing/optaweb-vehicle-routing-frontend/node_modules/@patternfly/react-tokens/dist/js/c_divider_m_vertical_after_FlexBasis.d.ts’: No such file or directory<br/>[2022-06-08T13:18:52.503Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/optaplanner.tests.downstream.optaweb-vehicle-routing_ws-cleanup_1654694327903/bc/kiegroup_optaweb_vehicle_routing/optaweb-vehicle-routing/optaweb-vehicle-routing-frontend/node_modules/@patternfly/react-tokens/dist/js/c_divider_m_vertical_after_Width.d.ts’: No such file or directory<br/>[2022-06-08T13:18:52.503Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/optaplanner.tests.downstream.optaweb-vehicle-routing_ws-cleanup_1654694327903/bc/kiegroup_optaweb_vehicle_routing/optaweb-vehicle-routing/optaweb-vehicle-routing-frontend/node_modules/@patternfly/react-tokens/dist/js/c_drawer__actions_MarginRight.d.ts’: No such file or directory<br/>[2022-06-08T13:18:52.503Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/optaplanner.tests.downstream.optaweb-vehicle-routing_ws-cleanup_1654694327903/bc/kiegroup_optaweb_vehicle_routing/optaweb-vehicle-routing/optaweb-vehicle-routing-frontend/node_modules/@patternfly/react-tokens/dist/js/c_drawer__actions_MarginTop.d.ts’: No such file or directory<br/>[2022-06-08T13:18:52.503Z] 633M	/home/jenkins/workspace<br/>[2022-06-08T13:18:52.503Z] 0	/home/jenkins/.pki<br/>[2022-06-08T13:18:52.503Z] 117M	/home/jenkins/tools<br/>[2022-06-08T13:18:52.503Z] 0	/home/jenkins/caches<br/>[2022-06-08T13:18:52.503Z] 129M	/home/jenkins/.npm<br/>[2022-06-08T13:18:52.503Z] 3.1G	/home/jenkins<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Install build-chain tool)<br/>Stage "Install build-chain tool" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>Stage "Build projects" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Sonar analysis)<br/>Stage "Sonar analysis" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space after build)<br/>Stage "check space after build" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-06-08T13:18:53.568Z] + wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/286/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by cristianonicolai** [comment]
Jenkins rerun kogito-runtimes tests

**Pull request merged**
