### PR TITLE
KOGITO-4767 - Upgrade GraalVM to version 20.3.1.2

### PR DESCRIPTION
**Pull request by cristianonicolai**
Assembly:
- https://github.com/kiegroup/kie-jenkins-scripts/pull/947
- https://github.com/kiegroup/kogito-runtimes/pull/1172

### CODE REVIEW

**Review by evacchi — APPROVED** [review]

**Comment by evacchi** [comment]
let's not forget to start the native build before merging

**Review by ricardozanini — APPROVED** [review]

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by ricardozanini** [comment]
Jenkins run native

**Comment by ricardozanini** [comment]
> The Native check has **failed**. Please check [the logs](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/kogito/job/pullrequest/job/kogito-runtimes.native/24/console).

@cristianonicolai @r00ta @danielezonca same error on Trusty apps

**Comment by cristianonicolai** [comment]
Jenkins run native

**Comment by r00ta** [comment]
> > The Native check has **failed**. Please check [the logs](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/kogito/job/pullrequest/job/kogito-runtimes.native/24/console).
> 
> @cristianonicolai @r00ta @danielezonca same error on Trusty apps

Checking... are we hitting https://github.com/quarkusio/quarkus/issues/12447 ?

**Comment by ricardozanini** [comment]
@r00ta nice catch! I think it's possible, yes.

**Comment by r00ta** [comment]
> @r00ta nice catch! I think it's possible, yes.

But it's really strange... here https://github.com/kiegroup/kogito-apps/pull/732 I've implemented a workaround for that URL but nothing for the TrustyUI (I expected it to fail), but actually the build is green :/

**Comment by r00ta** [comment]
Jenkins run native

Let's see..

**Comment by cristianonicolai** [comment]
GraalVM Version 20.1.0, I guess it hasnt pick up yet the change from https://github.com/kiegroup/kie-jenkins-scripts/pull/947

**Comment by cristianonicolai** [comment]
Jenkins run native

**Comment by cristianonicolai** [comment]
I was missing a rebase to get the latest changes from the Jenkinsfile.

**Comment by cristianonicolai** [comment]
Jenkins run native

**Comment by MarianMacik** [comment]
Native build fixed as part of kiegroup/kogito-examples#632.

**Comment by cristianonicolai** [comment]
Jenkins run native

**Comment by cristianonicolai** [comment]
Jenkins run native

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
Jenkins run native

**Comment by ricardozanini** [comment]
DRL/DMN related errors, not sure if it's related to this change. @evacchi ?

**Comment by cristianonicolai** [comment]
Jenkins run native

**Comment by cristianonicolai** [comment]
Jenkins run native

**Comment by cristianonicolai** [comment]
Jenkins run native

**Comment by cristianonicolai** [comment]
Jenkins run native

**Comment by cristianonicolai** [comment]
Jenkins run native

**Comment by cristianonicolai** [comment]
Jenkins run native

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Pull request merged**
