### PR TITLE
KOGITO-3506 Set Maven mirror to local repository

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Review by radtriste — APPROVED** [review]

**Review by Sgitario — APPROVED** [review]

**Review by ricardozanini — APPROVED** [review]
+1000

**Comment by ricardozanini** [comment]
Should we merge or wait for the CI to be green? :)

**Review by MarianMacik — APPROVED** [review]

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by ricardozanini** [comment]
@cristianonicolai I think we are good?

**Pull request merged**
