### PR TITLE
KOGITO-1057 - Use listener instead of config bean and add IT tests fo…

### PR DESCRIPTION
**Pull request by cristianonicolai**
…r process monitoring

### CODE REVIEW

**Comment by cristianonicolai** [comment]
Jenkins rerun apps tests

**Comment by cristianonicolai** [comment]
Jenkins rerun examples tests

**Review by ricardozanini — APPROVED** [review]

**Comment by ricardozanini** [comment]
Do we need to update the monitoring examples?

**Comment by ricardozanini** [comment]
Jenkins rerun apps tests

**Comment by cristianonicolai** [comment]
> Do we need to update the monitoring examples?

not really, this is just an internal change

**Pull request merged**
