### PR TITLE
BXMSPROD-1603 Composite actions centralized github actions

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/BXMSPROD-1603

Depends on https://github.com/kiegroup/kogito-pipelines/pull/345

Modified version to avoid build errors. See also https://github.com/kiegroup/kogito-runtimes/pull/1729

### CODE REVIEW

**Comment by radtriste** [comment]
Testing runtimes with changes from https://github.com/kiegroup/kogito-pipelines/pull/345

**Comment by radtriste** [comment]
@Ginxo all checks passed with https://github.com/kiegroup/kogito-pipelines/pull/345. Do you mind checking and approve/merge if ok ?

**Comment by Ginxo** [comment]
@radtriste is this ready for review?

**Comment by radtriste** [comment]
@Ginxo it is now :)

**Review by Ginxo — APPROVED** [review]
LGTM, thanks a lot @radtriste

**Pull request merged**
