### PR TITLE
KOGITO-6457 Skip validating OpenAPI spec file

### PR DESCRIPTION
**Pull request by cristianonicolai**
Codegen will continue and print an warn about invalid attributes.

### CODE REVIEW

**Review by ricardozanini — APPROVED** [review]

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
Jenkins rerun kogito-apps tests

**Comment by cristianonicolai** [comment]
Jenkins rerun kogito-runtimes tests

**Comment by cristianonicolai** [comment]
Jenkins rerun kogito-runtimes tests

**Comment by cristianonicolai** [comment]
Jenkins rerun kogito-runtimes tests

**Pull request merged**
