### PR TITLE
KOGITO-6493 Upgrade mvnw version

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by cristianonicolai** [comment]
Jenkins rerun kogito-apps tests

**Comment by cristianonicolai** [comment]
Jenkins rerun kogito-examples tests

**Review by ricardozanini — APPROVED** [review]

**Comment by ricardozanini** [comment]
Jenkins rerun kogito-apps tests

**Comment by ricardozanini** [comment]
Jenkins rerun kogito-apps tests

**Comment by cristianonicolai** [comment]
Jenkins rerun kogito-apps tests

**Comment by cristianonicolai** [comment]
Jenkins rerun kogito-apps tests

**Comment by cristianonicolai** [comment]
Jenkins rerun kogito-apps tests

**Pull request merged**
