### PR TITLE
KOGITO-4223 Kogito SB archetype fail Swagger/OAS ootb

### PR DESCRIPTION
**Pull request by tarilabs**
Ref: https://issues.redhat.com/browse/KOGITO-4223?focusedCommentId=15676972&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-15676972

A PR to align all ~30 examples is in the works.

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.md)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by tarilabs** [comment]
### BEFORE

Broken, see JIRA.

### AFTER

using and launching archetype out of the box:

Screenshot 2021-01-22 at 11 16 34

Screenshot 2021-01-22 at 11 17 39

**Review by danielezonca — APPROVED** [review]
Well done :+1:

**Review by cristianonicolai — APPROVED** [review]
thanks @tarilabs !

**Comment by tarilabs** [comment]
Jenkins retest this

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by tarilabs** [comment]
Jenkins retest this

**Comment by tarilabs** [comment]
```
Existing failures - 1
testKogitoContainerIsDeployedAndResponsive – org.kie.kogito.examples.GrafanaDockerComposeIT
1s
Error
localhost:8080 failed to respond
Stacktrace
org.apache.http.NoHttpResponseException: localhost:8080 failed to respond
at org.kie.kogito.examples.GrafanaDockerComposeIT.testKogitoContainerIsDeployedAndResponsive(GrafanaDockerComposeIT.java:95)
```

🤷‍♂️ 🎱 

Jenkins retest this

**Comment by tarilabs** [comment]
image

Jenkins retest this

**Pull request merged**
