### PR TITLE
KOGITO-7402 - Split UnitOfWork from ProcessEventListeners

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by kie-ci3** [comment]
**(tests) - kogito-runtimes job** `#331` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/331/display/redirect

**Test results:**
- PASSED: 2747
- FAILED: 4

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/331/testReport/org.kie.kogito.codegen.tests/BusinessRuleTaskIT/testBasicBusinessRuleTaskControlledByUnitOfWork/">org.kie.kogito.codegen.tests.BusinessRuleTaskIT.testBasicBusinessRuleTaskControlledByUnitOfWork</a></summary>
java.lang.AssertionError: <br/><br/>Expected size: 0 but was: 1 in:<br/>["c891f536-e23a-41f4-bdf8-6e2423b226ef"]<br/>	at org.kie.kogito.codegen.tests.BusinessRuleTaskIT.testBasicBusinessRuleTaskControlledByUnitOfWork(BusinessRuleTaskIT.java:136)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/331/testReport/org.kie.kogito.codegen.tests/BusinessRuleUnitIT/testBasicBusinessRuleUnitControlledByUnitOfWork(String)[1]/">org.kie.kogito.codegen.tests.BusinessRuleUnitIT.testBasicBusinessRuleUnitControlledByUnitOfWork(String)[1]</a></summary>
java.lang.AssertionError: <br/><br/>Expected size: 0 but was: 1 in:<br/>["e5fd8708-503d-4ed7-8304-1dc70a4d5ac9"]<br/>	at org.kie.kogito.codegen.tests.BusinessRuleUnitIT.testBasicBusinessRuleUnitControlledByUnitOfWork(BusinessRuleUnitIT.java:155)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/331/testReport/org.kie.kogito.codegen.tests/BusinessRuleUnitIT/testBasicBusinessRuleUnitControlledByUnitOfWork(String)[2]/">org.kie.kogito.codegen.tests.BusinessRuleUnitIT.testBasicBusinessRuleUnitControlledByUnitOfWork(String)[2]</a></summary>
java.lang.AssertionError: <br/><br/>Expected size: 0 but was: 1 in:<br/>["26d51045-56bb-4b39-bc19-76c47532e2a3"]<br/>	at org.kie.kogito.codegen.tests.BusinessRuleUnitIT.testBasicBusinessRuleUnitControlledByUnitOfWork(BusinessRuleUnitIT.java:155)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/331/testReport/org.kie.kogito.codegen.tests/PublishEventIT/testBusinessRuleProcessStartToEndWithVariableTracked/">org.kie.kogito.codegen.tests.PublishEventIT.testBusinessRuleProcessStartToEndWithVariableTracked</a></summary>
java.lang.AssertionError: <br/><br/>Expected size: 3 but was: 2 in:<br/>[AbstractProcessDataEvent [kogitoParentProcessinstanceId=null, kogitoProcessinstanceState=2, kogitoReferenceId=null, kogitoBusinessKey=null, kogitoStartFromNode=null, getSource()=http://myhost/BusinessRuleTask, getSpecVersion()=1.0, getId()=c2805047-1b19-4576-8811-11f60da6231c, getType()=ProcessInstanceEvent, getTime()=2022-06-17T21:40:36.174547-04:00, getData()=ProcessInstanceEventBody [id=a5c9553d-d75a-420f-9ad2-c04d3793b083, parentInstanceId=null, rootInstanceId=null, processId=BusinessRuleTask, rootProcessId=null, processName=Default Process, startDate=Fri Jun 17 21:40:36 EDT 2022, endDate=Fri Jun 17 21:40:36 EDT 2022, state=2], getKogitoProcessinstanceId()=a5c9553d-d75a-420f-9ad2-c04d3793b083, getKogitoRootProcessinstanceId()=null, getKogitoProcessId()=BusinessRuleTask, getKogitoRootProcessId()=null, getKogitoAddons()=test],<br/>    org.kie.kogito.event.process.VariableInstanceDataEvent@4d95f6a2]<br/>	at org.kie.kogito.codegen.tests.PublishEventIT.testBusinessRuleProcessStartToEndWithVariableTracked(PublishEventIT.java:592)<br/>
</details>

**Comment by kie-ci3** [comment]
**(tests) - kogito-runtimes job** `#333` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/333/display/redirect

**Test results:**
- PASSED: 2740
- FAILED: 3

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/333/testReport/org.kie.kogito.codegen.rules/BusinessRuleUnitIT/testBasicBusinessRuleUnitControlledByUnitOfWork(String)[1]/">org.kie.kogito.codegen.rules.BusinessRuleUnitIT.testBasicBusinessRuleUnitControlledByUnitOfWork(String)[1]</a></summary>
java.lang.AssertionError: <br/><br/>Expected size: 0 but was: 1 in:<br/>["6ae66a17-c6be-4322-a66a-088a94775b06"]<br/>	at org.kie.kogito.codegen.rules.BusinessRuleUnitIT.testBasicBusinessRuleUnitControlledByUnitOfWork(BusinessRuleUnitIT.java:155)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/333/testReport/org.kie.kogito.codegen.rules/BusinessRuleUnitIT/testBasicBusinessRuleUnitControlledByUnitOfWork(String)[2]/">org.kie.kogito.codegen.rules.BusinessRuleUnitIT.testBasicBusinessRuleUnitControlledByUnitOfWork(String)[2]</a></summary>
java.lang.AssertionError: <br/><br/>Expected size: 0 but was: 1 in:<br/>["f873f128-25b7-4501-be36-a9697036b44b"]<br/>	at org.kie.kogito.codegen.rules.BusinessRuleUnitIT.testBasicBusinessRuleUnitControlledByUnitOfWork(BusinessRuleUnitIT.java:155)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/333/testReport/org.kie.kogito.codegen.rules/PublishEventBusinessRuleIT/testBusinessRuleProcessStartToEndWithVariableTracked/">org.kie.kogito.codegen.rules.PublishEventBusinessRuleIT.testBusinessRuleProcessStartToEndWithVariableTracked</a></summary>
java.lang.AssertionError: <br/><br/>Expected size: 3 but was: 2 in:<br/>[AbstractProcessDataEvent [kogitoParentProcessinstanceId=null, kogitoProcessinstanceState=2, kogitoReferenceId=null, kogitoBusinessKey=null, kogitoStartFromNode=null, getSource()=http://myhost/BusinessRuleTask, getSpecVersion()=1.0, getId()=85ec854e-aa88-4e63-bd2b-dd20ffab7155, getType()=ProcessInstanceEvent, getTime()=2022-06-17T23:30:01.202899-04:00, getData()=ProcessInstanceEventBody [id=e5093ea4-852b-4427-8d3d-165d041d7975, parentInstanceId=null, rootInstanceId=null, processId=BusinessRuleTask, rootProcessId=null, processName=Default Process, startDate=Fri Jun 17 23:30:01 EDT 2022, endDate=Fri Jun 17 23:30:01 EDT 2022, state=2], getKogitoProcessinstanceId()=e5093ea4-852b-4427-8d3d-165d041d7975, getKogitoRootProcessinstanceId()=null, getKogitoProcessId()=BusinessRuleTask, getKogitoRootProcessId()=null, getKogitoAddons()=test],<br/>    org.kie.kogito.event.process.VariableInstanceDataEvent@2b2c98c8]<br/>	at org.kie.kogito.codegen.rules.PublishEventBusinessRuleIT.testBusinessRuleProcessStartToEndWithVariableTracked(PublishEventBusinessRuleIT.java:153)<br/>
</details>

**Review by ricardozanini — APPROVED** [review]

**Review by krisv — APPROVED** [review]
@cristianonicolai so this switches not just the dev mode logger to be immediate, but I guess any custom listener (through @ApplicationScoped DefaultProcessEventListenerConfig) will now be triggered immediately as well.  We should at least release note this.
Wondering if there's a need for the delayed listener notification still as well?  Or are we looking at EventEmitter for use cases that require this?

**Comment by cristianonicolai** [comment]
@krisv correct, we're back to v7 situation, processeventlistener will for immediate action and emitter for delayed/batch action. We can also consider that we now have UnitOfWorkListener that allows to interact with that lifecycle internally if needed, an in-between use case. 
+1 to document the change.

**Pull request merged**
