### PR TITLE
[1.5.x] KOGITO-5141 Upgrade Quarkus to 1.11.6.Final

### PR DESCRIPTION
**Pull request by jstastny-cz**
Upgrading to use latest micro release of Quarkus.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

* <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

### CODE REVIEW

**Review by mareknovotny — APPROVED** [review]
thanks for upgrade PR

**Comment by jstastny-cz** [comment]
Failure in DevMojoIT
```
org.awaitility.core.ConditionTimeoutException: Condition with lambda expression in io.quarkus.it.kogito.devmode.DevMojoIT was not fulfilled within 1 minutes.
        at io.quarkus.it.kogito.devmode.DevMojoIT.testDRLHotReload(DevMojoIT.java:276)
Caused by: java.util.concurrent.TimeoutException
        at io.quarkus.it.kogito.devmode.DevMojoIT.testDRLHotReload(DevMojoIT.java:276)
```

jenkins retest this

**Comment by jstastny-cz** [comment]
The failure is different now, timeouts in `Kogito :: Cloud :: Work Items` and `Kogito :: Integration Tests :: SpringBoot` tests.
jenkins retest this

**Comment by mareknovotny** [comment]
I think those tests are randomly failing not only here :(

**Comment by jstastny-cz** [comment]
Only `Kogito :: Cloud :: Work Items` this time.

jenkins retest this

**Comment by jstastny-cz** [comment]
and now `Kogito :: Integration Tests :: SpringBoot`

jenkins retest this

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by jstastny-cz** [comment]
`Kogito :: Cloud :: Work Items` failed this time.

jenkins retest this

**Comment by mareknovotny** [comment]
@danielezonca or @cristianonicolai can you guys look at the failures and asses if that is really a failure caused by CI environment and timeouts? We need to merge this ASAP if not real problems

**Comment by cristianonicolai** [comment]
looks like another connection issue, retrying
jenkins please retest this

**Comment by mareknovotny** [comment]
tests are continously failing due losing connections in environments, I will merge this to not infinitely wait for green.

**Pull request merged**
