### PR TITLE
KOGITO-7537 - Downgrade Codestart test API

### PR DESCRIPTION
**Pull request by cristianonicolai**
Assembly:
- https://github.com/kiegroup/kogito-runtimes/pull/2332
- https://github.com/kiegroup/drools/pull/4539

### CODE REVIEW

**Comment by cristianonicolai** [comment]
Jenkins rerun kogito-runtimes tests

**Review by evacchi — APPROVED** [review]
@fyi tarilabs

**Comment by tarilabs** [comment]
thanks for the headsup, but I don't understand why this "revert". I understood previously you _wanted me_ to use the codestart new API. Now this is reverted on main. I checked the JIRA, there is no detail about it. Can you clarify why this was needed, please?

**Comment by cristianonicolai** [comment]
> clarify why this was needed,

@tarilabs although _setupStandaloneExtensionTest_ is, from my perspective, the appropriate way to set up the extension test, that was introduced only on Quarkus 2.10. At the moment, we still need to keep compatibility with Quarkus 2.7 because of RHBQ, where this method is not available ( it was refactored ), hence I'm pushing a temporary revert of the use of this API so we can keep compatibility with both versions of Quarkus.

**Comment by kie-ci3** [comment]
**(tests) - kogito-apps job** `#618` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/618/display/redirect

**Test results:**
- PASSED: 1847
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/618/testReport/org.kie.kogito.index/ProcessDataIndexPostgreSqlIT/testProcessInstanceEvents/">org.kie.kogito.index.ProcessDataIndexPostgreSqlIT.testProcessInstanceEvents</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>JSON path data.UserTaskInstances[0].comments.size() doesn't match.<br/>Expected: is <1><br/>  Actual: <0><br/><br/>
</details>

**Comment by radtriste** [comment]
jenkins rerun kogito-apps tests

**Review by radtriste — APPROVED** [review]

**Pull request merged**
