### PR TITLE
[1.0.x] KOGITO-3870 Mark Quarkus Extension as "stable"

### PR DESCRIPTION
**Pull request by evacchi**
https://issues.redhat.com/browse/KOGITO-3870

Set Quarkus Extension to "stable" instead of "preview"; otherwise it will show up with a "preview" label in code.quarkus.io UI

image

---

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.md)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Review by radtriste — APPROVED** [review]

**Review by cristianonicolai — APPROVED** [review]

**Review by tiagodolphine — APPROVED** [review]

**Comment by evacchi** [comment]
jenkins please retest this

**Comment by evacchi** [comment]
jenkins please retest this

**Review by danielezonca — APPROVED** [review]

**Review by mariofusco — APPROVED** [review]

**Comment by evacchi** [comment]
jenkins please retest this

**Comment by evacchi** [comment]
jenkins please retest this

**Comment by radtriste** [comment]
@cristianonicolai This one can be merged :)

**Pull request merged**
