### PR TITLE
[KOGITO-5687] Fixing proto file path on windows

### PR DESCRIPTION
**Pull request by fjtirado**

### CODE REVIEW

**Review by cristianonicolai — APPROVED** [review]

**Comment by cristianonicolai** [comment]
Fixes https://github.com/kiegroup/kogito-examples/issues/769

**Comment by ricardozanini** [comment]
Closes https://github.com/kiegroup/kogito-runtimes/pull/1523

**Comment by cristianonicolai** [comment]
Jenkins rerun apps tests

**Comment by cristianonicolai** [comment]
Jenkins rerun examples tests

**Review by elguardian — APPROVED** [review]

**Pull request merged**
