### PR TITLE
test - do not merge

### PR DESCRIPTION
**Pull request by radtriste**
Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](CONTRIBUTING.md)
- [ ] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/main/kogito-build/kogito-ide-config)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Run all builds</b>  
  Please add comment: <b>Jenkins retest this</b>

* <b>Run (or rerun) specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] tests</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Run (or rerun) LTS specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

* <b>Run (or rerun) native specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] native</b>

* <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

### CODE REVIEW

**Comment by radtriste** [comment]
jenkins retest this

**Comment by radtriste** [comment]
jenkins retest this

**Comment by radtriste** [comment]
jenkins retest this

**Comment by radtriste** [comment]
jenkins retest this

**Comment by kie-ci1** [comment]
**(tests) - kogito-runtimes job** #5 was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/custom/job/tradisso/job/kogito-runtimes-pr-check-new-format/5/display/redirect or see console log:
<details>
<summary><b>Console Logs</b></summary>
GitHub pull request #1944 of commit bc53fd40741a7b0fbba9334364108a2cdeb4f765, no merge conflicts.<br/>Setting status of bc53fd40741a7b0fbba9334364108a2cdeb4f765 to PENDING with url https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/custom/job/tradisso/job/kogito-runtimes-pr-check-new-format/5/display/redirect and message: 'Build started.'<br/>Using context: (build) kogito-runtimes<br/>Checking out git https://github.com/radtriste/kogito-pipelines.git into /var/lib/jenkins/jobs/custom/jobs/tradisso/jobs/kogito-runtimes-pr-check-new-format/workspace@script to read .ci/jenkins/Jenkinsfile.buildchain<br/>The recommended git tool is: NONE<br/>using credential kie-ci<br/> > git rev-parse --resolve-git-dir /var/lib/jenkins/jobs/custom/jobs/tradisso/jobs/kogito-runtimes-pr-check-new-format/workspace@script/.git # timeout=10<br/>Fetching changes from the remote Git repository<br/> > git config remote.origin.url https://github.com/radtriste/kogito-pipelines.git # timeout=10<br/>Cleaning workspace<br/> > git rev-parse --verify HEAD # timeout=10<br/>Resetting working tree<br/> > git reset --hard # timeout=10<br/> > git clean -fdx # timeout=10<br/>Fetching upstream changes from https://github.com/radtriste/kogito-pipelines.git<br/> > git --version # timeout=10<br/> > git --version # 'git version 1.8.3.1'<br/>using GIT_ASKPASS to set credentials PSSWD: kie-ci service account with access to jboss-integration private github space<br/> > git fetch --tags --progress https://github.com/radtriste/kogito-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git rev-parse origin/updated_logs_markdown_display^{commit} # timeout=10<br/>Checking out Revision 21ee6360432a76f1e28eb6d5cadca668a99521ed (origin/updated_logs_markdown_display)<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f 21ee6360432a76f1e28eb6d5cadca668a99521ed # timeout=10<br/>Commit message: "updated buildchain file"<br/> > git rev-list --no-walk d1f597e9f7ffe201946ac7641cb7ff2b30328ec1 # timeout=10<br/>Loading library tradisso-jenkins-pipeline-shared-libraries@updated_logs_markdown_display<br/>Attempting to resolve updated_logs_markdown_display from remote references...<br/> > git --version # timeout=10<br/> > git --version # 'git version 1.8.3.1'<br/>using GIT_ASKPASS to set credentials PSSWD: kie-ci service account with access to jboss-integration private github space<br/> > git ls-remote -h https://github.com/radtriste/jenkins-pipeline-shared-libraries.git # timeout=10<br/>Found match: refs/heads/updated_logs_markdown_display revision f35a0c04aca7faa8857ace6d949db55fe20093da<br/>Selected Git installation does not exist. Using Default<br/>The recommended git tool is: NONE<br/>using credential kie-ci<br/> > git rev-parse --resolve-git-dir /var/lib/jenkins/jobs/custom/jobs/tradisso/jobs/kogito-runtimes-pr-check-new-format/workspace@libs/tradisso-jenkins-pipeline-shared-libraries/.git # timeout=10<br/>Fetching changes from the remote Git repository<br/> > git config remote.origin.url https://github.com/radtriste/jenkins-pipeline-shared-libraries.git # timeout=10<br/>Fetching without tags<br/>Fetching upstream changes from https://github.com/radtriste/jenkins-pipeline-shared-libraries.git<br/> > git --version # timeout=10<br/> > git --version # 'git version 1.8.3.1'<br/>using GIT_ASKPASS to set credentials PSSWD: kie-ci service account with access to jboss-integration private github space<br/> > git fetch --no-tags --progress https://github.com/radtriste/jenkins-pipeline-shared-libraries.git +refs/heads/*:refs/remotes/origin/* # timeout=10<br/>Checking out Revision f35a0c04aca7faa8857ace6d949db55fe20093da (updated_logs_markdown_display)<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f f35a0c04aca7faa8857ace6d949db55fe20093da # timeout=10<br/>Commit message: "update"<br/> > git rev-list --no-walk f35a0c04aca7faa8857ace6d949db55fe20093da # timeout=10<br/>[Pipeline] Start of Pipeline<br/>[Pipeline] node<br/>Running on rhos-01-kie-rhel8-priority-1493 in /home/jenkins/workspace/custom/tradisso/kogito-runtimes-pr-check-new-format<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Checkout SCM)<br/>[Pipeline] checkout<br/>The recommended git tool is: NONE<br/>using credential kie-ci<br/>Cloning the remote Git repository<br/>Avoid second fetch<br/>Checking out Revision 21ee6360432a76f1e28eb6d5cadca668a99521ed (origin/updated_logs_markdown_display)<br/>Commit message: "updated buildchain file"<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] timestamps<br/>[Pipeline] {<br/>[Pipeline] timeout<br/>[2022-01-27T13:54:44.958Z] Timeout set to expire in 3 hr 0 min<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Tool Install)<br/>[Pipeline] tool<br/>[2022-01-27T13:54:45.125Z] Unpacking https://nodejs.org/dist/v12.16.3/node-v12.16.3-linux-x64.tar.gz to /home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-12.16.3 on rhos-01-kie-rhel8-priority-1493<br/>Cloning repository https://github.com/radtriste/kogito-pipelines.git<br/> > git init /home/jenkins/workspace/custom/tradisso/kogito-runtimes-pr-check-new-format # timeout=10<br/>Fetching upstream changes from https://github.com/radtriste/kogito-pipelines.git<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.27.0'<br/>using GIT_ASKPASS to set credentials PSSWD: kie-ci service account with access to jboss-integration private github space<br/> > git fetch --tags --force --progress -- https://github.com/radtriste/kogito-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git config remote.origin.url https://github.com/radtriste/kogito-pipelines.git # timeout=10<br/> > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git rev-parse origin/updated_logs_markdown_display^{commit} # timeout=10<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f 21ee6360432a76f1e28eb6d5cadca668a99521ed # timeout=10<br/>[Pipeline] envVarsForTool<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Initialize)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-01-27T13:54:48.057Z] + printenv<br/>[Pipeline] archiveArtifacts<br/>[2022-01-27T13:54:48.165Z] Archiving artifacts<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space before build)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] dir<br/>[2022-01-27T13:54:50.379Z] Running in /home/jenkins/workspace/custom/tradisso/kogito-runtimes-pr-check-new-format<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2022-01-27T13:54:50.428Z] [INFO] space left on the machine<br/>[Pipeline] sh<br/>[2022-01-27T13:54:50.706Z] + df -h<br/>[2022-01-27T13:54:50.706Z] Filesystem      Size  Used Avail Use% Mounted on<br/>[2022-01-27T13:54:50.706Z] devtmpfs        3.8G     0  3.8G   0% /dev<br/>[2022-01-27T13:54:50.706Z] tmpfs           3.8G     0  3.8G   0% /dev/shm<br/>[2022-01-27T13:54:50.706Z] tmpfs           3.8G   33M  3.8G   1% /run<br/>[2022-01-27T13:54:50.706Z] tmpfs           3.8G     0  3.8G   0% /sys/fs/cgroup<br/>[2022-01-27T13:54:50.706Z] /dev/vda3        60G   21G   40G  34% /<br/>[2022-01-27T13:54:50.706Z] /dev/vda2       100M  5.8M   95M   6% /boot/efi<br/>[2022-01-27T13:54:50.706Z] tmpfs           777M     0  777M   0% /run/user/1000<br/>[Pipeline] echo<br/>[2022-01-27T13:54:50.725Z] [INFO] space of /home/jenkins<br/>[Pipeline] sh<br/>[2022-01-27T13:54:51.008Z] + du -h -d1 /home/jenkins<br/>[2022-01-27T13:54:51.008Z] 4.0K	/home/jenkins/.ssh<br/>[2022-01-27T13:54:51.008Z] 0	/home/jenkins/go<br/>[2022-01-27T13:54:51.008Z] 8.0K	/home/jenkins/.vnc<br/>[2022-01-27T13:54:51.008Z] 8.0K	/home/jenkins/.m2<br/>[2022-01-27T13:54:51.008Z] 2.1G	/home/jenkins/git-repos<br/>[2022-01-27T13:54:51.008Z] 8.0K	/home/jenkins/.config<br/>[2022-01-27T13:54:51.008Z] 4.0K	/home/jenkins/.cekit<br/>[2022-01-27T13:54:51.008Z] 78M	/home/jenkins/virtenvs<br/>[2022-01-27T13:54:51.008Z] 30M	/home/jenkins/remoting<br/>[2022-01-27T13:54:51.008Z] 0	/home/jenkins/.cache<br/>[2022-01-27T13:54:51.008Z] 1.3G	/home/jenkins/workspace<br/>[2022-01-27T13:54:51.008Z] 81M	/home/jenkins/tools<br/>[2022-01-27T13:54:51.008Z] 0	/home/jenkins/caches<br/>[2022-01-27T13:54:51.008Z] 3.5G	/home/jenkins<br/>[Pipeline] echo<br/>[2022-01-27T13:54:51.026Z] [INFO] space of workspace<br/>[Pipeline] sh<br/>[2022-01-27T13:54:51.313Z] + du -h -d3 /home/jenkins/workspace<br/>[2022-01-27T13:54:51.313Z] 761M	/home/jenkins/workspace/KIE/kogito/main<br/>[2022-01-27T13:54:51.313Z] 153M	/home/jenkins/workspace/KIE/kogito/1.16.x<br/>[2022-01-27T13:54:51.313Z] 153M	/home/jenkins/workspace/KIE/kogito/1.15.x<br/>[2022-01-27T13:54:51.313Z] 202M	/home/jenkins/workspace/KIE/kogito/1.11.x<br/>[2022-01-27T13:54:51.313Z] 1.3G	/home/jenkins/workspace/KIE/kogito<br/>[2022-01-27T13:54:51.313Z] 1.3G	/home/jenkins/workspace/KIE<br/>[2022-01-27T13:54:51.313Z] 2.1M	/home/jenkins/workspace/custom/tradisso/kogito-runtimes-pr-check-new-format<br/>[2022-01-27T13:54:51.313Z] 8.0K	/home/jenkins/workspace/custom/tradisso/kogito-runtimes-pr-check-new-format@tmp<br/>[2022-01-27T13:54:51.313Z] 2.1M	/home/jenkins/workspace/custom/tradisso<br/>[2022-01-27T13:54:51.313Z] 2.1M	/home/jenkins/workspace/custom<br/>[2022-01-27T13:54:51.313Z] 1.3G	/home/jenkins/workspace<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Install build-chain tool)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2022-01-27T13:54:51.653Z] [INFO] Getting build-chain version from composite action file<br/>[Pipeline] readFile<br/>Scripts not permitted to use staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods getText java.net.URL. Administrators can decide whether to approve or reject this signature.<br/>[Pipeline] echo<br/>[2022-01-27T13:54:51.924Z] [INFO] build-chain version recovered '2.3.29'<br/>[Pipeline] sh<br/>[2022-01-27T13:54:52.230Z] + npm install -g @kie/build-chain-action@2.3.29 -registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/<br/>[2022-01-27T13:54:58.766Z] /home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-12.16.3/bin/build-chain-action -> /home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-12.16.3/lib/node_modules/@kie/build-chain-action/bin/build-chain-cli.js<br/>[2022-01-27T13:54:58.766Z] npm WARN notsup Unsupported engine for @kie/build-chain-action@2.3.29: wanted: {"node":">= 12.18.0"} (current: {"node":"12.16.3","npm":"6.14.4"})<br/>[2022-01-27T13:54:58.766Z] npm WARN notsup Not compatible with your version of node/npm: @kie/build-chain-action@2.3.29<br/>[2022-01-27T13:54:58.766Z] npm WARN @octokit/plugin-request-log@1.0.4 requires a peer of @octokit/core@>=3 but none is installed. You must install peer dependencies yourself.<br/>[2022-01-27T13:54:58.766Z] <br/>[2022-01-27T13:54:58.766Z] + @kie/build-chain-action@2.3.29<br/>[2022-01-27T13:54:58.766Z] added 111 packages from 89 contributors in 5.242s<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] error<br/>[Pipeline] }<br/>[Pipeline] // script<br/>Post stage<br/>[Pipeline] junit<br/>[2022-01-27T13:54:59.250Z] Recording test results<br/>[2022-01-27T13:54:59.339Z] No test report files were found. Configuration error?<br/>Error when executing always post condition:<br/>Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to rhos-01-kie-rhel8-priority-1493<br/>		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1797)<br/>		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)<br/>		at hudson.remoting.Channel.call(Channel.java:1001)<br/>		at hudson.FilePath.act(FilePath.java:1166)<br/>		at hudson.FilePath.act(FilePath.java:1155)<br/>		at hudson.tasks.junit.JUnitParser.parseResult(JUnitParser.java:107)<br/>		at hudson.tasks.junit.JUnitResultArchiver.parse(JUnitResultArchiver.java:153)<br/>		at hudson.tasks.junit.JUnitResultArchiver.parseAndSummarize(JUnitResultArchiver.java:247)<br/>		at hudson.tasks.junit.pipeline.JUnitResultsStepExecution.run(JUnitResultsStepExecution.java:63)<br/>		at hudson.tasks.junit.pipeline.JUnitResultsStepExecution.run(JUnitResultsStepExecution.java:29)<br/>		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)<br/>		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)<br/>hudson.AbortException: No test report files were found. Configuration error?<br/>	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:154)<br/>	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3338)<br/>	at hudson.remoting.UserRequest.perform(UserRequest.java:211)<br/>	at hudson.remoting.UserRequest.perform(UserRequest.java:54)<br/>	at hudson.remoting.Request$2.run(Request.java:376)<br/>	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)<br/>	at java.util.concurrent.FutureTask.run(FutureTask.java:266)<br/>	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)<br/>	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)<br/>	at java.lang.Thread.run(Thread.java:748)<br/><br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-01-27T13:54:59.656Z] + rm -rf console.log<br/>[Pipeline] sh<br/>
</details>

**Pull request closed without merging**
