### PR TITLE
KOGITO-4595 Downgrade Quarkus 1.11

### PR DESCRIPTION
**Pull request by evacchi**
https://github.com/kiegroup/kogito-runtimes/pull/1115
https://github.com/kiegroup/kogito-apps/pull/692
https://github.com/kiegroup/kogito-examples/pull/601

https://issues.redhat.com/browse/KOGITO-4595

### CODE REVIEW

**Comment by evacchi** [comment]
🤔 

```
stderr: remote: Repository not found.
fatal: repository 'https://github.com/evacchi/optaplanner.git/' not found
```

**Comment by evacchi** [comment]
jenkins please retest this

**Comment by evacchi** [comment]
jenkins please retest this

**Review by cristianonicolai — APPROVED** [review]

**Review by nmirasch — APPROVED** [review]

**Comment by evacchi** [comment]
jenkins please retest this

**Comment by evacchi** [comment]
Jenkins please retest this

**Pull request merged**
