### PR TITLE
[1.5.x] KOGITO-4902 Bump kie7 to 7.52.0.Final

### PR DESCRIPTION
**Pull request by evacchi**
related https://github.com/kiegroup/optaplanner/pull/1260

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](CONTRIBUTING.md)
- [ ] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/master/kogito-ide-config)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

* <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

### CODE REVIEW

**Comment by evacchi** [comment]
jenkins please retest this ✨

**Comment by evacchi** [comment]
```
Error
'void org.drools.core.rule.Pattern.<init>(int, int, org.drools.core.spi.ObjectType, java.lang.String, boolean)'
Stacktrace
java.lang.NoSuchMethodError: 'void org.drools.core.rule.Pattern.<init>(int, int, org.drools.core.spi.ObjectType, java.lang.String, boolean)'
at org.drools.modelcompiler.KiePackagesBuilder.addPatternForVariable(KiePackagesBuilder.java:976)
at org.drools.modelcompiler.KiePackagesBuilder.buildPattern(KiePackagesBuilder.java:746)
at org.drools.modelcompiler.KiePackagesBuilder.conditionToElement(KiePackagesBuilder.java:488)
at org.drools.modelcompiler.KiePackagesBuilder.addSubConditions(KiePackagesBuilder.java:671)
at org.drools.modelcompiler.KiePackagesBuilder.populateLHS(KiePackagesBuilder.java:451)
at org.drools.modelcompiler.KiePackagesBuilder.compileRule(KiePackagesBuilder.java:251)
at org.drools.modelcompiler.KiePackagesBuilder.build(KiePackagesBuilder.java:222)
at org.drools.modelcompiler.CanonicalKieModule.createKiePackages(CanonicalKieModule.java:309)
at org.drools.modelcompiler.CanonicalKieModule.lambda$createKieBase$1(CanonicalKieModule.java:213)
at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
at org.drools.modelcompiler.CanonicalKieModule.createKieBase(CanonicalKieModule.java:213)
```

@danielezonca @r00ta @kostola anyone knows what this is about?

**Comment by r00ta** [comment]
> org.kie.kogito.explainability.explainability.integrationtests.pmml.PmmlCompoundScorecardLimeExplainerTest – org.kie.kogito.explainability.explainability.integrationtests.pmml.PmmlCompoundScorecardLimeExplainerTest
> 
> ```
> Error
> 'void org.drools.core.rule.Pattern.<init>(int, int, org.drools.core.spi.ObjectType, java.lang.String, boolean)'
> Stacktrace
> java.lang.NoSuchMethodError: 'void org.drools.core.rule.Pattern.<init>(int, int, org.drools.core.spi.ObjectType, java.lang.String, boolean)'
> at org.drools.modelcompiler.KiePackagesBuilder.addPatternForVariable(KiePackagesBuilder.java:976)
> at org.drools.modelcompiler.KiePackagesBuilder.buildPattern(KiePackagesBuilder.java:746)
> at org.drools.modelcompiler.KiePackagesBuilder.conditionToElement(KiePackagesBuilder.java:488)
> at org.drools.modelcompiler.KiePackagesBuilder.addSubConditions(KiePackagesBuilder.java:671)
> at org.drools.modelcompiler.KiePackagesBuilder.populateLHS(KiePackagesBuilder.java:451)
> at org.drools.modelcompiler.KiePackagesBuilder.compileRule(KiePackagesBuilder.java:251)
> at org.drools.modelcompiler.KiePackagesBuilder.build(KiePackagesBuilder.java:222)
> at org.drools.modelcompiler.CanonicalKieModule.createKiePackages(CanonicalKieModule.java:309)
> at org.drools.modelcompiler.CanonicalKieModule.lambda$createKieBase$1(CanonicalKieModule.java:213)
> at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
> at org.drools.modelcompiler.CanonicalKieModule.createKieBase(CanonicalKieModule.java:213)
> ```
> 
> @danielezonca @r00ta @kostola anyone knows what this is about?

Hi @evacchi , sorry I have no clue. @gitgabrio ^^ ?

**Comment by evacchi** [comment]
jenkins please retest this 💣

**Comment by triceo** [comment]
New PR: https://github.com/kiegroup/optaplanner/pull/1260

**Comment by evacchi** [comment]
jenkins please retest this

**Review by radtriste — APPROVED** [review]

**Comment by evacchi** [comment]
jenkins please retest this

**Comment by evacchi** [comment]
jenkins please retest this

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by mbiarnes** [comment]
Jenkins retest this

**Pull request merged**
