### PR TITLE
[1.11.x] KOGITO-6929 spring-boot to 2.6.6 (#2120)

### PR DESCRIPTION
**Pull request by Ginxo**
https://issues.redhat.com/browse/KOGITO-6929

Related PRs:

- https://github.com/kiegroup/kogito-runtimes/pull/2137
- https://github.com/kiegroup/kogito-examples/pull/1215
- https://github.com/kiegroup/optaplanner/pull/1931
- https://github.com/kiegroup/kogito-apps/pull/1299

Related to https://github.com/kiegroup/kogito-runtimes/pull/2120

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Run all builds</b>  
  Please add comment: <b>Jenkins retest this</b>

* <b>Run (or rerun) specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] tests</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Run (or rerun) LTS specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

* <b>Run (or rerun) native specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] native</b>

* <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

### CODE REVIEW

**Comment by Ginxo** [comment]
testing jobs by https://github.com/kiegroup/kogito-runtimes/pull/2139

**Review by VaniHaripriya — APPROVED** [review]

**Comment by Ginxo** [comment]
Jenkins run kogito-examples tests

**Comment by Ginxo** [comment]
Jenkins retest this

**Comment by Ginxo** [comment]
Jenkins run kogito-examples tests

**Comment by Ginxo** [comment]
build-chain configuration is wrong, I will check it after merging this set of PRs

**Comment by Ginxo** [comment]
Jenkins retest this

**Comment by Ginxo** [comment]
Ready to mreview/merge. See https://github.com/kiegroup/kogito-runtimes/pull/2139 to compare checks results

**Comment by mareknovotny** [comment]
Jenkins run kogito-apps tests

**Comment by mareknovotny** [comment]
Jenkins run kogito-apps tests

**Comment by Ginxo** [comment]
Jenkins run kogito-apps tests

**Comment by Ginxo** [comment]
Jenkins rerun kogito-apps tests

**Comment by Ginxo** [comment]
Jenkins retest this

**Comment by Ginxo** [comment]
Jenkins run optaplanner tests

**Comment by Ginxo** [comment]
@cristianonicolai @evacchi could you please help here? I'm not able to see the problem with kogito-apps...

**Comment by mareknovotny** [comment]
@evacchi could you please look at failures and help us to sort them out?

**Comment by Ginxo** [comment]
Jenkins run apps tests

**Comment by Ginxo** [comment]
Jenkins run apps tests

**Pull request merged**
