### PR TITLE
Removed unused dependencies

### PR DESCRIPTION
**Pull request by ruromero**
Signed-off-by: ruromero <rromerom@redhat.com>

Fix native build for integration-tests-quarkus-rules project

### CODE REVIEW

**Review by ricardozanini — APPROVED** [review]
LGTM

**Comment by ruromero** [comment]
The build is failing for an unrelated issue.
Kogito Apps:: UI Packages

**Review by evacchi — APPROVED** [review]

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by ruromero** [comment]
jenkins retest this

**Review by cristianonicolai — APPROVED** [review]

**Pull request merged**
