### PR TITLE
[KOGITO-6207] Handling compensation for serverless workflow

### PR DESCRIPTION
**Pull request by fjtirado**
Example in https://github.com/kiegroup/kogito-examples/pull/989

### CODE REVIEW

**Comment by fjtirado** [comment]
jenkins rerun kogito-examples tests

**Review by tiagodolphine — COMMENTED** [review]
In general, it LGTM, I think it is missing some integration test, to test the execution of a SW with compensations in different situations, in different steps, to check if all compensations were executed and in the order that they were supposed to be executed. Something similar to CompensationIT or CompensationTest, wdyt?

**Comment by fjtirado** [comment]
> In general, it LGTM, I think it is missing some integration test, to test the execution of a SW with compensations in different situations, in different steps, to check if all compensations were executed and in the order that they were supposed to be executed. Something similar to CompensationIT or CompensationTest, wdyt?

Did you check the example?

**Comment by fjtirado** [comment]
jenkins rerun kogito-apps tests

**Review by tiagodolphine — APPROVED** [review]

**Review by ricardozanini — APPROVED** [review]

**Pull request merged**
