### PR TITLE
KOGITO-6534 Always pull latest image version of Data Index

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by manstis** [comment]
Well.. this minimises the versioning problem :smiley: 

I'm doing the same change to trusty.

**Review by radtriste — APPROVED** [review]

**Comment by manstis** [comment]
@cristianonicolai With this change, I found I can no longer use local images. Can you verify?

For example when the image name is `org.kie.kogito/trusty-service-infinispan:2.0.0-SNAPSHOT` and I confirm it's in my local cache, Docker still attempts to pull from `org.kie.kogito`. See https://stackoverflow.com/questions/20481225/how-can-i-use-a-local-image-as-the-base-image-with-a-dockerfile

**Comment by cristianonicolai** [comment]
@manstis updated so it only pulls if image tag is `latest`.

**Review by ricardozanini — APPROVED** [review]

**Comment by cristianonicolai** [comment]
Jenkins rerun kogito-examples tests

**Pull request merged**
