### PR TITLE
KOGITO-1655: Bump 0.9.x to 0.9.1-SNAPSHOT

### PR DESCRIPTION
**Pull request by evacchi**
should we do this for examples too? anything else?

### CODE REVIEW

**Comment by radtriste** [comment]
you should update all the pom in the repository ;)

**Comment by radtriste** [comment]
and yes, should also be done on kogito-examples

**Comment by cristianonicolai** [comment]
I still not sold on this, would really prefer to avoid this for now. But if this is the direction, please update all three repos, including runtimes, app and examples. Would be important to update the release script as well so this manual steps/prs aren't needed.

**Comment by radtriste** [comment]
kogito-examples has been updated. kogito-apps is in progress https://github.com/kiegroup/kogito-apps/pull/140#pullrequestreview-385777587
I am focusing on deploy pipeline from kogito-runtimes
PR Jenkinsfiles should already handle correctly this as we are using `CHANGE_TARGET` variable

**Pull request merged**
