### PR TITLE
Failsafe and Surefire plugins upgrade

### PR DESCRIPTION
**Pull request by cristianonicolai**
Assembly:
- https://github.com/kiegroup/kogito-runtimes/pull/1253
- https://github.com/kiegroup/kogito-apps/pull/788

### CODE REVIEW

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Review by radtriste — APPROVED** [review]

**Comment by cristianonicolai** [comment]
depends on https://github.com/kiegroup/kogito-apps/pull/787

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Pull request merged**
