### PR TITLE
[KOGITO-6768] Be able to rename default channel

### PR DESCRIPTION
**Pull request by fjtirado**
The properties to rename channel are 
`kogito.addon.messaging.incoming.defaultName` and` kogito.addon.messaging.outgoing.defaultName`
See example at https://github.com/kiegroup/kogito-examples/pull/1126

### CODE REVIEW

**Review by ricardozanini — APPROVED** [review]
Nice! Can you please also update the docs? https://docs.jboss.org/kogito/release/latest/html_single/#_kogito_messaging_add_on

**Review by tiagodolphine — COMMENTED** [review]
Nice, just one question, so this change is to make it possible to change the channel in case of the "single" approach, for the "multi" we keep the current behavior?

**Comment by ricardozanini** [comment]
> Nice, just one question, so this change is to make it possible to change the channel in case of the "single" approach, for the "multi" we keep the current behavior?

Looks like this. We need to update the docs to clarify these questions.

**Comment by kie-ci1** [comment]
**(tests) - kogito-examples job** `#1163` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 432
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1163/testReport/org.kie.kogito.examples.demo/OutboxIT/___/">org.kie.kogito.examples.demo.OutboxIT.(?)</a></summary>
java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [8080, 49254] should be listening)<br/>	at org.kie.kogito.examples.demo.OutboxIT.before(OutboxIT.java:81)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [8080, 49254] should be listening)<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1163/display/redirect

**Comment by fjtirado** [comment]
More than differentiating between "single" and "multi", we should talk about channel mapping. 
Unless there is a channel with the same name than the message name in the bpmn or the event type in the Serverless Workflow defined in application.properties, the generator will search for the default channel. 
This JIRA just allows to define a different channel name than kogito_incoming_stream or kogito_output_stream. 
But nothing else has changed, you can still for three event types, an specific channel for one of them and the other two will use the default. And you will always need at least one incoming and one outgoing channel defined in your application.properties for Kogito to work.

**Review by tiagodolphine — APPROVED** [review]

**Pull request merged**
