### PR TITLE
FAI-722: Set containers name as property

### PR DESCRIPTION
**Pull request by sjamboro**
https://issues.redhat.com/browse/FAI-722

This PR should be merge together with https://github.com/kiegroup/kogito-apps/pull/1250

### CODE REVIEW

**Comment by kie-ci1** [comment]
**(tests) - kogito-examples job** `#1264` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 432
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1264/testReport/org.kie.kogito.examples/CallbackRestIT/Build_projects___testCallbackRest/">Build projects / org.kie.kogito.examples.CallbackRestIT.testCallbackRest</a></summary>
org.awaitility.core.ConditionTimeoutException: <br/>Assertion condition defined as a lambda expression in org.kie.kogito.examples.CallbackRestIT that uses java.lang.String 1 expectation failed.<br/>Expected status code <404> but was <200>.<br/> within 30 seconds.<br/>	at org.kie.kogito.examples.CallbackRestIT.testCallbackRest(CallbackRestIT.java:50)<br/>Caused by: java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <404> but was <200>.<br/><br/>	at org.kie.kogito.examples.CallbackRestIT.lambda$testCallbackRest$0(CallbackRestIT.java:55)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1264/testReport/org.acme.travel.tests.avro.quarkus/MultiMessagingIT/testProcess/">org.acme.travel.tests.avro.quarkus.MultiMessagingIT.testProcess</a></summary>
org.opentest4j.AssertionFailedError: expected: <0> but was: <3><br/>	at org.acme.travel.tests.avro.quarkus.MultiMessagingIT.testProcess(MultiMessagingIT.java:89)<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1264/display/redirect

**Comment by sjamboro** [comment]
@cristianonicolai thank you for information. Now I am going to use the new property "container.image.wurstmeister.kafka". I have assigned a different issue to migrate to another container and unify it: https://issues.redhat.com/browse/FAI-729 

This issue is obsolete now. So I will migrate to Redpanda. I expect that it is not so easy as change a value of the property.

**Comment by kie-ci1** [comment]
**(tests) - kogito-runtimes job** `#1145` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 2498
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/1145/testReport/org.kie.kogito.integrationtests.springboot/PingPongMessageTest/testPingPongBetweenProcessInstances/">org.kie.kogito.integrationtests.springboot.PingPongMessageTest.testPingPongBetweenProcessInstances</a></summary>
org.awaitility.core.ConditionTimeoutException: <br/>Assertion condition defined as a org.kie.kogito.integrationtests.springboot.PingPongMessageTest 1 expectation failed.<br/>JSON path $.size() doesn't match.<br/>Expected: <1><br/>  Actual: 0<br/> within 10 seconds.<br/>	at org.kie.kogito.integrationtests.springboot.PingPongMessageTest.validateSubProcess(PingPongMessageTest.java:85)<br/>	at org.kie.kogito.integrationtests.springboot.PingPongMessageTest.testPingPongBetweenProcessInstances(PingPongMessageTest.java:56)<br/>Caused by: java.lang.AssertionError: <br/>1 expectation failed.<br/>JSON path $.size() doesn't match.<br/>Expected: <1><br/>  Actual: 0<br/><br/>	at org.kie.kogito.integrationtests.springboot.PingPongMessageTest.lambda$validateSubProcess$1(PingPongMessageTest.java:91)<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/1145/display/redirect

**Comment by kie-ci1** [comment]
**(tests) - kogito-examples job** `#1273` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 432
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1273/testReport/org.acme.travel.tests.messaging.quarkus/MessagingIT/testProcess/">org.acme.travel.tests.messaging.quarkus.MessagingIT.testProcess</a></summary>
org.opentest4j.AssertionFailedError: expected: <0> but was: <3><br/>	at org.acme.travel.tests.messaging.quarkus.MessagingIT.testProcess(MessagingIT.java:110)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1273/testReport/org.kie.kogito.examples.demo/OutboxIT/___/">org.kie.kogito.examples.demo.OutboxIT.(?)</a></summary>
java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [8080, 49237] should be listening)<br/>	at org.kie.kogito.examples.demo.OutboxIT.before(OutboxIT.java:81)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [8080, 49237] should be listening)<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1273/display/redirect

**Review by ricardozanini — APPROVED** [review]

**Comment by kie-ci1** [comment]
**(tests) - kogito-examples job** `#1275` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 433
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1275/testReport/org.kie.kogito.examples.demo/OutboxIT/___/">org.kie.kogito.examples.demo.OutboxIT.(?)</a></summary>
java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [8080, 49255] should be listening)<br/>	at org.kie.kogito.examples.demo.OutboxIT.before(OutboxIT.java:81)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [8080, 49255] should be listening)<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1275/display/redirect

**Comment by sjamboro** [comment]
@ricardozanini, @cristianonicolai Is possible to merge PRs for FAI-722? I need to investigate how to migrate containers to use redpanda. At least I need to replace `kafka-1` by `redpanda` because DMP does not support aliases in this version. I would like to store information about migration in a separate jira. In case that you want to close this PR, I need to correct https://github.com/kiegroup/kogito-apps/pull/1250. Now both PRs are green.

**Pull request merged**
