### PR TITLE
KOGITO-3752 Add Rules REST Templated endpoint for Spring MVC support

### PR DESCRIPTION
**Pull request by evacchi**
https://issues.redhat.com/browse/KOGITO-3752

Add support for templates in Rule endpoint generation (this is just keeping jax-rs, we can customize spring-specific in a separate PR)

------

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.md)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Review by cristianonicolai — APPROVED** [review]

**Comment by tiagodolphine** [comment]
@evacchi I'll cherry-pick this to my branch to start working with it. It is missing now just the rules part then we follow up in the PR I already opened.

**Comment by evacchi** [comment]
jenkins please retest this

**Comment by evacchi** [comment]
I think this can be closed yes? @tiagodolphine

**Comment by tiagodolphine** [comment]
yeah @evacchi I already cherry-picked this into the branch that was already merged.  So it's fine to close this.

**Pull request closed without merging**
