### PR TITLE
[KOGITO-650] Support for Enum marshalling

### PR DESCRIPTION
**Pull request by ruromero**
Fix: https://issues.redhat.com/browse/KOGITO-650

Adds support for Enum marshalling both using Jandex and Reflection.
## Reflection proto generation
As this type of generation has acces to the class and fields declaration, the order can be respected.

## Jandex proto generation
However for Jandex proto generation, where the file is read and is not part of the classpath it is not possible to get the fields as they are declared. Fields are sorted lexicographically and in order to have a  reliable marshaller generation, fields have to be declared in order.

```
public MyEnum {
 YES,
 MAYBE,
 NO
}
```

This code will result in the following proto file:

```
syntax = "proto2"; 
package org.kie.kogito.test; 

enum Answer { 
	option java_package = "org.kie.kogito.codegen.data";
	YES = 2;
	NO = 1;
	MAYBE = 0;
}
```

Annotations provide a way to define metadata that is accessible during this step so if the user defines `@ProtoEnumValue` in each enum value it will be picked up by the generator and used to define the numeric values of each field.

```
import org.infinispan.protostream.annotations.ProtoEnumValue;

public enum AnswerWitAnnotations {
    @ProtoEnumValue(number = 0)
    YES,
    @ProtoEnumValue(number = 1)
    MAYBE,
    @ProtoEnumValue(number = 2)
    NO
}
```
Having the following as a result
```
syntax = "proto2"; 
package org.kie.kogito.test; 

enum AnswerWitAnnotations { 
	option java_package = "org.kie.kogito.codegen.data";
	NO = 2;
	MAYBE = 1;
	YES = 0;
}
```

## Marshallers

EnumMarshallers will be generated for each Enum like the one in the example:
```
import org.infinispan.protostream.EnumMarshaller;

public class AnswerWitAnnotationsEnumMarshaller implements EnumMarshaller<org.kie.kogito.codegen.data.AnswerWitAnnotations> {

    public String getTypeName() {
        return "org.kie.kogito.test.AnswerWitAnnotations";
    }

    public java.lang.Class<org.kie.kogito.codegen.data.AnswerWitAnnotations> getJavaClass() {
        return org.kie.kogito.codegen.data.AnswerWitAnnotations.class;
    }

    public int encode(org.kie.kogito.codegen.data.AnswerWitAnnotations state) {
        if (null == state)
            throw new java.lang.IllegalArgumentException("Invalid value provided to enum");
        return state.ordinal();
    }

    public org.kie.kogito.codegen.data.AnswerWitAnnotations decode(int value) {
        switch(value) {
            case 2:
                return org.kie.kogito.codegen.data.AnswerWitAnnotations.NO;
            case 1:
                return org.kie.kogito.codegen.data.AnswerWitAnnotations.MAYBE;
            case 0:
                return org.kie.kogito.codegen.data.AnswerWitAnnotations.YES;
            default:
                throw new java.lang.IllegalArgumentException("Invalid value provided to enum");
        }
    }
}
```

Signed-off-by: ruromero <rromerom@redhat.com>

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.md)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by ruromero** [comment]
It is a WIP until it persistence profile is added to the integration tests

**Comment by cristianonicolai** [comment]
@ruromero just a note to update docs in [here](https://docs.jboss.org/kogito/release/latest/html_single/#_supported_data_types_for_persisted_variables) once this is merged.

**Comment by ruromero** [comment]
Should use https://github.com/kiegroup/kogito-runtimes/pull/625

**Comment by tiagodolphine** [comment]
It seems there is the infinispan dependency missing for sprinboot integration tests... `org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.infinispan.client.hotrod.RemoteCacheManager'`

**Comment by ruromero** [comment]
@MarianMacik Can you take a look since I changed the integration tests?

**Comment by tiagodolphine** [comment]
@Sgitario would you mind taking a look at this PR, there are some new integration tests regarding persistence for the runtimes.
Thanks.

**Pull request merged**
