### PR TITLE
[KOGITO-6837] Fixing DefaultConditionError

### PR DESCRIPTION
**Pull request by fjtirado**

### CODE REVIEW

**Comment by kie-ci1** [comment]
**(tests) - kogito-examples job** `#1286` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 432
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1286/testReport/org.acme.travel.tests.messaging.quarkus/MessagingIT/testProcess/">org.acme.travel.tests.messaging.quarkus.MessagingIT.testProcess</a></summary>
org.opentest4j.AssertionFailedError: expected: <0> but was: <3><br/>	at org.acme.travel.tests.messaging.quarkus.MessagingIT.testProcess(MessagingIT.java:110)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1286/testReport/org.acme.travel.tests.multimessaging.springboot/MultiMessagingIT/testProcess/">org.acme.travel.tests.multimessaging.springboot.MultiMessagingIT.testProcess</a></summary>
org.opentest4j.AssertionFailedError: expected: <0> but was: <3><br/>	at org.acme.travel.tests.multimessaging.springboot.MultiMessagingIT.testProcess(MultiMessagingIT.java:96)<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1286/display/redirect

**Comment by kie-ci1** [comment]
**(tests) - kogito-apps job** `#1191` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 2678
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/1191/testReport/org.kie.kogito.index.infinispan/ProcessDataIndexInfinispanIT/testProcessInstanceEvents/">org.kie.kogito.index.infinispan.ProcessDataIndexInfinispanIT.testProcessInstanceEvents</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>JSON path errors doesn't match.<br/>Expected: null<br/>  Actual: <[{message=Exception while fetching data (/UserTaskInstanceAttachmentUpdate) : Index 0 out of bounds for length 0, locations=[{line=1, column=12}], path=[UserTaskInstanceAttachmentUpdate], extensions={classification=DataFetchingException}}]><br/><br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/1191/display/redirect

**Comment by fjtirado** [comment]
jenkins rerun kogito-examples tests

**Comment by fjtirado** [comment]
jenkins rerun kogito-apps tests

**Review by hbelmiro — APPROVED** [review]

**Review by ricardozanini — APPROVED** [review]

**Comment by kie-ci1** [comment]
**(tests) - kogito-examples job** `#1287` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 433
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1287/testReport/org.acme.travel.tests.messaging.quarkus/MessagingIT/testProcess/">org.acme.travel.tests.messaging.quarkus.MessagingIT.testProcess</a></summary>
org.opentest4j.AssertionFailedError: expected: <0> but was: <3><br/>	at org.acme.travel.tests.messaging.quarkus.MessagingIT.testProcess(MessagingIT.java:110)<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1287/display/redirect

**Pull request merged**
