### PR TITLE
Invoker failing to resolve Quarkus dep on local nexus repo on Jenkins CI

### PR DESCRIPTION
**Pull request by tarilabs**
<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Run all builds</b>  
  Please add comment: <b>Jenkins retest this</b>

* <b>Run (or rerun) specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] tests</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Run (or rerun) LTS specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

* <b>Run (or rerun) native specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] native</b>

* <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

### CODE REVIEW

**Comment by tarilabs** [comment]
jenkins run lts

**Comment by radtriste** [comment]
rate limit error ... jenkins retest this

**Comment by tarilabs** [comment]
Unfortunately the idea from @jstastny-cz does not solve, but it seems the error is changed

from
```
[2021-12-13T05:28:39.103Z] [INFO] --- maven-invoker-plugin:3.2.1:run (integration-test) @ integration-tests-kogito-plugin ---
[2021-12-13T05:28:39.103Z] [INFO] Building: integration-tests-kogito-plugin-it/pom.xml
[2021-12-13T05:28:41.022Z] [INFO] [INFO] Scanning for projects...
[2021-12-13T05:28:42.455Z] [INFO] [ERROR] [ERROR] Some problems were encountered while processing the POMs:
[2021-12-13T05:28:42.455Z] [INFO] [ERROR] Non-resolvable import POM: Could not find artifact io.quarkus:quarkus-bom:pom:999-SNAPSHOT in mirror-central (https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/) @ org.kie.kogito:kogito-quarkus-bom:1.11.2-SNAPSHOT, /home/jenkins/workspace/KIE/kogito/1.11.x/nightly/kogito-quarkus-2.2/kogito-runtimes/integration-tests/integration-tests-kogito-plugin/target/local-repo/org/kie/kogito/kogito-quarkus-bom/1.11.2-SNAPSHOT/kogito-quarkus-bom-1.11.2-SNAPSHOT.pom, line 21, column 19
[2021-12-13T05:28:42.455Z] [INFO] [ERROR] 'dependencies.dependency.version' for io.quarkus:quarkus-resteasy:jar is missing. @ line 35, column 21
[2021-12-13T05:28:42.455Z] [INFO] [ERROR] 'dependencies.dependency.version' for org.kie.kogito:kogito-quarkus:jar is missing. @ line 39, column 21
[2021-12-13T05:28:42.455Z] [INFO] [ERROR] 'dependencies.dependency.version' for io.quarkus:quarkus-smallrye-openapi:jar is missing. @ line 43, column 21
[2021-12-13T05:28:42.455Z] [INFO] [ERROR] 'dependencies.dependency.version' for io.quarkus:quarkus-junit5:jar is missing. @ line 49, column 21
[2021-12-13T05:28:42.455Z] [INFO] [ERROR] 'dependencies.dependency.version' for io.rest-assured:rest-assured:jar is missing. @ line 54, column 21
[2021-12-13T05:28:42.455Z] [INFO]  @ 
[2021-12-13T05:28:42.455Z] [INFO] [ERROR] The build could not read 1 project -> [Help 1]
[2021-12-13T05:28:42.455Z] [INFO] [ERROR]   
[2021-12-13T05:28:42.455Z] [INFO] [ERROR]   The project org.kie.kogito:integration-tests-kogito-plugin-it:1.11.2-SNAPSHOT (/home/jenkins/workspace/KIE/kogito/1.11.x/nightly/kogito-quarkus-2.2/kogito-runtimes/integration-tests/integration-tests-kogito-plugin/target/it/integration-tests-kogito-plugin-it/pom.xml) has 6 errors
[2021-12-13T05:28:42.455Z] [INFO] [ERROR]     Non-resolvable import POM: Could not find artifact io.quarkus:quarkus-bom:pom:999-SNAPSHOT in mirror-central (https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/) @ org.kie.kogito:kogito-quarkus-bom:1.11.2-SNAPSHOT, /home/jenkins/workspace/KIE/kogito/1.11.x/nightly/kogito-quarkus-2.2/kogito-runtimes/integration-tests/integration-tests-kogito-plugin/target/local-repo/org/kie/kogito/kogito-quarkus-bom/1.11.2-SNAPSHOT/kogito-quarkus-bom-1.11.2-SNAPSHOT.pom, line 21, column 19 -> [Help 2]
[2021-12-13T05:28:42.455Z] [INFO] [ERROR]     'dependencies.dependency.version' for io.quarkus:quarkus-resteasy:jar is missing. @ line 35, column 21
[2021-12-13T05:28:42.455Z] [INFO] [ERROR]     'dependencies.dependency.version' for org.kie.kogito:kogito-quarkus:jar is missing. @ line 39, column 21
[2021-12-13T05:28:42.456Z] [INFO] [ERROR]     'dependencies.dependency.version' for io.quarkus:quarkus-smallrye-openapi:jar is missing. @ line 43, column 21
[2021-12-13T05:28:42.456Z] [INFO] [ERROR]     'dependencies.dependency.version' for io.quarkus:quarkus-junit5:jar is missing. @ line 49, column 21
[2021-12-13T05:28:42.456Z] [INFO] [ERROR]     'dependencies.dependency.version' for io.rest-assured:rest-assured:jar is missing. @ line 54, column 21
[2021-12-13T05:28:42.456Z] [INFO] [ERROR] 
[2021-12-13T05:28:42.456Z] [INFO] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[2021-12-13T05:28:42.456Z] [INFO] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
[2021-12-13T05:28:42.456Z] [INFO] [ERROR] 
[2021-12-13T05:28:42.456Z] [INFO] [ERROR] For more information about the errors and possible solutions, please read the following articles:
[2021-12-13T05:28:42.456Z] [INFO] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[2021-12-13T05:28:42.456Z] [INFO] [ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
[2021-12-13T05:28:42.456Z] [INFO]   The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/1.11.x/nightly/kogito-quarkus-2.2/kogito-runtimes/integration-tests/integration-tests-kogito-plugin/target/it/integration-tests-kogito-plugin-it/build.log for details.
[2021-12-13T05:28:42.456Z] [INFO]           integration-tests-kogito-plugin-it/pom.xml ....... FAILED (3.1 s)
[2021-12-13T05:28:42.456Z] [INFO] -------------------------------------------------
[2021-12-13T05:28:42.456Z] [INFO] Build Summary:
[2021-12-13T05:28:42.456Z] [INFO]   Passed: 0, Failed: 1, Errors: 0, Skipped: 0
[2021-12-13T05:28:42.456Z] [INFO] -------------------------------------------------
```

to
```
[2021-12-13T13:43:55.201Z] [INFO] [INFO] ---------< org.kie.kogito:integration-tests-kogito-plugin-it >----------
[2021-12-13T13:43:55.201Z] [INFO] [INFO] Building integration-tests-kogito-plugin-it 1.11.2-SNAPSHOT
[2021-12-13T13:43:55.201Z] [INFO] [INFO] --------------------------------[ jar ]---------------------------------
[2021-12-13T13:43:59.496Z] [INFO] [INFO] ------------------------------------------------------------------------
[2021-12-13T13:43:59.496Z] [INFO] [INFO] BUILD FAILURE
[2021-12-13T13:43:59.496Z] [INFO] [INFO] ------------------------------------------------------------------------
[2021-12-13T13:43:59.496Z] [INFO] [INFO] Total time:  5.326 s
[2021-12-13T13:43:59.496Z] [INFO] [INFO] Finished at: 2021-12-13T08:43:58-05:00
[2021-12-13T13:43:59.496Z] [INFO] [INFO] ------------------------------------------------------------------------
[2021-12-13T13:43:59.496Z] [INFO] [ERROR] Failed to execute goal on project integration-tests-kogito-plugin-it: Could not resolve dependencies for project org.kie.kogito:integration-tests-kogito-plugin-it:jar:1.11.2-SNAPSHOT: Failed to collect dependencies at io.quarkus:quarkus-resteasy:jar:999-SNAPSHOT -> io.quarkus:quarkus-vertx-http:jar:999-SNAPSHOT -> io.quarkus:quarkus-core:jar:999-SNAPSHOT -> io.quarkus:quarkus-bootstrap-runner:jar:999-SNAPSHOT: Failed to read artifact descriptor for io.quarkus:quarkus-bootstrap-runner:jar:999-SNAPSHOT: Could not find artifact io.quarkus:quarkus-bootstrap-bom:pom:999-SNAPSHOT -> [Help 1]
```

**Comment by tarilabs** [comment]
jenkins run lts

**Comment by tarilabs** [comment]
jenkins run lts

**Comment by tarilabs** [comment]
jenkins run lts

**Comment by tarilabs** [comment]
well, the error changed again, now to:
```
[2021-12-13T17:07:43.688Z] [INFO] [INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ integration-tests-kogito-plugin-it ---
[2021-12-13T17:07:46.998Z] [INFO] [INFO] 
[2021-12-13T17:07:46.998Z] [INFO] [INFO] -------------------------------------------------------
[2021-12-13T17:07:46.998Z] [INFO] [INFO]  T E S T S
[2021-12-13T17:07:46.998Z] [INFO] [INFO] -------------------------------------------------------
[2021-12-13T17:07:47.926Z] [INFO] [INFO] Running org.acme.travels.ManagementAddOnTest
[2021-12-13T17:07:52.122Z] [INFO] Downloading from mirror-central: https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/org/jsoup/jsoup/1.14.2/jsoup-1.14.2.pom
[2021-12-13T17:07:52.122Z] [INFO] Downloaded from mirror-central: https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/org/jsoup/jsoup/1.14.2/jsoup-1.14.2.pom (12 kB at 32 kB/s)
[2021-12-13T17:07:52.122Z] [INFO] [ERROR] Tests run: 4, Failures: 0, Errors: 1, Skipped: 3, Time elapsed: 3.692 s <<< FAILURE! - in org.acme.travels.ManagementAddOnTest
[2021-12-13T17:07:52.122Z] [INFO] [ERROR] org.acme.travels.ManagementAddOnTest.testAbortProcessInstance  Time elapsed: 0.008 s  <<< ERROR!
[2021-12-13T17:07:52.122Z] [INFO] java.lang.RuntimeException: io.quarkus.bootstrap.BootstrapException: Failed to create the application model for org.kie.kogito:integration-tests-kogito-plugin-it::jar:1.11.2-SNAPSHOT
[2021-12-13T17:07:52.122Z] [INFO] Caused by: io.quarkus.bootstrap.BootstrapException: Failed to create the application model for org.kie.kogito:integration-tests-kogito-plugin-it::jar:1.11.2-SNAPSHOT
[2021-12-13T17:07:52.122Z] [INFO] Caused by: io.quarkus.bootstrap.resolver.AppModelResolverException: Failed to inject extension deployment dependencies for org.kie.kogito:integration-tests-kogito-plugin-it:jar:1.11.2-SNAPSHOT
[2021-12-13T17:07:52.122Z] [INFO] Caused by: io.quarkus.bootstrap.BootstrapDependencyProcessingException: Quarkus extension deployment artifact io.quarkus:quarkus-smallrye-openapi-deployment:jar:999-SNAPSHOT does not appear to depend on the corresponding runtime artifact io.quarkus:quarkus-smallrye-openapi:jar:999-SNAPSHOT
[2021-12-13T17:07:52.122Z] [INFO] 
```

I guess in short this idea is not viable.
If you have any further comment @jstastny-cz feel free to comment, but I guess I'm going to close this tentative PR based on this investigation.

**Pull request closed without merging**
