### PR TITLE
KOGITO-6606 KOGITO-6446 Produce event listener before starting Data I…

### PR DESCRIPTION
**Pull request by cristianonicolai**
…ndex

### CODE REVIEW

**Review by pefernan — APPROVED** [review]
+1 thanks @cristianonicolai

**Review by nmirasch — APPROVED** [review]

**Review by radtriste — APPROVED** [review]

**Comment by cristianonicolai** [comment]
Jenkins rerun kogito-examples tests

**Comment by cristianonicolai** [comment]
Jenkins rerun kogito-apps tests

**Comment by nmirasch** [comment]
Jenkins rerun kogito-examples tests

**Pull request merged**
