### PR TITLE
KOGITO-4945 - Unify Testcontainers usage

### PR DESCRIPTION
**Pull request by cristianonicolai**
Assembly:
- https://github.com/kiegroup/kogito-runtimes/pull/1257
- https://github.com/kiegroup/kogito-apps/pull/779
- https://github.com/kiegroup/kogito-examples/pull/664

### CODE REVIEW

**Review by manstis — APPROVED** [review]

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Review by radtriste — APPROVED** [review]

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Review by danielezonca — APPROVED** [review]
Thanks for the PR

**Comment by danielezonca** [comment]
Timeout on example but 
https://github.com/kiegroup/kogito-examples/pull/664
is green so I think we can merge

**Pull request merged**
