### PR TITLE
KOGITO-4129 - Build native kogito-apps

### PR DESCRIPTION
**Pull request by r00ta**
JIRA: https://issues.redhat.com/browse/KOGITO-4129

This PR aims to build native kogito-apps in the pipelines.

Related PR on kogito-apps: https://github.com/kiegroup/kogito-apps/pull/607 
 
Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.md)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by r00ta** [comment]
Hi @radtriste , this PR aims to build `kogito-apps` with the native profile as well. In particular, the new kogito app `jitexecutor` is intended to be used mainly in native mode. 

In case some of the apps should not be built in native mode, I think we should simply remove the native build part in the respective poms

**Comment by r00ta** [comment]
Jenkins retest this please

**Comment by radtriste** [comment]
@r00ta I guess we should have a specific `native` profile with only compatible apps, like we have in examples: https://github.com/kiegroup/kogito-examples/blob/master/pom.xml#L219

**Comment by r00ta** [comment]
> @r00ta I guess we should have a specific `native` profile with only compatible apps, like we have in examples: https://github.com/kiegroup/kogito-examples/blob/master/pom.xml#L219

Hi @radtriste , I've updated the main kogito-apps pom with such strategy. The PR is here https://github.com/kiegroup/kogito-apps/pull/607 . Let me know wdyt

**Review by radtriste — APPROVED** [review]
Can be merged once https://github.com/kiegroup/kogito-apps/pull/607 is merged

**Pull request merged**
