### PR TITLE
[1.11.x][KOGITO-5789] use activating property for kogito-quarkus-test-list

### PR DESCRIPTION
**Pull request by jstastny-cz**
Cherry-pick of #1584 .
https://issues.redhat.com/browse/KOGITO-5789

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Run all builds</b>  
  Please add comment: <b>Jenkins retest this</b>

* <b>Run (or rerun) specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [runtimes|optaplanner|apps|examples] tests</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Run (or rerun) LTS specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [runtimes|optaplanner|apps|examples] LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

* <b>Run (or rerun) native specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [runtimes|optaplanner|apps|examples] native</b>

* <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

### CODE REVIEW

**Comment by jstastny-cz** [comment]
Jenkins rerun examples tests

**Review by evacchi — CHANGES_REQUESTED** [review]
could you exclude the gradle integration test as well? that was faulty on https://github.com/quarkusio/quarkus-platform/pull/308

**Comment by jstastny-cz** [comment]
That one should not be included after this change, or did I overlook? Basically it is exluded unless there is `<quarkus.test.list.include>true</quarkus.test.list.include>` property definition in the test module.

**Comment by evacchi** [comment]
ah, I am not very knowledgeable about how that works, so you may be right

**Review by ricardozanini — APPROVED** [review]
Much better! Thanks Jan!

**Review by cristianonicolai — APPROVED** [review]

**Comment by jstastny-cz** [comment]
Is this still worth having in 1.11.x? @evacchi @danielezonca

**Comment by ricardozanini** [comment]
If it's a requirement only for the integration tests with the Quarkus platform, I don't think so.

**Comment by jstastny-cz** [comment]
Yes, just that. It fixes the problem of test-list pointing at test-jars that were not actually built (due to modules excluded using `-Dproductized` or `-DexcludeITModules`). Without this change we have test-list containing non-existing test-jar GAVs (which has been hopefully worked-around or we might have issues in quarkus-platform prod build).

**Comment by AntStephenson** [comment]
Hi @jstastny-cz - thanks for the PR, @ricardozanini it turns out we need this on the prod side as the productized Quarkus Platform build fails when using a productized version of kogito artifacts, the test list contains tests that we don't productize

**Review by mareknovotny — APPROVED** [review]

**Pull request merged**
