### PR TITLE
BXMSPROD-1540 composite actions centralized github actions

### PR DESCRIPTION
**Pull request by radtriste**
let's try again https://github.com/kiegroup/kogito-runtimes/pull/1692 and find what is the problem with the runtimes build.

We need to know that this problem does not happen on other repositories but only on runtimes.
Noticeable change: Use https://github.com/s4u/setup-maven-action but this is for all.

Checkout hierarchy:
- https://github.com/s4u/setup-maven-action checkout kogito-runtimes in `/home/runner/work/kogito-runtimes/kogito-runtimes`
- build-chain checkout drools in `/home/runner/work/kogito-runtimes/kogito-runtimes/kiegroup_drools`
- build-chain checkout kogito-runtimes in `/home/runner/work/kogito-runtimes/kogito-runtimes/kiegroup_kogito_runtimes`

### CODE REVIEW

**Comment by radtriste** [comment]
@Ginxo so it seems indeed the bug was introduced with the use of https://github.com/s4u/setup-maven-action
(see kogito-runtimes GHA build)

**Comment by radtriste** [comment]
@Ginxo should we fallback the composite action and use the "old style" maven/java installation ?

**Comment by Ginxo** [comment]
@radtriste I agree (just for the java/maven step) adding a comment there explaining the reason to keep it. ok?

**Comment by radtriste** [comment]
updated https://github.com/radtriste/kogito-pipelines/blob/test_composite/.ci/actions/maven/action.yml, let's what the kogito-runtimes check is doing :)

**Comment by radtriste** [comment]
Follow-up on https://github.com/kiegroup/kogito-runtimes/pull/1834

**Pull request closed without merging**
