### PR TITLE
Upgrade xstream to 1.4.16

### PR DESCRIPTION
**Pull request by mareknovotny**
Details at https://app.snyk.io/vuln/SNYK-JAVA-COMTHOUGHTWORKSXSTREAM-1088337

Please make sure that your PR meets the following requirements:

- [X ] You have read the [contributors guide](CONTRIBUTING.md)
- [X] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/master/kogito-build/kogito-ide-config)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [X] Pull Request contains description of the issue
- [X] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

* <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

### CODE REVIEW

**Comment by mareknovotny** [comment]
jenkins retest this

**Comment by mareknovotny** [comment]
@danielezonca  we changed examples groupId few days ago and it seems the GA build for Examples shows the problem to find that new groupId snapshot kogito-examples parent pom.xml.

**Comment by danielezonca** [comment]
> @danielezonca we changed examples groupId few days ago and it seems the GA build for Examples shows the problem to find that new groupId snapshot kogito-examples parent pom.xml.

Nope, the problem was that one project in examples repo has not been updated. I fixed it yesterday
https://github.com/kiegroup/kogito-examples/pull/699
Now started the example build again, let's see 🤞

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
so the only failure is from not stsarted testcontainers docker image 
```
org.testcontainers.containers.ContainerLaunchException: Container startup failed
Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=library/mongo:4.0.10, imagePullPolicy=DefaultPullPolicy())
Caused by: org.testcontainers.containers.ContainerFetchException: Failed to get Docker client for library/mongo:4.0.10
Caused by: com.github.dockerjava.api.exception.DockerClientException: Could not pull image: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

I thought we have cached docker images in our internal Nexus?

**Comment by danielezonca** [comment]
> so the only failure is from not started testcontainers docker image
> 
> ```
> org.testcontainers.containers.ContainerLaunchException: Container startup failed
> Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=library/mongo:4.0.10, imagePullPolicy=DefaultPullPolicy())
> Caused by: org.testcontainers.containers.ContainerFetchException: Failed to get Docker client for library/mongo:4.0.10
> Caused by: com.github.dockerjava.api.exception.DockerClientException: Could not pull image: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
> ```
> 
> I thought we have cached docker images in our internal Nexus?

Yes it should 🤔 
@cristianonicolai 
Do we need to add a substitution class or similar for mongo? Isn't it automatic?

**Pull request merged**
