### PR TITLE
KOGITO-4002  Move process serialization to process-serialization-protobuf

### PR DESCRIPTION
**Pull request by evacchi**
https://issues.redhat.com/browse/KOGITO-4002

serialization depends on drools (v7) and is part of jbpm-flow.
refactor it to an optional module so that the v7 dependency is scoped to that module

-----

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.md)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by evacchi** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
@evacchi should we also take the opportunity to drop _jbpm_ from the new artifact name?

**Comment by evacchi** [comment]
@cristianonicolai as you wish. `process-` ?

**Comment by cristianonicolai** [comment]
+1, process- sounds good.

**Review by tiagodolphine — APPROVED** [review]

**Review by cristianonicolai — APPROVED** [review]

**Review by MarianMacik — APPROVED** [review]

**Comment by evacchi** [comment]
jenkins please retest this

**Comment by evacchi** [comment]
jenkins please retest this

**Comment by evacchi** [comment]
jenkins please retest this

**Pull request merged**
