### PR TITLE
Remove duplicated version.archetype.plugin property

### PR DESCRIPTION
**Pull request by jomarko**
The same file *kogito-build-parent/pom.xml* contained the same property twice.

### CODE REVIEW

**Comment by jomarko** [comment]
Jenkins please retest this

**Comment by jomarko** [comment]
```

11:14:11,714 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project process-optaplanner-springboot: There are test failures.

11:14:11,714 [ERROR] 

11:14:11,714 [ERROR] Please refer to /home/jenkins/workspace/KIE/kogito/pullrequest/kogito-runtimes/kogito-examples/process-optaplanner-springboot/target/surefire-reports for the individual test results.
```

**Comment by jomarko** [comment]
Jenkins please retest this

**Review by danielezonca — APPROVED** [review]
Thanks for the PR 👍

**Comment by jomarko** [comment]
Jenkins please retest this

**Comment by jomarko** [comment]
@danielezonca could we please merge?

**Pull request merged**
