### PR TITLE
Add org.kie.kogito to scanBasePackages since Kogito handlers are added there

### PR DESCRIPTION
**Pull request by Christopher-Chianelli**
When I created an example using the kogito-spring-boot archetype, I noticed
the handlers field of my BPMN process was null. After some investigating,
I learned that scanBasePackages was only checking for my groupId (in
fact, it added my groupId twice!). However, the kogito handlers
are placed in org.kie.kogito.handlers, so it was not picking up the
service handlers!

This add org.kie.kogito.** to the maven archetype so it can detect
the package.

Alternatives:

- Move Handlers to the package of the service they are a proxy of

### CODE REVIEW

**Comment by evacchi** [comment]
is this a duplicate of #371 ?

**Comment by Christopher-Chianelli** [comment]
Sorry, didn't see your reply.  Looks different; this issue have to do with generated classes from Kogito for BPMN diagrams.

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by r00ta** [comment]
Hi @Christopher-Chianelli   , can we close this PR or is something still to be done? Thanks

**Comment by Christopher-Chianelli** [comment]
@r00ta it been a long while since I checked/used this code. The `http**` added to the scan might of fixed the same issue that this PR fixes (depending on if handlers moved to a http package). IIRC, the issue was handlers for events was not being registered correctly. A way to test it is to see if replacing https://github.com/kiegroup/kogito-examples/blob/b4c398cf8130c1f899a7e7103a2e5c477dca5bd0/process-optaplanner-springboot/src/main/java/org/kie/kogito/examples/FlightSeatingApplication.java#L21 with the current scan package causes no issues. If so, the PR can be safely closed.

**Comment by Christopher-Chianelli** [comment]
@r00ta PR still needed; I get test failures for missing `Application` bean w/o changes.

**Comment by domhanak** [comment]
Closing as stale/inactive. Please reopen if required.

**Pull request closed without merging**
