### PR TITLE
KOGITO-3984 SpringBoot application generated by archetype missing htt…

### PR DESCRIPTION
**Pull request by sutaakar**
…p package scan

Signed-off-by: Karel Suta <ksuta@redhat.com>

https://issues.redhat.com/browse/KOGITO-3984

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.md)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by sutaakar** [comment]
Related to https://github.com/kiegroup/kogito-runtimes/pull/891

**Review by ricardozanini — APPROVED** [review]
@tiagodolphine can you take a look, please? Seems related to the migration we did from RestEasy :+1: 

It's blocking us on BDD, see: https://jenkins-kogito-tools.apps.kogito-cloud.automation.rhmw.io/job/kogito/job/kogito-cloud-operator-PR-check/233/artifact/test/logs/smoke/error%20-%20Deploy%20.dmn%20source%20files%20with%20CLI%20using%20runtime%20springboot%20-%20jenkins-cucumber-54a4/test-run.log

```json
{"level":"warn","T":"2020-12-07T21:02:41.113Z","logger":"jenkins-cucumber-54a4","msg":"Request not expected. Got status code 404"}
{"level":"error","T":"2020-12-07T21:02:42.116Z","logger":"jenkins-cucumber-54a4","msg":"Error in step 'HTTP POST request on service \"dmn-springboot-example\" is successful within 2 minutes with path \"Traffic Violation\" and body:': Timeout waiting for HTTP POST request on path 'Traffic Violation' to be successful"}
{"level":"error","T":"2020-12-07T21:02:42.316Z","logger":"jenkins-cucumber-54a4","msg":"Error in scenario 'Deploy .dmn source files with CLI using runtime springboot': Timeout waiting for HTTP POST request on path 'Traffic Violation' to be successful"}
```

**Review by MarianMacik — APPROVED** [review]
It seems it slipped our attention in the PR.

Here is the old config for the archetype:
https://github.com/kiegroup/kogito-runtimes/pull/891/files#diff-b130c673dab9b859b15296e30b677cb8f8d124718fa220797987c2b6e7774e24L6

Here is the new config, which was applied in the integration tests:
https://github.com/kiegroup/kogito-runtimes/pull/891/files#diff-c4573d5ceb9c7bd366591e69776f755f1bf4c02157edfbd91e1fb58e09004caeR22

Thanks guys!

**Review by cristianonicolai — APPROVED** [review]

**Comment by sutaakar** [comment]
jenkins retest this

**Review by tiagodolphine — APPROVED** [review]
LGTM, in fact the package `http**` is generated for DMN endpoints, I needed to fix it on the examples to insert on the scanBasepackage as well, but missed the archetype. Thanks.
@tarilabs FYI

**Comment by ricardozanini** [comment]
@cristianonicolai can we merge this?

**Pull request merged**
