### PR TITLE
[1.0.x] KOGITO-3827  Bump to Quarkus 1.10.0.CR1

### PR DESCRIPTION
**Pull request by evacchi**
[KOGITO-3827](https://issues.redhat.com/browse/KOGITO-3827)

- https://github.com/kiegroup/kogito-runtimes/pull/884
- https://github.com/kiegroup/kogito-examples/pull/450

----

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.md)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by evacchi** [comment]
@ricardozanini FYI I was bumping kubernetes-client to 4.12.0 -- like Quarkus -- but some API is breaking. I tried to fix manually by adding a fake String name (the new arg) but I think the tests are then failing -- you probably know better how to fix that. For now I am reverting to 4.8 

Error was:

```
[ERROR] /home/evacchi/Devel/redhat/pr/submarine/submarine-runtimes/kogito-cloud-services/kogito-cloud-kubernetes-client/src/test/java/org/kie/kogito/cloud/kubernetes/client/MockKubernetesServerSupport.java:[116,56] no suitable constructor found for ServicePort(java.lang.String,int,int,java.lang.String,io.fabric8.kubernetes.api.model.IntOrString)
    constructor io.fabric8.kubernetes.api.model.ServicePort.ServicePort() is not applicable
      (actual and formal argument lists differ in length)
    constructor io.fabric8.kubernetes.api.model.ServicePort.ServicePort(java.lang.String,java.lang.String,java.lang.Integer,java.lang.Integer,java.lang.String,io.fabric8.kubernetes.api.model.IntOrString) is not applicable
      (actual and formal argument lists differ in length)

**Comment by ricardozanini** [comment]
@evacchi can you please open a JIRA for me following up this one? I'll try to take a look at it today. Many thanks!

**Comment by evacchi** [comment]
there is also this which.... ???

```
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] BUILD FAILURE
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] Total time:  4.564 s
[INFO] [INFO] Finished at: 2020-11-11T08:48:03-05:00
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [ERROR] Failed to execute goal on project integration-tests-springboot-it: Could not resolve dependencies for project org.kie.kogito:integration-tests-springboot-it:jar:1.0.0-SNAPSHOT: The following artifacts could not be resolved: com.github.java-json-tools:json-schema-validator:jar:2.2.14, com.sun.xml.bind:jaxb-impl:jar:2.3.3: Could not find artifact com.github.java-json-tools:json-schema-validator:jar:2.2.14 in local.mirror (file:///home/jenkins/.m2/repository) -> [Help 1]
[INFO] [ERROR] 
[INFO] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[INFO] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
[INFO] [ERROR] 
[INFO] [ERROR] For more information about the errors and possible solutions, please read the following articles:
[INFO] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[INFO]   The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/ghprb-webhooks/kogito-runtimes/kogito-runtimes/integration-tests/integration-tests-springboot/target/it/integration-tests-springboot-it/build.log for details.
[INFO]           integration-tests-springboot-it/pom.xml .......... FAILED (5.9 s)

**Comment by evacchi** [comment]
I am disabling the local repo which apparently it is 1) slowing down the build and 2) not necessary for the way we are using this tests?

**Comment by evacchi** [comment]
> Caused by: com.github.dockerjava.api.exception.DockerClientException: Could not pull image: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

**Comment by evacchi** [comment]
jenkins please retest this

**Comment by evacchi** [comment]
I am backing off from some changes and reverting to restassured 4.3.0 since it's only test-scoped and we don't need to align to Quarkus. It seems to be the root cause of some conflicts with sprint boot

**Comment by evacchi** [comment]
restoring testcontainers as well, as it breaks for an API compatibility change apparently

```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
Caused by: java.lang.reflect.InvocationTargetException
Caused by: java.lang.NoSuchMethodError: org.testcontainers.utility.DockerImageName.parse(Ljava/lang/String;)Lorg/testcontainers/utility/DockerImageName;

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by evacchi** [comment]
[last build failed](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/kogito/job/ghprb-webhooks/job/kogito-runtimes/2016/console) but I suspect snapshots are mixed in CI

jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by evacchi** [comment]
jenkins please retest this

**Comment by evacchi** [comment]
jenkins please retest this

**Comment by evacchi** [comment]
jenkins please retest this

**Comment by tiagodolphine** [comment]
jenkins retest this

**Comment by tiagodolphine** [comment]
jenkins retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Review by radtriste — APPROVED** [review]

**Comment by tiagodolphine** [comment]
jenkins retest this

**Review by tiagodolphine — APPROVED** [review]

**Comment by evacchi** [comment]
jenkins retest this

**Comment by radtriste** [comment]
jenkins retest this

**Comment by evacchi** [comment]
jenkins retest this

**Comment by evacchi** [comment]
@radtriste I think it's failing because of this :thinking: 

> Scripts not permitted to use new java.lang.StringBuilder java.lang.String. Administrators can decide whether to approve or reject this signature.

**Comment by radtriste** [comment]
@mbiarnes @Ginxo  Could we accept to use `java.lang.StringBuilder` in Jenkins ? or I can fallback to string computation

**Comment by radtriste** [comment]
jenkins retest this

**Comment by radtriste** [comment]
jenkins retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
greeeeeeeeeeeeeeeeeeen!!!!

**Review by cristianonicolai — APPROVED** [review]

**Pull request merged**
