### PR TITLE
[KOGITO-3972] Make TemplateGenerator use KogitoBuildContext

### PR DESCRIPTION
**Pull request by danielezonca**
https://issues.redhat.com/browse/KOGITO-3972

Details
- Updated `TemaplateGenerator` to use `KogitoBuildContext` instead of `DependencyInjectorAnnotator`
- Removed `ConfigGenerator` and replaced with `ApplicationConfigGenerator` (it was an intermediate step now removed)
- Created `AbstractConfigGenerator` to simplify `*ConfigGenerator` impl
- All `*ConfigGenerator`s now extends `AbstractConfigGenerator`
- Update all `TemplateGenerator` usages to only be used as delegate
- `JavaKogitoBuildContext` for non-DI context (and avoid `null` context)
- `DependencyInjectionAnnotator` reference inside `KogitoBuildContext` to prevent inconsistent configuration (i.e. Quarkus but no DI or Java but with DI)
- Removed all `withDependencyInjectionAnnotator` methods because no more needed
- Created a common `hasDI()` method inside `KogitoBuildContext` and removed all custom `useInjection()` methods

~~To be merged after https://github.com/kiegroup/kogito-runtimes/pull/929~~ Merged

### CODE REVIEW

**Comment by evacchi** [comment]
> Update all TemplateGenerator usages to only be used as delegate

you can probably make it `final` then! I haven't look at the whole PR yet, but looks great. We can probably avoid a few `instanceof` now, but I understand that this is to keep the changes minimal

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by danielezonca** [comment]
> > Update all TemplateGenerator usages to only be used as delegate
> 
> you can probably make it `final` then! I haven't look at the whole PR yet, but looks great. We can probably avoid a few `instanceof` now, but I understand that this is to keep the changes minimal

Done, now `TemplateGenerator` is `final` :)

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by danielezonca** [comment]
jenkins retest this please

**Review by evacchi — APPROVED** [review]

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by danielezonca** [comment]
jenkins retest this please

**Review by MarianMacik — APPROVED** [review]
Looks good to me.

**Pull request merged**
