### PR TITLE
[1.8.x] Setup Jenkins timestamps

### PR DESCRIPTION
**Pull request by radtriste**
cherry-pick: https://github.com/kiegroup/kogito-runtimes/pull/1396

### CODE REVIEW

**Review by danielezonca — APPROVED** [review]

**Comment by radtriste** [comment]
jenkins rerun runtimes test

**Comment by radtriste** [comment]
jenkins rerun examples tests

**Comment by radtriste** [comment]
jenkins rerun runtimes tests

**Comment by radtriste** [comment]
jenkins rerun runtime tests

**Comment by radtriste** [comment]
jenkins rerun runtimes tests

**Pull request merged**
