### PR TITLE
[1.1.x] fix for optaplanner checkout in PR release branch

### PR DESCRIPTION
**Pull request by radtriste**
Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.md)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Review by evacchi — APPROVED** [review]

**Comment by radtriste** [comment]
Jenkins retest this

**Comment by radtriste** [comment]
Jenkins retest this

**Comment by radtriste** [comment]
Jenkins retest this

**Comment by evacchi** [comment]
this seems to be failing at

```
	at org.kie.kogito.jobs.service.resource.JobResourceIT.testForcingCreateExpiredJob(JobResourceIT.java:283)
```

https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/blue/organizations/jenkins/KIE%2Fkogito%2Fghprb-webhooks%2Fkogito-runtimes/detail/kogito-runtimes/2552/tests

which needless to say seems unrelated @tiagodolphine 
I think I'll try and open another PR and see if disabling it "fixes" the problem. No clue on what is wrong though (we haven't even bumped any version yet arrrgh)

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by radtriste** [comment]
jenkins please retest this

**Comment by evacchi** [comment]
jenkins please retest this

**Pull request merged**
