### PR TITLE
KOGITO-4251: fixed version property names according to conventions an…

### PR DESCRIPTION
**Pull request by mareknovotny**
…d sorted them alphabetically
see https://issues.redhat.com/browse/KOGITO-4251

Dependent PRs:

- https://github.com/kiegroup/kogito-apps/pull/639
- https://github.com/kiegroup/kogito-examples/pull/559

Please make sure that your PR meets the following requirements:

- [X] You have read the [contributors guide](CONTRIBUTING.md)
- [X] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/droolsjbpm-build-bootstrap/tree/master/ide-configuration)
- [X] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [X ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [X] Pull Request contains link to the JIRA issue
- [X] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by radtriste** [comment]
just ignore the `BDD tests`

**Comment by radtriste** [comment]
Jenkins retest this

**Comment by radtriste** [comment]
Jenkins retest this

**Comment by radtriste** [comment]
Jenkins retest this

**Comment by radtriste** [comment]
Jenkins retest this

**Comment by mareknovotny** [comment]
jenkins retest this

**Comment by mareknovotny** [comment]
jenkins retest this please

**Review by cristianonicolai — COMMENTED** [review]
@mareknovotny I believe its missing dependency from generated archetypes, such as https://github.com/kiegroup/kogito-runtimes/blob/master/integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/pom.xml#L34

**Comment by mareknovotny** [comment]
> @mareknovotny I believe its missing dependency from generated archetypes, such as https://github.com/kiegroup/kogito-runtimes/blob/master/integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/pom.xml#L34

I have it replaced too https://github.com/mareknovotny/kogito-runtimes/blob/KOGITO-4251/integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/pom.xml#L34, and CI is green so it should be ok

**Comment by mareknovotny** [comment]
I know there are not all version properties replaced outside of kogito-build-parent, but I think the urgent fixes are in parent and we can iteratively fix other places like integration-tests pom.xml where are referenced some of version properties in bad names.

**Comment by mareknovotny** [comment]
jenkins retest this please

**Review by cristianonicolai — APPROVED** [review]

**Comment by mareknovotny** [comment]
jenkins retest this please

**Pull request merged**
