### PR TITLE
KOGITO-3876  Bump to Quarkus 1.10.0.Final

### PR DESCRIPTION
**Pull request by evacchi**
cherry-pick #884 
related https://github.com/kiegroup/kogito-examples/pull/459

### CODE REVIEW

**Comment by evacchi** [comment]
jenkins please retest this

**Comment by evacchi** [comment]
jenkins please retest this

**Comment by evacchi** [comment]
@cristianonicolai @tiagodolphine @radtriste repurposing this PR to also bring in Final, since it is due today anyway

**Review by cristianonicolai — APPROVED** [review]

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by evacchi** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Pull request merged**
