### PR TITLE
KOGITO-4847 Fix local builds for integration tests

### PR DESCRIPTION
**Pull request by jstastny-cz**
[KOGITO-4847](https://issues.redhat.com/browse/KOGITO-4847)
* fixing surefire/filesafe systemProperties to systemPropertyVariables (https://maven.apache.org/surefire/maven-surefire-plugin/examples/system-properties.html, https://maven.apache.org/surefire/maven-failsafe-plugin/examples/system-properties.html)
* moving invoker properties to kogito-build-parent pluginManagement for invoker plugin.
* introducing explicit test dependencies in modules that use invoker to run other maven projects - aggregation of the dependencies need by those projects being invoked.
* Making sure all maven invocations respect `-Dmaven.repo.local=<path>` and `-s <path>/settings.xml` configurations
  * by setting explicitly in surefire/failsafe (for quarkus plugin)
  * by passing directly in code (IT tests for quarkus dev mode which use invoker from java) 

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

* <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

### CODE REVIEW

**Comment by jstastny-cz** [comment]
jenkins retest this

**Comment by danielezonca** [comment]
@jstastny-cz 
Thanks for the PR, I agree with you that the best solution should be to introduce an explicit test dependencies to make maven aware of it.
Please consider also that we run in CI with a specific settings that adds internal nexus url (@radtriste please correct me if I'm wrong) so we should test the fix both locally and via CI

**Comment by jstastny-cz** [comment]
@danielezonca do you mean I should verify something more than the PR check here?
I've verified locally by using both `-Dmaven.repo.local` and `-s settings.xml` and was checking that no kogito-runtimes module was being downloaded from anywhere and that the things that got downloaded were taken from correct remotes and put into correct local repository (This applies especially for invoker builds).

**Comment by radtriste** [comment]
If you want to make sure no snapshot is taken in the PR from the used [settings.xml](https://github.com/kiegroup/kogito-runtimes/blob/master/Jenkinsfile#L251), just add `.withSnapshotsDisabledInSettings()` (taken from [the shared library](https://github.com/kiegroup/jenkins-pipeline-shared-libraries/blob/master/src/org/kie/jenkins/MavenCommand.groovy#L122)) after this [line](https://github.com/kiegroup/kogito-runtimes/blob/master/Jenkinsfile#L251)

**Comment by danielezonca** [comment]
> @danielezonca do you mean I should verify something more than the PR check here?
> I've verified locally by using both `-Dmaven.repo.local` and `-s settings.xml` and was checking that no kogito-runtimes module was being downloaded from anywhere and that the things that got downloaded were taken from correct remotes and put into correct local repository (This applies especially for invoker builds).

I'm mainly referring to run a full build locally with a clean m2 to make sure the new configuration works starting from an empty env.
In the past we got multiple situations with integration tests where it was not working with an empty m2 or without an additional settings available only on jenkins

**Comment by jstastny-cz** [comment]
There are issues when there's no settings.xml in user's ~/.m2/settings.xml - cause it returns by default in `${session.request.userSettingsFile.path}` looking if can be handled in problematic cases.

**Comment by jstastny-cz** [comment]
@danielezonca understood. That's actual how I was checking that previously.

Now I am running other checks to make sure:
* that nothing breaks with no settings.xml neither provided through -s, nor present in ~/.m2/
* that build works with disabled snapshot downloads

**Comment by radtriste** [comment]
Tested latest change locally by changing the version 
```
$ mvn -N -e -Dfull -DallowSnapshots=false -DgenerateBackupPoms=false -DnewVersion=544.5.0-SNAPSHOT versions:set
$ mvn clean install -fae
```
I get the same problem as in the latest run of PR check:
```
[INFO] --- maven-invoker-plugin:3.2.1:run (integration-test) @ integration-tests-springboot ---
[INFO] Building: integration-tests-springboot-it/pom.xml
[INFO] [INFO] Scanning for projects...
[INFO] [INFO] 
[INFO] [INFO] -----------< org.kie.kogito:integration-tests-springboot-it >-----------
[INFO] [INFO] Building integration-tests-springboot-it 544.5.0-SNAPSHOT
[INFO] [INFO] --------------------------------[ jar ]---------------------------------
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] BUILD FAILURE
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] Total time:  04:52 min
[INFO] [INFO] Finished at: 2021-04-02T11:35:31+02:00
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [ERROR] Failed to execute goal on project integration-tests-springboot-it: Could not resolve dependencies for project org.kie.kogito:integration-tests-springboot-it:jar:544.5.0-SNAPSHOT: Failed to collect dependencies at org.kie.kogito:kogito-test-utils:jar:544.5.0-SNAPSHOT: Failed to read artifact descriptor for org.kie.kogito:kogito-test-utils:jar:544.5.0-SNAPSHOT: Could not find artifact org.kie.kogito:kogito-quarkus-bom:pom:544.5.0-SNAPSHOT in jboss-public-repository-group (https://repository.jboss.org/nexus/content/groups/public/) -> [Help 1]
[INFO] [ERROR] 
[INFO] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[INFO] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
[INFO] [ERROR] 
[INFO] [ERROR] For more information about the errors and possible solutions, please read the following articles:
[INFO] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[INFO]   The build exited with code 1. See /home/tradisso/projects/kiegroup/kogito-runtimes/integration-tests/integration-tests-springboot/target/it/integration-tests-springboot-it/build.log for details.
[INFO]           integration-tests-springboot-it/pom.xml .......... FAILED (294.3 s)
[INFO] Building: integration-tests-springboot-kafka-it/pom.xml
[INFO] [INFO] Scanning for projects...
[INFO] [INFO] 
[INFO] [INFO] --------< org.kie.kogito:integration-tests-springboot-kakfa-it >--------
[INFO] [INFO] Building integration-tests-springboot-kakfa-it 544.5.0-SNAPSHOT
[INFO] [INFO] --------------------------------[ jar ]---------------------------------
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] BUILD FAILURE
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] Total time:  21.735 s
[INFO] [INFO] Finished at: 2021-04-02T11:35:56+02:00
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [ERROR] Failed to execute goal on project integration-tests-springboot-kakfa-it: Could not resolve dependencies for project org.kie.kogito:integration-tests-springboot-kakfa-it:jar:544.5.0-SNAPSHOT: Failed to collect dependencies at org.kie.kogito:kogito-test-utils:jar:544.5.0-SNAPSHOT: Failed to read artifact descriptor for org.kie.kogito:kogito-test-utils:jar:544.5.0-SNAPSHOT: Failure to find org.kie.kogito:kogito-quarkus-bom:pom:544.5.0-SNAPSHOT in https://repository.jboss.org/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of jboss-public-repository-group has elapsed or updates are forced -> [Help 1]
[INFO] [ERROR] 
[INFO] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[INFO] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
[INFO] [ERROR] 
[INFO] [ERROR] For more information about the errors and possible solutions, please read the following articles:
[INFO] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[INFO]   The build exited with code 1. See /home/tradisso/projects/kiegroup/kogito-runtimes/integration-tests/integration-tests-springboot/target/it/integration-tests-springboot-kafka-it/build.log for details.
[INFO]           integration-tests-springboot-kafka-it/pom.xml .... FAILED (25.3 s)
[INFO] -------------------------------------------------
[INFO] Build Summary:
[INFO]   Passed: 0, Failed: 2, Errors: 0, Skipped: 0
[INFO] -------------------------------------------------
[ERROR] The following builds failed:
[ERROR] *  integration-tests-springboot-it/pom.xml
[ERROR] *  integration-tests-springboot-kafka-it/pom.xml
[INFO] -------------------------------------------------
```

**Comment by jstastny-cz** [comment]
I've added an explicit dep on the kogito-quarkus-bom, but here I am actually not sure, why this would be needed, I expected that kogito-test-utils when transitively depending on kogito-quarkus-bom, would make invoker to install that into the local repository even without explicit dep.
I think we're not seeing `useLocalRepository` invoker option to be working here, I am struggling to understand why is that.

**Comment by jstastny-cz** [comment]
jenkins retest this

**Comment by radtriste** [comment]
Jenkins test this

**Comment by jstastny-cz** [comment]
jenkins retest this

**Review by evacchi — APPROVED** [review]

**Comment by evacchi** [comment]
@danielezonca @radtriste does this look fine to you guys?

**Comment by radtriste** [comment]
Jenkins retest this

**Comment by radtriste** [comment]
Jenkins retest this

**Comment by jstastny-cz** [comment]
Failure in `Building Kogito :: Quarkus Extension :: Integration Tests (Maven devmode) 2.0.0-SNAPSHOT [74/165]`
That one is using Invoker directly from Java, no output is present in logs.

**Comment by jstastny-cz** [comment]
jenkins retest this

**Comment by radtriste** [comment]
seems there is a formatting problem of https://github.com/kiegroup/kogito-runtimes/pull/1188/files#diff-1603c5d788d2c2de347ab63964e329821b33c2341e1c9a8eee7bdb3c5b991422 ...

**Comment by jstastny-cz** [comment]
jenkins retest this

**Comment by radtriste** [comment]
jenkins retest this

**Comment by radtriste** [comment]
test failure is linked to https://kie.zulipchat.com/#narrow/stream/232676-kogito/topic/Task.20assign.20broken.20on.20CI.3F

**Comment by radtriste** [comment]
jenkins retest this

**Comment by radtriste** [comment]
jenkins retest this

**Comment by radtriste** [comment]
jenkins retest this

**Comment by radtriste** [comment]
jenkins retest this

**Comment by jstastny-cz** [comment]
jenkins retest this

**Review by radtriste — APPROVED** [review]

**Comment by radtriste** [comment]
are we good to merge ?

**Comment by jstastny-cz** [comment]
Yes, this should be it.

**Pull request merged**
