### PR TITLE
[KOGITO-5699] Inject object mapper for events addon

### PR DESCRIPTION
**Pull request by fjtirado**
https://issues.redhat.com/browse/KOGITO-5699

### CODE REVIEW

**Review by ricardozanini — APPROVED** [review]
Nice! I think with [KOGITO-5618](https://issues.redhat.com/browse/KOGITO-5618) we can work on having an "ObjectMapperProvider" that works for both runtimes and can be a central point for the mapper instance and configuration.

**Review by danielezonca — APPROVED** [review]

**Comment by fjtirado** [comment]
jenkins run apps tests

**Comment by fjtirado** [comment]
jenkins run optaplanner tests

**Comment by fjtirado** [comment]
jenkins run examples tests

**Comment by fjtirado** [comment]
jenkins run examples tests

**Pull request merged**
