### PR TITLE
KOGITO-4158 Setup native PR checks

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/KOGITO-4158

Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/127
- https://github.com/kiegroup/kogito-runtimes/pull/1120
- https://github.com/kiegroup/optaplanner/pull/1204
- https://github.com/kiegroup/kogito-apps/pull/699
- https://github.com/kiegroup/kogito-examples/pull/608

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.md)
- [x] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/master/kogito-ide-config)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by radtriste** [comment]
Jenkins run native

**Comment by radtriste** [comment]
Jenkins run native

**Comment by radtriste** [comment]
Jenkins run native

**Comment by radtriste** [comment]
Jenkins run native

**Comment by radtriste** [comment]
Jenkins run LTS

**Comment by radtriste** [comment]
Jenkins run native

**Comment by radtriste** [comment]
Jenkins retest this

**Comment by radtriste** [comment]
Jenkins test LTS

**Comment by radtriste** [comment]
Jenkins run LTS

**Comment by radtriste** [comment]
Jenkins run native

**Review by evacchi — APPROVED** [review]

**Comment by radtriste** [comment]
Jenkins run LTS

**Review by msmagnanijr — APPROVED** [review]
lgtm

**Comment by radtriste** [comment]
native check error is not related to the PR jenkinsfile itself but to the code.

**Pull request merged**
