### PR TITLE
[1.5.x] KOGITO-5140 defer expansion of properties with versions in quarkus archetypes

### PR DESCRIPTION
**Pull request by jstastny-cz**
Jira: https://issues.redhat.com/browse/KOGITO-5140
Cherry-pick of #1317 .

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

* <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

### CODE REVIEW

**Comment by jstastny-cz** [comment]
`Kogito :: Cloud :: Work Items` failed.

jenkins retest this

**Review by AntStephenson — APPROVED** [review]

**Review by danielezonca — COMMENTED** [review]
@jstastny-cz 
Can you please apply the same changes to `kogito-quarkus-dm-archetype` and `kogito-springboot-dm-archetype`

**Comment by jstastny-cz** [comment]
@danielezonca the changes here are in both quarkus archetypes. Spring Boot ones do not suffer from this issue, unless I missed something.

**Comment by jstastny-cz** [comment]
`Kogito :: Integration Tests :: SpringBoot` this time.

jenkins retest this

**Comment by danielezonca** [comment]
You are right, nevermind 👍

**Review by danielezonca — APPROVED** [review]

**Comment by jstastny-cz** [comment]
jenkins retest this

**Comment by AntStephenson** [comment]
Jenkins retest this

**Comment by mareknovotny** [comment]
I feel like the tests are always randomly failing and we saw in past executions that all tests which failed before now are passing without any change of code. so I am merging it now.

**Pull request merged**
