### PR TITLE
KOGITO-7961 - Add process events addon to productized profile

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by cristianonicolai** [comment]
jenkins run quarkus-lts

**Review by radtriste — APPROVED** [review]

**Review by ricardozanini — APPROVED** [review]

**Comment by ricardozanini** [comment]
Do we need backport?

**Comment by cristianonicolai** [comment]
@ricardozanini I guess not at this point

**Comment by cristianonicolai** [comment]
issue on kogito-examples github actions is not related and getting fixed in https://github.com/kiegroup/kogito-pipelines/pull/614

**Pull request merged**
