### PR TITLE
KOGITO-1781: set modelName and modelNamespace in DMNResult

### PR DESCRIPTION
**Pull request by r00ta**
Hi, 

For accountability purposes we need the modelName and modelNamespace properly set in the DMNResult, this is a small PR to do that. 

Best

### CODE REVIEW

**Comment by r00ta** [comment]
> you can even consider removing this additional constructor and just rely on the one accepting DMNResult for the same end-result. Up to you

Thx, done! I've also updated the dmn endpoint template accordingly

**Comment by tarilabs** [comment]
no wait, I meant exaclty the opposite! :D

**Comment by r00ta** [comment]
> no wait, I meant exaclty the opposite! :D

lol eheh. But I don't get it, the `rg.kie.dmn.api.core.DMNResult` does not contain the `modelName`, how can I set up the `modelName` in the constructor with just the `rg.kie.dmn.api.core.DMNResult` parameter?

**Comment by r00ta** [comment]
@evacchi, Myself and @tarilabs checked and we are fine with this version: we can move forward with this

**Pull request merged**
