### PR TITLE
KOGITO-4870 It's not possible to execute processes by using the quarkus

### PR DESCRIPTION
**Pull request by tiagodolphine**
Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](CONTRIBUTING.md)
- [ ] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/master/kogito-ide-config)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

* <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

### CODE REVIEW

**Comment by wmedvede** [comment]
Hi @tiagodolphine , I'm not familiar with this code, so I can't say too much.
But this is more or lees what I've could see after applying your changes locally:

1) I start the app with mvn clean compile quarkus:dev
2) Now the processes works
3) I do several invocations and the "Hot replace" is not executed. That's fine.
4) I do a small change in a java file.
5) I do a new invocation via rest on my processes, and the "Hot replace" is executed. That's fine, since a java file was modified.
6) I do a new invocation via rest and I can see again in the log "Hot replace total time: 2.566s", but there are no more modifications
7) I do a new invocation, and the same "Hot replace total time: 2.566s "
8) a new invocation, same thing "Hot replace total time: 2.566s" 

It looks like after step 4) the hot replace is being executed all the time, not good and not necessary since there are no more modifications since step 4.

**Comment by tiagodolphine** [comment]
Updated the PR with the fix we discussed in the call.

**Review by evacchi — APPROVED** [review]

**Comment by evacchi** [comment]
jenkins please test 🌈

**Review by mariofusco — APPROVED** [review]

**Comment by evacchi** [comment]
> script returned exit code 143

jenkins please retest this 🙏

**Comment by wmedvede** [comment]
Hi @tiagodolphine , I think a test will be more than great to add here otherwise it'll be difficult to catch up this sort of potential error next time. Specially considering "tricks" commented by @evacchi to make the hot reload work.

**Comment by tiagodolphine** [comment]
> Hi @tiagodolphine , I think a test will be more than great to add here otherwise it'll be difficult to catch up this sort of potential error next time. Specially considering "tricks" commented by @evacchi to make the hot reload work.

yeah, we need a test for this scenario, but I don't think we have an easy/quick way to do it now, I'll open a JIRA to do it, in this way we can merge this PR just a hotfix, and provide more tests afterward.

**Comment by pefernan** [comment]
Hey @tiagodolphine, I'm testing this PR locally with Task Console and found that the JSON schemas for task-forms are not generated, not sure if that's the same issue.

**Comment by tiagodolphine** [comment]
> R locally with Task Console and found that the JSON schemas for task-forms are not generated, not sure if that's the same issue.

I should be working unless it is a different issue, are you running in dev mode or using the generated jar?

**Comment by evacchi** [comment]
jenkins please retest this

**Comment by tiagodolphine** [comment]
@MarianMacik can you take a quick look at this, it's a hotfix for the hot reload for processes.

**Comment by tiagodolphine** [comment]
jenkins retest this

**Comment by tiagodolphine** [comment]
jenkins retest this

**Comment by tiagodolphine** [comment]
jenkins retest this

**Comment by tiagodolphine** [comment]
jenkins retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Review by cristianonicolai — APPROVED** [review]

**Comment by tiagodolphine** [comment]
jenkins retest this

**Comment by tiagodolphine** [comment]
impossible to get a green build =/

**Comment by pefernan** [comment]
@tiagodolphine I know that feeling...

**Comment by tiagodolphine** [comment]
jenkins retest this

**Comment by tiagodolphine** [comment]
jenkins retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Pull request merged**
