### PR TITLE
[1.13.x] KOGITO-7536 - Downgrade Spring Boot version to 2.5.12

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by kie-ci1** [comment]
**(tests) - kogito-examples job** `#4` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/4/display/redirect

**Test results:**
- PASSED: 430
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/4/testReport/org.acme.deals/DealsRestIT/Build_projects___testDealsRest/">Build projects / org.acme.deals.DealsRestIT.testDealsRest</a></summary>
java.lang.IllegalStateException: Failed to load ApplicationContext<br/>Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'applicationConfig' defined in file [/home/jenkins/workspace/KIE/kogito/1.13.x/pullrequest/kogito-runtimes.tests.downstream.kogito-examples/bc/kiegroup_kogito_examples/kogito-examples/process-mongodb-persistence-springboot/target/classes/org/kie/kogito/app/ApplicationConfig.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'processConfig' defined in file [/home/jenkins/workspace/KIE/kogito/1.13.x/pullrequest/kogito-runtimes.tests.downstream.kogito-examples/bc/kiegroup_kogito_examples/kogito-examples/process-mongodb-persistence-springboot/target/classes/org/kie/kogito/app/ProcessConfig.class]: Unsatisfied dependency expressed through constructor parameter 7; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mongoDBTransactionManagerImpl' defined in file [/home/jenkins/workspace/KIE/kogito/1.13.x/pullrequest/kogito-runtimes.tests.downstream.kogito-examples/bc/kiegroup_kogito_examples/kogito-examples/process-mongodb-persistence-springboot/target/classes/org/kie/kogito/mongodb/transaction/MongoDBTransactionManagerImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongo' defined in class path resource [org/springframework/boot/autoconfigure/mongo/MongoAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.mongodb.client.MongoClient]: Factory method 'mongo' threw exception; nested exception is java.lang.NoClassDefFoundError: com/mongodb/internal/connection/InternalConnectionPoolSettings<br/>Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'processConfig' defined in file [/home/jenkins/workspace/KIE/kogito/1.13.x/pullrequest/kogito-runtimes.tests.downstream.kogito-examples/bc/kiegroup_kogito_examples/kogito-examples/process-mongodb-persistence-springboot/target/classes/org/kie/kogito/app/ProcessConfig.class]: Unsatisfied dependency expressed through constructor parameter 7; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mongoDBTransactionManagerImpl' defined in file [/home/jenkins/workspace/KIE/kogito/1.13.x/pullrequest/kogito-runtimes.tests.downstream.kogito-examples/bc/kiegroup_kogito_examples/kogito-examples/process-mongodb-persistence-springboot/target/classes/org/kie/kogito/mongodb/transaction/MongoDBTransactionManagerImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongo' defined in class path resource [org/springframework/boot/autoconfigure/mongo/MongoAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.mongodb.client.MongoClient]: Factory method 'mongo' threw exception; nested exception is java.lang.NoClassDefFoundError: com/mongodb/internal/connection/InternalConnectionPoolSettings<br/>Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mongoDBTransactionManagerImpl' defined in file [/home/jenkins/workspace/KIE/kogito/1.13.x/pullrequest/kogito-runtimes.tests.downstream.kogito-examples/bc/kiegroup_kogito_examples/kogito-examples/process-mongodb-persistence-springboot/target/classes/org/kie/kogito/mongodb/transaction/MongoDBTransactionManagerImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongo' defined in class path resource [org/springframework/boot/autoconfigure/mongo/MongoAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.mongodb.client.MongoClient]: Factory method 'mongo' threw exception; nested exception is java.lang.NoClassDefFoundError: com/mongodb/internal/connection/InternalConnectionPoolSettings<br/>Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongo' defined in class path resource [org/springframework/boot/autoconfigure/mongo/MongoAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.mongodb.client.MongoClient]: Factory method 'mongo' threw exception; nested exception is java.lang.NoClassDefFoundError: com/mongodb/internal/connection/InternalConnectionPoolSettings<br/>Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.mongodb.client.MongoClient]: Factory method 'mongo' threw exception; nested exception is java.lang.NoClassDefFoundError: com/mongodb/internal/connection/InternalConnectionPoolSettings<br/>Caused by: java.lang.NoClassDefFoundError: com/mongodb/internal/connection/InternalConnectionPoolSettings<br/>Caused by: java.lang.ClassNotFoundException: com.mongodb.internal.connection.InternalConnectionPoolSettings<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/4/testReport/org.kie.kogito.springboot.outbox/OutboxIT/___/">org.kie.kogito.springboot.outbox.OutboxIT.(?)</a></summary>
java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [49616, 8080] should be listening)<br/>	at org.kie.kogito.springboot.outbox.OutboxIT.before(OutboxIT.java:85)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [49616, 8080] should be listening)<br/>
</details>

**Comment by kie-ci1** [comment]
**(tests) - optaweb-employee-rostering job** `#5` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-runtimes.tests.downstream.optaweb-employee-rostering/5/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-07-12T08:38:15.898Z] 0	/home/jenkins/workspace/custom/tradisso/test<br/>[2022-07-12T08:38:15.898Z] 0	/home/jenkins/workspace/custom/tradisso/test@tmp<br/>[2022-07-12T08:38:15.898Z] 0	/home/jenkins/workspace/custom/tradisso<br/>[2022-07-12T08:38:15.898Z] 0	/home/jenkins/workspace/custom<br/>[2022-07-12T08:38:15.898Z] du: cannot access ‘/home/jenkins/workspace/KIE/optaplanner/main/pullrequest/optaplanner.tests.downstream.optaweb-vehicle-routing_ws-cleanup_1657615090422/bc/kiegroup_optaweb_vehicle_routing/optaweb-vehicle-routing/optaweb-vehicle-routing-frontend/node_modules/string.prototype.matchall/node_modules/es-abstract/2017/OrdinaryGetOwnProperty.js’: No such file or directory<br/>[2022-07-12T08:38:15.898Z] du: cannot access ‘/home/jenkins/workspace/KIE/optaplanner/main/pullrequest/optaplanner.tests.downstream.optaweb-vehicle-routing_ws-cleanup_1657615090422/bc/kiegroup_optaweb_vehicle_routing/optaweb-vehicle-routing/optaweb-vehicle-routing-frontend/node_modules/string.prototype.matchall/node_modules/es-abstract/2017/OrdinaryGetPrototypeOf.js’: No such file or directory<br/>[2022-07-12T08:38:15.898Z] du: cannot access ‘/home/jenkins/workspace/KIE/optaplanner/main/pullrequest/optaplanner.tests.downstream.optaweb-vehicle-routing_ws-cleanup_1657615090422/bc/kiegroup_optaweb_vehicle_routing/optaweb-vehicle-routing/optaweb-vehicle-routing-frontend/node_modules/string.prototype.matchall/node_modules/es-abstract/2017/OrdinaryHasInstance.js’: No such file or directory<br/>[2022-07-12T08:38:15.898Z] du: cannot access ‘/home/jenkins/workspace/KIE/optaplanner/main/pullrequest/optaplanner.tests.downstream.optaweb-vehicle-routing_ws-cleanup_1657615090422/bc/kiegroup_optaweb_vehicle_routing/optaweb-vehicle-routing/optaweb-vehicle-routing-frontend/node_modules/string.prototype.matchall/node_modules/es-abstract/2017/OrdinaryHasProperty.js’: No such file or directory<br/>[2022-07-12T08:38:15.898Z] 224M	/home/jenkins/workspace/KIE/optaplanner/main<br/>[2022-07-12T08:38:15.898Z] 224M	/home/jenkins/workspace/KIE/optaplanner<br/>[2022-07-12T08:38:15.898Z] 2.5M	/home/jenkins/workspace/KIE/kogito/1.13.x<br/>[2022-07-12T08:38:15.898Z] 2.5M	/home/jenkins/workspace/KIE/kogito<br/>[2022-07-12T08:38:15.898Z] 226M	/home/jenkins/workspace/KIE<br/>[2022-07-12T08:38:15.898Z] 226M	/home/jenkins/workspace<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Install build-chain tool)<br/>Stage "Install build-chain tool" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>Stage "Build projects" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Sonar analysis)<br/>Stage "Sonar analysis" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space after build)<br/>Stage "check space after build" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-07-12T08:38:16.742Z] + wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-runtimes.tests.downstream.optaweb-employee-rostering/5/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by cristianonicolai** [comment]
Jenkins rerun optaweb-employee-rostering tests

**Comment by cristianonicolai** [comment]
@jstastny-cz also included the changes needed for kafka-clients

**Comment by jstastny-cz** [comment]
I think we still need to upgrade kafka-clients to 3.1.0. Discussing elsewhere.

**Review by jstastny-cz — APPROVED** [review]
LGTM, discussion about kafka-clients taken elsewhere.

**Pull request merged**
