### PR TITLE
[DROOLS-5861] Excluding drools-mvel from kie-pmml-dependencies

### PR DESCRIPTION
**Pull request by gitgabrio**
@danielezonca @mariofusco @jiripetrlik

See https://issues.redhat.com/browse/DROOLS-5861

Depends on
https://github.com/kiegroup/droolsjbpm-knowledge/pull/492
https://github.com/kiegroup/drools/pull/3296

### CODE REVIEW

**Comment by triceo** [comment]
@gitgabrio Do you still want to merge this? The following PR made it a little easier:
https://github.com/kiegroup/kogito-runtimes/pull/990

**Comment by gitgabrio** [comment]
@triceo 
I think it is safer to keep this PR. I'll update it as soon as the other one is merged

**Review by jiripetrlik — APPROVED** [review]

**Comment by gitgabrio** [comment]
@triceo 
Hi Lucas, thanks for the update but we choose to postpone it after the final release of 7.49, since that snapshot (7.49.0.t20210118) does not contains required code.
I would kindly beg you to ask me before commit/modify my branches, thanks!

**Comment by triceo** [comment]
@gitgabrio No worries. Even better - I won't touch it from now on. :-)

**Review by mariofusco — APPROVED** [review]

**Comment by danielezonca** [comment]
jenkins retest this please

**Review by danielezonca — APPROVED** [review]

**Comment by danielezonca** [comment]
jenkins retest this please

**Pull request merged**
