### PR TITLE
Fix explainability artifact id

### PR DESCRIPTION
**Pull request by r00ta**
Moved `explainability` artifact id to `explainability-addon` so to fix https://kie.zulipchat.com/#narrow/stream/232676-kogito/topic/GAV.20conflicts.20between.20runtimes.20.26.20apps/near/215813646

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](CONTRIBUTING.md)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Review by danielezonca — APPROVED** [review]
LGTM

**Review by radtriste — APPROVED** [review]
Good with that.

On another side, I think we should also rename all parent poms in addons module with `-addon` so that it does not conflict with apps ... But that would be for another issue.
@danielezonca wdyt ?

**Comment by r00ta** [comment]
^^ Resolved conflicts

**Comment by radtriste** [comment]
@danielezonca that one can be merged :)

**Pull request merged**
