### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by mareknovotny**
This PR adds issue template on request of @ricardozanini 

> We were discussing in the past Runtimes Retrospective about the GH issues in the repositories in 'Create Github Issue Template on Kogito Runtimes and Examples' email thread. We came up with a "solution" for users to avoid using it. The idea is to create GH Issues Templates encouraging users to use JIRA to report bugs >and our dev list to ask questions.

>Although, I don't have permission to purpose templates in these repositories. Can you give me our create yourself one, please? 
>Many thanks!

The four templates were created and are the default ones very slighly customized to what we talked about to target people to JIRA.

### CODE REVIEW

**Comment by mareknovotny** [comment]
@ricardozanini @cristianonicolai @danielezonca @evacchi any review feedback? i guess this PR fell down from your focus ;)

**Comment by danielezonca** [comment]
Hi @mareknovotny 
Yes I missed this PR :)
Can you please add some more context? As far as I can see it includes some (4) issue templates but they look to me almost the same so I don't understand why 4

**Comment by mareknovotny** [comment]
i think that is some out of control result :)
i will check why 4.

**Comment by mareknovotny** [comment]
> Hi @mareknovotny
> Yes I missed this PR :)
> Can you please add some more context? As far as I can see it includes some (4) issue templates but they look to me almost the same so I don't understand why 4

i remind myself the past. These 4 templates are default ones if you enable them in Settings and Github generates them for you with possibility to change text. There are like types for Bug Report, Feature Request and Custom template. I am not sure, but maybe they removed one or i did mistakenly duplicates.
So I will keep only Bug and Feature report types and you can discuss if both are needed.

**Comment by ricardozanini** [comment]
@danielezonca @mareknovotny I'm sorry, this is on my plate for some time. I'll review it later. We need to take the "you're encouraged to open a JIRA or discuss with us on Zulip" approach. BUT they can open the issue either way. So we ask ahead all the info we need to open a JIRA or to reproduce the problem.

**Comment by mareknovotny** [comment]
closing in favour of https://github.com/kiegroup/kogito-runtimes/pull/1843

**Pull request closed without merging**
