### PR TITLE
Kogito 2743 - Add Audit UI link to grafana dashboards

### PR DESCRIPTION
**Pull request by r00ta**
Jira: https://issues.redhat.com/browse/KOGITO-2743

In the context of the grafana monitoring dashboards, this PR adds the link to the Audit UI if the tracing and the monitoring addons are active. The URL added to the dashboards is a placeholder that has to be replaced by the operator or anyway by a script of the developer during the deployment of the dashboards. 

Screenshot from 2020-07-14 09-52-55

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.md)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by r00ta** [comment]
Depends on #630

**Comment by danielezonca** [comment]
@r00ta 
Can you please add to ticket description an example of link that will be generated in Grafana with this PR?

**Comment by r00ta** [comment]
> @r00ta
> Can you please add to ticket description an example of link that will be generated in Grafana with this PR?

Hi @danielezonca , I've added the screenshot to the jira ticket. In particular a kind of button is added at top right of every dashboard, the URL in the templates is just a placeholder (`${{urlPlaceholder}}`) that has to be replaced by the operator (or by a script, or manually) during the deployment of the dashboards

**Comment by danielezonca** [comment]
@r00ta 
I mainly refer to which parameters are added to URL.
See https://grafana.com/static/assets/img/blog/dashboard_links2.png
I would like to flag all the `Include` options

**Pull request merged**
