### PR TITLE
KOGITO-2639 Follow up upgrade dependencies aliging with Quarkus 1.6.0

### PR DESCRIPTION
**Pull request by cristianonicolai**
Assembly:
- https://github.com/kiegroup/kogito-runtimes/pull/607
- https://github.com/kiegroup/kogito-examples/pull/290
- https://github.com/kiegroup/kogito-apps/pull/305

### CODE REVIEW

**Comment by cristianonicolai** [comment]
keeping as draft to be merged after 0.12 release.

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by evacchi** [comment]
please add a bump to antlr 4.8 since you're doing this already :)

**Comment by cristianonicolai** [comment]
@evacchi done

**Pull request merged**
