### PR TITLE
Fix kogito-quarkus parent

### PR DESCRIPTION
**Pull request by danielezonca**
Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](CONTRIBUTING.md)
- [ ] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/master/kogito-ide-config)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Review by evacchi — APPROVED** [review]

**Comment by evacchi** [comment]
issues with formatter @danielezonca @r00ta

**Comment by danielezonca** [comment]
> issues with formatter @danielezonca @r00ta

Fixed by https://github.com/kiegroup/kogito-runtimes/pull/1100

jenkins retest this please

**Comment by danielezonca** [comment]
`testPingPongBetweenProcessInstances – org.kie.kogito.integrationtests.springboot.PingPongMessageTest`
`ConditionTimeoutException`

jenkins retest this please

**Comment by danielezonca** [comment]
`doTest – org.kie.kogito.it.trusty.SpringBootTrustyExplainabilityEnd2EndIT`
`org.awaitility.core.ConditionTimeoutException`

Different test (in different repo) and another timeout, merging

**Pull request merged**
