### PR TITLE
[KOGITO-5530] Increase DevMojoIT timeout

### PR DESCRIPTION
**Pull request by danielezonca**
https://issues.redhat.com/browse/KOGITO-5530

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](CONTRIBUTING.md)
- [ ] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/master/kogito-build/kogito-ide-config)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Run all builds</b>  
  Please add comment: <b>Jenkins retest this</b>

* <b>Run (or rerun) specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [runtimes|optaplanner|apps|examples] tests</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Run (or rerun) LTS specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [runtimes|optaplanner|apps|examples] LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

* <b>Run (or rerun) native specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [runtimes|optaplanner|apps|examples] native</b>

* <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

### CODE REVIEW

**Comment by danielezonca** [comment]
Green https://eng-jenkins-csb-business-automation.apps.ocp4.prod.psi.redhat.com/job/KIE/job/kogito/job/pullrequest/job/master/job/kogito-runtimes.tests.runtimes/84/display/redirect

Jenkins run runtimes tests

**Comment by radtriste** [comment]
Jenkins rerun runtimes tests

**Comment by danielezonca** [comment]
Second build succeed 
https://eng-jenkins-csb-business-automation.apps.ocp4.prod.psi.redhat.com/job/KIE/job/kogito/job/pullrequest/job/master/job/kogito-runtimes.tests.runtimes/86/

Third build failed a previous test because of timeout
[testMultipleEventBasedStartEventsTimerDifferentPaths](https://eng-jenkins-csb-business-automation.apps.ocp4.prod.psi.redhat.com/job/KIE/job/kogito/job/pullrequest/job/master/job/kogito-runtimes.tests.runtimes/89/testReport/junit/org.jbpm.bpmn2/StartEventTest/testMultipleEventBasedStartEventsTimerDifferentPaths/)

Is it another flaky test?

Jenkins rerun runtimes tests

**Comment by danielezonca** [comment]
Another green build
https://eng-jenkins-csb-business-automation.apps.ocp4.prod.psi.redhat.com/job/KIE/job/kogito/job/pullrequest/job/master/job/kogito-runtimes.tests.runtimes/92/display/redirect

Jenkins rerun runtimes tests

**Comment by danielezonca** [comment]
Another green build
https://eng-jenkins-csb-business-automation.apps.ocp4.prod.psi.redhat.com/job/KIE/job/kogito/job/pullrequest/job/master/job/kogito-runtimes.tests.runtimes/93/display/redirect

Jenkins rerun runtimes tests

**Comment by radtriste** [comment]
still green
https://eng-jenkins-csb-business-automation.apps.ocp4.prod.psi.redhat.com/blue/organizations/jenkins/KIE%2Fkogito%2Fpullrequest%2Fmaster%2Fkogito-runtimes.tests.runtimes/detail/kogito-runtimes.tests.runtimes/95/

Let's try one last time ?
Jenkins rerun runtimes tests

**Review by tarilabs — APPROVED** [review]
the long timeout is concerning for being tied to CI limitation it seems?

**Comment by radtriste** [comment]
It is also because, AFAIU, the DevMojoIT test is getting artifacts from external repository instead of local ... That needs to be investigated why so ...

**Pull request merged**
