### PR TITLE
KOGITO-4984 - Add artifactId and version labels in dashboards

### PR DESCRIPTION
**Pull request by r00ta**
JIRA: https://issues.redhat.com/browse/KOGITO-4984

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.md)
- [x] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/master/kogito-ide-config)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

* <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

### CODE REVIEW

**Comment by r00ta** [comment]
Jenkins retest this please

**Comment by r00ta** [comment]
Jenkins retest this please

**Comment by r00ta** [comment]
Jenkins retest this please

**Review by danielezonca — APPROVED** [review]

**Comment by danielezonca** [comment]
@cristianonicolai @tiagodolphine 
[`kogito-apps` failed](https://github.com/kiegroup/kogito-runtimes/pull/1241/checks?check_run_id=2846346160) with
> kiegroup_kogito_apps/data-index/data-index-service/data-index-service-infinispan/src/test/java/org/kie/kogito/index/graphql/InfinispanWebSocketSubscriptionIT.java:1 | java.util.concurrent.TimeoutException

It looks like a flaky test, can you please have a look?

I can also see in the log this WARN that looks strange

> 2021-06-17T07:25:02.6468102Z 2021-06-17 07:24:59,417 WARN  [org.kie.kog.ind.gra.GraphQLSchemaManager] (vert.x-eventloop-thread-1) Process 'travels_sub' endpoint '/travels_sub', does not contain full URL, please review the kogito.service.url system property to point the public URL for this runtime.
> 2021-06-17T07:25:02.6473465Z 2021-06-17 07:25:00,195 WARN  [org.kie.kog.ind.gra.GraphQLSchemaManager] (vert.x-eventloop-thread-0) Process 'travels_sub' endpoint '/travels_sub', does not contain full URL, please review the kogito.service.url system property to point the public URL for this runtime.
> 2021-06-17T07:25:02.6479362Z 2021-06-17 07:25:01,405 WARN  [org.kie.kog.ind.gra.GraphQLSchemaManager] (vert.x-eventloop-thread-2) Process 'travels_sub' endpoint '/travels_sub', does not contain full URL, please review the kogito.service.url system property to point the public URL for this runtime.
> 2021-06-17T07:25:02.6484344Z 2021-06-17 07:25:02,209 WARN  [org.kie.kog.ind.gra.GraphQLSchemaManager] (vert.x-eventloop-thread-3) Process 'travels_sub' endpoint '/travels_sub', does not contain full URL, please review the kogito.service.url system property to point the public URL for this runtime.
> 2021-06-17T07:25:02.6545581Z 2021-06-17 07:25:02,651 WARN  [org.kie.kog.per.pro.ProtobufService] (main) Error trying to parse proto buffer file: Failed to resolve type of field "org.demo.travels.traveller". Type not found : stringa: org.infinispan.protostream.DescriptorParserException: Failed to resolve type of field "org.demo.travels.traveller". Type not found : stringa
> 2021-06-17T07:25:02.6549403Z 	at org.infinispan.protostream.descriptors.FileDescriptor.resolveFieldTypes(FileDescriptor.java:347)
> 2021-06-17T07:25:02.6553082Z 	at org.infinispan.protostream.descriptors.FileDescriptor.resolveDependencies(FileDescriptor.java:254)
> 2021-06-17T07:25:02.6557104Z 	at org.infinispan.protostream.descriptors.FileDescriptor.resolveDependencies(FileDescriptor.java:210)
> 2021-06-17T07:25:02.6560470Z 	at org.infinispan.protostream.descriptors.ResolutionContext.resolve(ResolutionContext.java:57)
> ...

But I don't know if it is related or not

**Review by jiripetrlik — APPROVED** [review]
Looks good to me.

**Pull request merged**
