### PR TITLE
KOGITO-4551 Java module name for -runtimes/drools/ artifacts

### PR DESCRIPTION
**Pull request by tarilabs**
https://issues.redhat.com/browse/KOGITO-4551

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.md)
- [x] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/master/kogito-ide-config)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by evacchi** [comment]
jenkins please retest this

**Review by danielezonca — APPROVED** [review]
Thanks for the PR, approving 👍

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by tarilabs** [comment]
```
org.kie.kogito.examples.GrafanaDockerComposeIT.testPrometheusTargetsAreGreen
 Error Details
1 expectation failed.
Response body doesn't match expectation.
Expected: a string containing "\"health\":\"up\""
  Actual: {"status":"success","data":{"activeTargets":[{"discoveredLabels":{"__address__":"hello:8080","__metrics_path__":"/metrics","__scheme__":"http","job":"kogito-app"},"labels":{"instance":"hello:8080","job":"kogito-app"},"scrapeUrl":"http://hello:8080/metrics","lastError":"","lastScrape":"0001-01-01T00:00:00Z","health":"unknown"}],"droppedTargets":[]}}
 Stack Trace
java.lang.AssertionError: 
1 expectation failed.
Response body doesn't match expectation.
Expected: a string containing "\"health\":\"up\""
  Actual: {"status":"success","data":{"activeTargets":[{"discoveredLabels":{"__address__":"hello:8080","__metrics_path__":"/metrics","__scheme__":"http","job":"kogito-app"},"labels":{"instance":"hello:8080","job":"kogito-app"},"scrapeUrl":"http://hello:8080/metrics","lastError":"","lastScrape":"0001-01-01T00:00:00Z","health":"unknown"}],"droppedTargets":[]}}

	at org.kie.kogito.examples.GrafanaDockerComposeIT.testPrometheusTargetsAreGreen(GrafanaDockerComposeIT.java:132)
 Standard Output
08:29:47.761 [main] INFO  org.testcontainers.dockerclient.DockerClientProviderStrategy - Loaded org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy from ~/.testcontainers.properties, will try it first
08:29:48.377 [main] INFO  org.testcontainers.dockerclient.DockerClientProviderStrategy - Found Docker environment with Environment variables, system properties and defaults. Resolved dockerHost=unix:///var/run/docker.sock
08:29:48.380 [main] INFO  org.testcontainers.DockerClientFactory - Docker host IP address is localhost
08:29:48.423 [main] INFO  org.testcontainers.DockerClientFactory - Connected to docker: 
  Server Version: 20.10.3
  API Version: 1.41
  Operating System: Red Hat Enterprise Linux Server 7.9 (Maipo)
  Total Memory: 15884 MB
08:29:48.426 [main] INFO  org.testcontainers.utility.ImageNameSubstitutor - Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
08:29:48.477 [main] INFO  org.testcontainers.utility.RegistryAuthLocator - Failure when attempting to lookup auth config. Please ignore if you don't have images in an authenticated registry. Details: (dockerImageName: testcontainers/ryuk:0.3.0, configFile: /home/jenkins/.docker/config.json. Falling back to docker-java default behaviour. Exception message: /home/jenkins/.docker/config.json (No such file or directory)
08:29:48.970 [main] INFO  org.testcontainers.DockerClientFactory - Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
08:29:48.983 [main] INFO  org.testcontainers.containers.DockerComposeContainer - Preemptively checking local images for 'grafana/grafana:6.6.1', referenced via a compose file or transitive Dockerfile. If not available, it will be pulled.
08:29:48.986 [main] INFO  org.testcontainers.containers.DockerComposeContainer - Preemptively checking local images for 'org.kie.kogito.examples/dmn-drools-springboot-metrics:1.0', referenced via a compose file or transitive Dockerfile. If not available, it will be pulled.
08:29:48.989 [main] INFO  org.testcontainers.containers.DockerComposeContainer - Preemptively checking local images for 'prom/prometheus:v2.8.0', referenced via a compose file or transitive Dockerfile. If not available, it will be pulled.
08:29:49.015 [main] INFO  🐳 [docker/compose:1.24.1] - Creating container for image: docker/compose:1.24.1
08:29:49.053 [main] INFO  🐳 [docker/compose:1.24.1] - Starting container with ID: 66859ecd428ed83b7b92063eda22c4d12fe879fa9f3df09c477ff2271a4b904f
08:29:49.363 [main] INFO  🐳 [docker/compose:1.24.1] - Container docker/compose:1.24.1 is starting: 66859ecd428ed83b7b92063eda22c4d12fe879fa9f3df09c477ff2271a4b904f
08:29:52.074 [main] INFO  🐳 [docker/compose:1.24.1] - Container docker/compose:1.24.1 started in PT3.058628S
08:29:52.078 [main] INFO  🐳 [docker/compose:1.24.1] - Docker Compose container is running for command: up -d
08:29:52.080 [main] INFO  🐳 [docker/compose:1.24.1] - Docker Compose has finished running
08:29:52.081 [docker-java-stream--425340774] INFO  🐳 [docker/compose:1.24.1] - STDERR: Creating network "dpihzqg2v45j_default" with the default driver
08:29:52.087 [docker-java-stream--425340774] INFO  🐳 [docker/compose:1.24.1] - STDERR: Creating dpihzqg2v45j_hello_1 ... 
08:29:52.088 [docker-java-stream--425340774] INFO  🐳 [docker/compose:1.24.1] - STDERR: &amp#27;[1A&amp#27;[2K
Creating dpihzqg2v45j_hello_1 ... done
&amp#27;[1BCreating dpihzqg2v45j_prometheus_1 ... 
08:29:52.088 [docker-java-stream--425340774] INFO  🐳 [docker/compose:1.24.1] - STDERR: &amp#27;[1A&amp#27;[2K
Creating dpihzqg2v45j_prometheus_1 ... done
&amp#27;[1BCreating dpihzqg2v45j_grafana_1    ... 
08:29:52.088 [docker-java-stream--425340774] INFO  🐳 [docker/compose:1.24.1] - STDERR: &amp#27;[1A&amp#27;[2K
Creating dpihzqg2v45j_grafana_1    ... done
&amp#27;[1B
08:29:52.093 [main] INFO  🐳 [alpine/socat:1.7.3.4-r0] - Creating container for image: alpine/socat:1.7.3.4-r0
08:29:52.167 [main] INFO  🐳 [alpine/socat:1.7.3.4-r0] - Starting container with ID: 67e64132f69874128752a4cd05350d83e6138ed3911993dc39b67321e0e3b977
08:29:52.856 [main] INFO  🐳 [alpine/socat:1.7.3.4-r0] - Container alpine/socat:1.7.3.4-r0 is starting: 67e64132f69874128752a4cd05350d83e6138ed3911993dc39b67321e0e3b977
08:29:52.968 [main] INFO  🐳 [alpine/socat:1.7.3.4-r0] - Container alpine/socat:1.7.3.4-r0 started in PT0.875585S
08:29:58.385 [main] INFO  org.testcontainers.containers.DockerComposeContainer - Preemptively checking local images for 'grafana/grafana:6.6.1', referenced via a compose file or transitive Dockerfile. If not available, it will be pulled.
08:29:58.388 [main] INFO  org.testcontainers.containers.DockerComposeContainer - Preemptively checking local images for 'org.kie.kogito.examples/dmn-drools-springboot-metrics:1.0', referenced via a compose file or transitive Dockerfile. If not available, it will be pulled.
08:29:58.390 [main] INFO  org.testcontainers.containers.DockerComposeContainer - Preemptively checking local images for 'prom/prometheus:v2.8.0', referenced via a compose file or transitive Dockerfile. If not available, it will be pulled.
08:29:58.392 [main] INFO  🐳 [docker/compose:1.24.1] - Creating container for image: docker/compose:1.24.1
08:29:58.422 [main] INFO  🐳 [docker/compose:1.24.1] - Starting container with ID: 9f73d3216724bf4d56a21080bc89530bbd61483bbdedabd87c4f0829757c478f
08:29:58.758 [main] INFO  🐳 [docker/compose:1.24.1] - Container docker/compose:1.24.1 is starting: 9f73d3216724bf4d56a21080bc89530bbd61483bbdedabd87c4f0829757c478f
08:29:59.550 [main] INFO  🐳 [docker/compose:1.24.1] - Container docker/compose:1.24.1 started in PT1.157882S
08:29:59.551 [main] INFO  🐳 [docker/compose:1.24.1] - Docker Compose container is running for command: up -d
08:29:59.553 [docker-java-stream-1509641458] INFO  🐳 [docker/compose:1.24.1] - STDERR: dpihzqg2v45j_hello_1 is up-to-date
08:29:59.553 [docker-java-stream-1509641458] INFO  🐳 [docker/compose:1.24.1] - STDERR: dpihzqg2v45j_prometheus_1 is up-to-date
08:29:59.553 [docker-java-stream-1509641458] INFO  🐳 [docker/compose:1.24.1] - STDERR: dpihzqg2v45j_grafana_1 is up-to-date
08:29:59.554 [main] INFO  🐳 [docker/compose:1.24.1] - Docker Compose has finished running
```

Something something Grafana something 🎱 🤷‍♂️ 

Jenkins retest this

**Comment by evacchi** [comment]
"CI builds are like violence"

Jenkins retest this

**Comment by tarilabs** [comment]
https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/kogito/job/pullrequest/job/kogito-runtimes/414/testReport/
```
org.kie.kogito.explainability.utils.WeightedLinearRegressionTest.testUnderspecifiedIntercept
 Error Details
expected: <0.0> but was: <1.1128751789596404E-6>
 Stack Trace
org.opentest4j.AssertionFailedError: expected: <0.0> but was: <1.1128751789596404E-6>
```

🎱 🤷‍♂️ 

Jenkins retest this

**Pull request merged**
