### PR TITLE
[KOGITO-5965] Fix migration to Trusty PMML 7.60

### PR DESCRIPTION
**Pull request by gitgabrio**
@danielezonca @Ginxo 

It builds and execute quick test on my local machine.

Depends on 

https://github.com/kiegroup/drools/pull/3852
https://github.com/kiegroup/kogito-examples/pull/903

### CODE REVIEW

**Review by Ginxo — APPROVED** [review]
LGTM, many thanks!

**Comment by gitgabrio** [comment]
@danielezonca @Ginxo 
This PR compile on my machine, but of course not on Jenkins due to lack of "SNAPSHOT" branch. Let me know how to proceed, thanks!

**Comment by Ginxo** [comment]
> @danielezonca @Ginxo
> This PR compile on my machine, but of course not on Jenkins due to lack of "SNAPSHOT" branch. Let me know how to proceed, thanks!

@lucamolteni any idea?

**Comment by danielezonca** [comment]
This PR cannot be merged until Kogito bumps to 7.60.Final. After that we expect to use 8 snapshot branch but we are not there yet.

I think we can rename this PR as `Bump kie7 to 7.60` and keep in draft for another week at least waiting for that release.

@gitgabrio 
Please have a look to build failures, this PR should be green because it is using snapshot version so it is strange that all builds are red.

**Comment by gitgabrio** [comment]
> This PR cannot be merged until Kogito bumps to 7.60.Final. After that we expect to use 8 snapshot branch but we are not there yet.
> 
> I think we can rename this PR as `Bump kie7 to 7.60` and keep in draft for another week at least waiting for that release.
> 
> @gitgabrio
> Please have a look to build failures, this PR should be green because it is using snapshot version so it is strange that all builds are red.

@danielezonca 
`[2021-09-24T15:30:33.588Z] [ERROR] Failed to execute goal on project kogito-pmml-api-dependencies: Could not resolve dependencies for project org.kie.kogito:kogito-pmml-api-dependencies:jar:2.0.0-SNAPSHOT: The following artifacts could not be resolved: org.kie:kie-pmml-evaluator-api:jar:7.60.0-SNAPSHOT, org.kie:kie-pmml-commons:jar:7.60.0-SNAPSHOT: Could not find artifact org.kie:kie-pmml-evaluator-api:jar:7.60.0-SNAPSHOT -> [Help 1]

[2021-09-24T15:30:33.588Z] [ERROR] Failed to execute goal on project drools-core-dynamic: Could not resolve dependencies for project org.kie.kogito:drools-core-dynamic:jar:2.0.0-SNAPSHOT: Could not find artifact org.drools:drools-core-dynamic:jar:7.60.0-SNAPSHOT -> [Help 1]

[2021-09-24T15:30:33.588Z] [ERROR] Failed to execute goal on project kogito-drools-model: Could not resolve dependencies for project org.kie.kogito:kogito-drools-model:jar:2.0.0-SNAPSHOT: Could not find artifact org.drools:drools-model-compiler:jar:7.60.0-SNAPSHOT -> [Help 1]

[2021-09-24T15:30:33.588Z] [ERROR] Failed to execute goal on project kogito-pmml-dependencies: Could not resolve dependencies for project org.kie.kogito:kogito-pmml-dependencies:pom:2.0.0-SNAPSHOT: Could not find artifact org.kie:kie-pmml-dependencies:jar:7.60.0-SNAPSHOT -> [Help 1]

[2021-09-24T15:30:33.588Z] [ERROR] Failed to execute goal on project drools-decisiontables: Could not resolve dependencies for project org.kie.kogito:drools-decisiontables:jar:2.0.0-SNAPSHOT: Could not find artifact org.drools:drools-decisiontables:jar:7.60.0-SNAPSHOT -> [Help 1]`

**Comment by danielezonca** [comment]
> > This PR cannot be merged until Kogito bumps to 7.60.Final. After that we expect to use 8 snapshot branch but we are not there yet.
> > I think we can rename this PR as `Bump kie7 to 7.60` and keep in draft for another week at least waiting for that release.
> > @gitgabrio
> > Please have a look to build failures, this PR should be green because it is using snapshot version so it is strange that all builds are red.
> 
> @danielezonca
> `[2021-09-24T15:30:33.588Z] [ERROR] Failed to execute goal on project kogito-pmml-api-dependencies: Could not resolve dependencies for project org.kie.kogito:kogito-pmml-api-dependencies:jar:2.0.0-SNAPSHOT: The following artifacts could not be resolved: org.kie:kie-pmml-evaluator-api:jar:7.60.0-SNAPSHOT, org.kie:kie-pmml-commons:jar:7.60.0-SNAPSHOT: Could not find artifact org.kie:kie-pmml-evaluator-api:jar:7.60.0-SNAPSHOT -> [Help 1]
> 
> [2021-09-24T15:30:33.588Z] [ERROR] Failed to execute goal on project drools-core-dynamic: Could not resolve dependencies for project org.kie.kogito:drools-core-dynamic:jar:2.0.0-SNAPSHOT: Could not find artifact org.drools:drools-core-dynamic:jar:7.60.0-SNAPSHOT -> [Help 1]
> 
> [2021-09-24T15:30:33.588Z] [ERROR] Failed to execute goal on project kogito-drools-model: Could not resolve dependencies for project org.kie.kogito:kogito-drools-model:jar:2.0.0-SNAPSHOT: Could not find artifact org.drools:drools-model-compiler:jar:7.60.0-SNAPSHOT -> [Help 1]
> 
> [2021-09-24T15:30:33.588Z] [ERROR] Failed to execute goal on project kogito-pmml-dependencies: Could not resolve dependencies for project org.kie.kogito:kogito-pmml-dependencies:pom:2.0.0-SNAPSHOT: Could not find artifact org.kie:kie-pmml-dependencies:jar:7.60.0-SNAPSHOT -> [Help 1]
> 
> [2021-09-24T15:30:33.588Z] [ERROR] Failed to execute goal on project drools-decisiontables: Could not resolve dependencies for project org.kie.kogito:drools-decisiontables:jar:2.0.0-SNAPSHOT: Could not find artifact org.drools:drools-decisiontables:jar:7.60.0-SNAPSHOT -> [Help 1]`

This seems strange to me 🤔 
@Ginxo 
Do you know if we had any issue with the nightly snapshot build? 7.60.0-SNAPSHOT should be available 🤔

**Comment by Ginxo** [comment]
the daily you mean @danielezonca, @mbiarnes ?

**Comment by danielezonca** [comment]
@triceo 
Can you please have a look to the failed OptaPlanner build?
https://github.com/kiegroup/kogito-runtimes/pull/1628/checks?check_run_id=3721193946
This PR is testing Kogito with Drools 7.60-SNAPSHOT and it fixes some differences at PMML level but I was not expecting an error in OptaPlanner build.
The error is a failure in the expected error message thrown by Drools
```
2021-09-27T14:20:22.5724453Z [ERROR] org.optaplanner.core.impl.solver.DefaultSolverTest.solveMetricsError  Time elapsed: 0.112 s  <<< FAILURE!
2021-09-27T14:20:22.5726596Z java.lang.AssertionError: 
2021-09-27T14:20:22.5727061Z 
2021-09-27T14:20:22.5727520Z Expecting throwable message:
2021-09-27T14:20:22.5728726Z   "Error evaluating constraint '' in [Rule "" in ]"
2021-09-27T14:20:22.5729390Z to contain:
2021-09-27T14:20:22.5729912Z   "Thrown exception in constraint provider"
2021-09-27T14:20:22.5730434Z but did not.
2021-09-27T14:20:22.5730693Z 
2021-09-27T14:20:22.5731106Z Throwable that failed the check:
2021-09-27T14:20:22.5731451Z 
2021-09-27T14:20:22.5733289Z org.drools.modelcompiler.constraints.ConstraintEvaluationException: Error evaluating constraint '' in [Rule "" in ]
2021-09-27T14:20:22.5736154Z 	at org.drools.modelcompiler.constraints.LambdaConstraint.isAllowed(LambdaConstraint.java:178)
```

It might be related to this PR https://github.com/kiegroup/drools/pull/3785 that touched some error reporting but I'm not sure
/cc @tkobayas

**Comment by triceo** [comment]
@danielezonca I am on PTO at the moment, will return on Wednesday. That said, this does look as if something in Drools changed and nobody checked the FDB.

**Comment by gitgabrio** [comment]
Jenkins retest this

**Comment by tkobayas** [comment]
@danielezonca  @triceo  Thank you for pointing that out. Indeed https://github.com/kiegroup/drools/pull/3785 (DROOLS-6351) changed the error message so caused the `DefaultSolverTest.solveMetricsError` assertion failure. I filed a fix PR.

https://github.com/kiegroup/optaplanner/pull/1590

> this does look as if something in Drools changed and nobody checked the FDB. 

IIRC, I confirmed that FDB had no issue with optaplanner. Btw, optaplanner main depends on version.org.kie.kogito 2.0.0-SNAPSHOT so depends on drools 7.59.0.Final. Does FDB test optalanner with drools 7.60.0-SNAPSHOT? (Sorry, if I'm asking a stupid question...)

**Comment by danielezonca** [comment]
> @danielezonca @triceo Thank you for pointing that out. Indeed [kiegroup/drools#3785](https://github.com/kiegroup/drools/pull/3785) (DROOLS-6351) changed the error message so caused the `DefaultSolverTest.solveMetricsError` assertion failure. I filed a fix PR.
> 
> [kiegroup/optaplanner#1590](https://github.com/kiegroup/optaplanner/pull/1590)
> 
> > this does look as if something in Drools changed and nobody checked the FDB.
> 
> IIRC, I confirmed that FDB had no issue with optaplanner. Btw, I noticed that optaplanner main depends on version.org.kie.kogito 2.0.0-SNAPSHOT so depends on drools 7.59.0.Final. Does FDB (triggered by a drools PR) test optaplanner with drools 7.60.0-SNAPSHOT? (Sorry, if I'm asking a stupid question...)

You are right, for now OptaPlanner depends on a final version of drools so a normal FDB triggered in drools PR is only testing 7.x stream and not Kogito/OptaPlanner 8. This PR is changing drools version so it is the first build that can highlight a similar issue.
This will change soon including drools8 build as part of Kogito/OptaPlanner8 pipelines (I expect in the next 3 weeks)

@tkobayas 
Thanks for the fix 👍

**Pull request closed without merging**
