### PR TITLE
[KOGITO-3832] Bump to Kubernetes Client 4.12.0

### PR DESCRIPTION
**Pull request by ricardozanini**
Signed-off-by: Ricardo Zanini <zanini@redhat.com>

See: https://issues.redhat.com/browse/KOGITO-3832

The test has been disabled because of https://github.com/fabric8io/kubernetes-client/issues/2631

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.md)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Review by evacchi — APPROVED** [review]
I really thought this would have been enough too, but I guess it broke somewhere else too -- or I missed a few spots

**Comment by ricardozanini** [comment]
> I really thought this would have been enough too, but I guess it broke somewhere else too -- or I missed a few spots

I guess it broke in that OIDC thing. Let's see how the CI goes. wdyt?

**Comment by ricardozanini** [comment]
Not my fault:

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.kie.kogito.security.KeycloakSecurityCommonsServiceIT
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 5.479 s <<< FAILURE! - in org.kie.kogito.security.KeycloakSecurityCommonsServiceIT
[ERROR] meTest  Time elapsed: 0.009 s  <<< ERROR!
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
Caused by: java.lang.reflect.InvocationTargetException
Caused by: java.lang.RuntimeException: Unable to start Quarkus test resource org.kie.kogito.testcontainers.quarkus.KeycloakQuarkusTestResource@500bde5b
Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed
Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=jboss/keycloak:11.0.2, imagePullPolicy=DefaultPullPolicy())
Caused by: java.lang.ArrayIndexOutOfBoundsException: size=25 offset=0 byteCount=149

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   KeycloakSecurityCommonsServiceIT.meTest » Runtime java.lang.reflect.Invocation...
```

Jenkins retest this please

**Review by cristianonicolai — APPROVED** [review]

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Pull request merged**
