### PR TITLE
KOGITO-1555: (Quarkus Snapshot) Bump Jackson version

### PR DESCRIPTION
**Pull request by evacchi**

### CODE REVIEW

**Comment by evacchi** [comment]
@cristianonicolai apparently this breaks `kogito-apps` :(

**Comment by cristianonicolai** [comment]
@evacchi I seen this issue with other builds, yarn build is failing due to timeout, trying to fix it here https://github.com/kiegroup/kogito-apps/pull/123

**Comment by cristianonicolai** [comment]
@evacchi should we wait to merge this only if we upgrade?

**Comment by evacchi** [comment]
I've been building on CI quarkus snapshot to make sure it works. So if it doesn't break current tree, and it's green, we can go ahead and merge https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/blue/organizations/jenkins/custom%2Fevacchi%2Fcustom-quarkus-snapshot/detail/custom-quarkus-snapshot/11/pipeline

**Pull request merged**
