### PR TITLE
KOGITO-1546 XStreamUtils kie-soup refactoring

### PR DESCRIPTION
**Pull request by tarilabs**
Part of https://github.com/kiegroup/kie-soup/pull/137

### CODE REVIEW

**Comment by evacchi** [comment]
shouldn't this be green now that we bumped to kie 7.37? @mariofusco

**Comment by tarilabs** [comment]
Jenkins test again

**Comment by tarilabs** [comment]
wait @evacchi 
this has to wait 7.38
ref https://github.com/kiegroup/kie-soup/commit/ad7f088576805199b7c7e610d924e1e707ba4119

**Comment by evacchi** [comment]
oh ok @tarilabs my bad. :)

**Comment by tarilabs** [comment]
as of 14:27 it's green today
image

**Pull request merged**
