### PR TITLE
[KOGITO-4586] Fixing reflect-config.json generation

### PR DESCRIPTION
**Pull request by gitgabrio**
@danielezonca @evacchi  @jiripetrlik

See https://issues.redhat.com/browse/KOGITO-4586

This PR restore the reflect-config.json generation that was wrongly removed by https://issues.redhat.com/browse/DROOLS-5702

### CODE REVIEW

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by danielezonca** [comment]
Timeout

jenkins retest this please

**Comment by danielezonca** [comment]
Timeout again

jenkins retest this please

**Review by jiripetrlik — APPROVED** [review]
LGTM

**Pull request merged**
