### PR TITLE
[1.2.x] KOGITO-4316 Bump 7.49.0.Final

### PR DESCRIPTION
**Pull request by evacchi**
cherry pick #1016

### CODE REVIEW

**Review by mariofusco — APPROVED** [review]

**Comment by evacchi** [comment]
Jenkins please retest this

**Comment by evacchi** [comment]
@danielezonca a lot of failing tests re:test scenario. is this expected?

**Comment by danielezonca** [comment]
@evacchi 
https://github.com/evacchi/kogito-runtimes/pull/10

**Comment by radtriste** [comment]
PR check is hanging ...

Jenkins retest this

**Comment by radtriste** [comment]
FYI, seems a refresh problem, PR check is still running => https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/blue/organizations/jenkins/KIE%2Fkogito%2Fghprb-webhooks%2Fkogito-runtimes/detail/kogito-runtimes/2983/pipeline/

**Pull request merged**
