### PR TITLE
[1.3.x] KOGITO-4251 backport

### PR DESCRIPTION
**Pull request by mareknovotny**
backport of https://github.com/kiegroup/kogito-runtimes/pull/1059

Merge together with https://github.com/kiegroup/kogito-examples/pull/574 and https://github.com/kiegroup/kogito-apps/pull/659

### CODE REVIEW

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by radtriste** [comment]
jenkins retest this please

**Review by cristianonicolai — APPROVED** [review]

**Comment by mareknovotny** [comment]
probably again space problem on build node 
`Unable to create directory /home/jenkins/workspace/KIE/kogito/pullrequest/kogito-runtimes/kogito-apps/security-commons/target `

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
hmm, the latest comment from kie-ci bot is not from the latest run of CI https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/blue/organizations/jenkins/KIE%2Fkogito%2Fpullrequest%2Fkogito-runtimes/detail/kogito-runtimes/168/pipeline

**Review by radtriste — APPROVED** [review]

**Pull request merged**
