### PR TITLE
KOGITO-5203 - Validate ScriptTask language - only Java is supported a…

### PR DESCRIPTION
**Pull request by cristianonicolai**
…t this stage

### CODE REVIEW

**Comment by cristianonicolai** [comment]
Jenkins rerun apps tests

**Comment by cristianonicolai** [comment]
Jenkins rerun examples tests

**Comment by cristianonicolai** [comment]
Jenkins rerun apps tests

**Review by ricardozanini — APPROVED** [review]
How were those tests running up until now? LOL
Also, I think we need this for the 7.12?

**Review by radtriste — APPROVED** [review]

**Comment by cristianonicolai** [comment]
Jenkins rerun runtimes tests

**Comment by cristianonicolai** [comment]
Jenkins rerun apps tests

**Comment by cristianonicolai** [comment]
Jenkins rerun examples tests

**Comment by cristianonicolai** [comment]
Jenkins rerun apps tests

**Comment by cristianonicolai** [comment]
Jenkins rerun examples tests

**Comment by cristianonicolai** [comment]
Jenkins rerun examples tests

**Comment by cristianonicolai** [comment]
Jenkins rerun apps tests

**Review by tiagodolphine — APPROVED** [review]

**Pull request merged**
