### PR TITLE
disable ryuk

### PR DESCRIPTION
**Pull request by radtriste**
Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](CONTRIBUTING.md)
- [ ] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/master/kogito-ide-config)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

* <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

### CODE REVIEW

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by danielezonca** [comment]
Stuck with

```
09:39:08,325 [INFO] 2021-04-23 09:39:08.321  INFO 29194 --- [ream-1683599194] o.k.k.t.KogitoKafkaContainer             : STDOUT: [2021-04-23 13:39:08,320] DEBUG [Controller id=1] Topics not in preferred replica for broker 1 Map() (kafka.controller.KafkaController)
09:39:08,326 [INFO] 2021-04-23 09:39:08.321  INFO 29194 --- [ream-1683599194] o.k.k.t.KogitoKafkaContainer             : STDOUT: [2021-04-23 13:39:08,320] TRACE [Controller id=1] Leader imbalance ratio for broker 1 is 0.0 (kafka.controller.KafkaController)
09:44:03,117 [INFO] 2021-04-23 09:44:03.116  INFO 29194 --- [ream-1683599194] o.k.k.t.KogitoKafkaContainer             : STDOUT: [2021-04-23 13:44:03,115] INFO [GroupMetadataManager brokerId=1] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
09:44:08,323 [INFO] 2021-04-23 09:44:08.322  INFO 29194 --- [ream-1683599194] o.k.k.t.KogitoKafkaContainer             : STDOUT: [2021-04-23 13:44:08,321] INFO [Controller id=1] Processing automatic preferred replica leader election (kafka.controller.KafkaController)
09:44:08,324 [INFO] 2021-04-23 09:44:08.322  INFO 29194 --- [ream-1683599194] o.k.k.t.KogitoKafkaContainer             : STDOUT: [2021-04-23 13:44:08,321] TRACE [Controller id=1] Checking need to trigger auto leader balancing (kafka.controller.KafkaController)
09:44:08,324 [INFO] 2021-04-23 09:44:08.322  INFO 29194 --- [ream-1683599194] o.k.k.t.KogitoKafkaContainer             : STDOUT: [2021-04-23 13:44:08,322] DEBUG [Controller id=1] Preferred replicas by broker Map(1 -> Map(__confluent.support.metrics-0 -> Vector(1))) (kafka.controller.KafkaController)
09:44:08,325 [INFO] 2021-04-23 09:44:08.322  INFO 29194 --- [ream-1683599194] o.k.k.t.KogitoKafkaContainer             : STDOUT: [2021-04-23 13:44:08,322] DEBUG [Controller id=1] Topics not in preferred replica for broker 1 Map() (kafka.controller.KafkaController)
09:44:08,326 [INFO] 2021-04-23 09:44:08.322  INFO 29194 --- [ream-1683599194] o.k.k.t.KogitoKafkaContainer             : STDOUT: [2021-04-23 13:44:08,322] TRACE [Controller id=1] Leader imbalance ratio for broker 1 is 0.0 (kafka.controller.KafkaController)
09:49:08,324 [INFO] 2021-04-23 09:49:08.323  INFO 29194 --- [ream-1683599194] o.k.k.t.KogitoKafkaContainer             : STDOUT: [2021-04-23 13:49:08,322] INFO [Controller id=1] Processing automatic preferred replica leader election (kafka.controller.KafkaController)
09:49:08,325 [INFO] 2021-04-23 09:49:08.323  INFO 29194 --- [ream-1683599194] o.k.k.t.KogitoKafkaContainer             : STDOUT: [2021-04-23 13:49:08,322] TRACE [Controller id=1] Checking need to trigger auto leader balancing (kafka.controller.KafkaController)
09:49:08,325 [INFO] 2021-04-23 09:49:08.323  INFO 29194 --- [ream-1683599194] o.k.k.t.KogitoKafkaContainer             : STDOUT: [2021-04-23 13:49:08,323] DEBUG [Controller id=1] Preferred replicas by broker Map(1 -> Map(__confluent.support.metrics-0 -> Vector(1))) (kafka.controller.KafkaController)
09:49:08,326 [INFO] 2021-04-23 09:49:08.323  INFO 29194 --- [ream-1683599194] o.k.k.t.KogitoKafkaContainer             : STDOUT: [2021-04-23 13:49:08,323] DEBUG [Controller id=1] Topics not in preferred replica for broker 1 Map() (kafka.controller.KafkaController)
09:49:08,326 [INFO] 2021-04-23 09:49:08.323  INFO 29194 --- [ream-1683599194] o.k.k.t.KogitoKafkaContainer             : STDOUT: [2021-04-23 13:49:08,323] TRACE [Controller id=1] Leader imbalance ratio for broker 1 is 0.0 (kafka.controller.KafkaController)
```

**Comment by radtriste** [comment]
yeah that one was not with much hope ... I have more faith in https://github.com/kiegroup/kogito-runtimes/pull/1255

**Comment by danielezonca** [comment]
@radtriste 
Well that PR is already blocked 😞 
```
09:39:20,298 [INFO] -------------------------------------------------------
09:39:20,298 [INFO]  T E S T S
09:39:20,298 [INFO] -------------------------------------------------------
09:39:21,272 [INFO] Running org.kie.kogito.persistence.kafka.KafkaProcessInstancesIT
```

**Comment by radtriste** [comment]
:(

**Pull request closed without merging**
