### PR TITLE
[KOGITO-6491] Fix paths handling on Windows for OpenAPI Codegen

### LINKED ISSUE #1825: Can not package on Windows10
Hi, 
I'm trying Kogito wtih serverless workflow by running the kogito-examples.But I can not package the example project on Windows, while there seems to be no problem when I package on CentOS.

On Windows, the generated openapi sources are located in ".\kogito-examples-main\serverless-workflow-temperature-conversion\conversion-workflow\target\generated-sources\kogito\\**src\main\java**\org\kie\kogito\app\openapi\client" 

Is this because the following codes do not fit windows, or Kogito only supports linux system?
https://github.com/kiegroup/kogito-runtimes/blob/49c622f08f3803d27d0585adfdeabe93200f642e/kogito-codegen-modules/kogito-codegen-openapi/src/main/java/org/kie/kogito/codegen/openapi/client/GeneratedFileBuilder.java#L68

The following file tree is what Kogito generated after “mvn package”，and I ran into an error “The declared package "org.kie.kogito.app.openapi.client.c3BlY3MvbXVsdGlwbGljYXRpb24ueWFtbA___multiplication" does not match the expected package "src.main.java.org.kie.kogito.app.openapi.client.c3BlY3MvbXVsdGlwbGljYXRpb24ueWFtbA___multiplication“

└─kogito
---├─org
---│---└─kie
---│------└─kogito
---│---------├─app
---│---------├─handlers
---│---------└─serverless
---└─src
------└─main
---------└─java
------------└─org
---------------└─kie
------------------└─kogito
---------------------└─app
------------------------└─openapi
---------------------------└─client
------------------------------├─c3BlY3MvbXVsdGlwbGljYXRpb24ueWFtbA___multiplication
------------------------------│  └─auth
------------------------------└─c3BlY3Mvc3VidHJhY3Rpb24ueWFtbA___subtraction
---------------------------------└─auth

### PR DESCRIPTION
**Pull request by ricardozanini**
Signed-off-by: Ricardo Zanini <zanini@redhat.com>

Fixes #1825 

See: https://issues.redhat.com/browse/KOGITO-6491

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.md)
- [x] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/main/kogito-build/kogito-ide-config)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Run all builds</b>  
  Please add comment: <b>Jenkins retest this</b>

* <b>Run (or rerun) specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] tests</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Run (or rerun) LTS specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

* <b>Run (or rerun) native specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] native</b>

* <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

### CODE REVIEW

**Review by fjtirado — APPROVED** [review]

**Comment by ricardozanini** [comment]
Jenkins rerun kogito-examples tests
Jenkins rerun kogito-apps tests

**Comment by ricardozanini** [comment]
Jenkins rerun kogito-apps tests

**Comment by ricardozanini** [comment]
Jenkins rerun kogito-examples tests

**Comment by ricardozanini** [comment]
Jenkins rerun kogito-examples tests

**Comment by ricardozanini** [comment]
Jenkins rerun kogito-examples tests

**Pull request merged**
