### PR TITLE
[1.6.x] KOGITO-5014 Bump KIE 7.53.1.Final

### PR DESCRIPTION
**Pull request by evacchi**

### CODE REVIEW

**Comment by evacchi** [comment]
I am confused

jenkins please retest this

**Comment by triceo** [comment]
Jenkins retest this.

**Comment by evacchi** [comment]
> script returned exit code 143

jenkins please retest this

**Review by radtriste — APPROVED** [review]

**Review by danielezonca — APPROVED** [review]

**Comment by evacchi** [comment]
[You had a bad day](http://www.youtube.com/watch?v=gH476CxJxfg "Bad Day")

jenkins please retest this

**Pull request merged**
