### PR TITLE
[KOGITO-4053] Ignore empty fields in CloudEvents

### PR DESCRIPTION
**Pull request by ruromero**
Fix https://issues.redhat.com/browse/KOGITO-4053

Signed-off-by: ruromero <rromerom@redhat.com>

### CODE REVIEW

**Review by ricardozanini — APPROVED** [review]
Looks good to me! just take a look in the CI error please.

**Review by tiagodolphine — APPROVED** [review]

**Comment by ruromero** [comment]
jenkins retest this

```
fatal: unable to access 'https://github.com/kiegroup/kogito-runtimes.git/': Failed connect to github.com:443; Connection timed out
```

**Comment by ruromero** [comment]
jenkins retest this

**Comment by ruromero** [comment]
jenkins retest this

**Pull request merged**
