### PR TITLE
[1.0.x] KOGITO-3862 - Make Docker images used by TestContainers compatible wi…

### PR DESCRIPTION
**Pull request by cristianonicolai**
Assembly:
- https://github.com/kiegroup/kogito-runtimes/pull/900
- https://github.com/kiegroup/kogito-examples/pull/461

### CODE REVIEW

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Review by mbiarnes — APPROVED** [review]
+1

**Review by radtriste — APPROVED** [review]

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Pull request merged**
