### PR TITLE
[1.0.x] KOGITO-3876 Bump to Quarkus 1.10.0.Final

### PR DESCRIPTION
**Pull request by evacchi**
https://issues.redhat.com/browse/KOGITO-3876
related: https://github.com/kiegroup/kogito-examples/pull/462

----

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.md)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by evacchi** [comment]
@cristianonicolai @tiagodolphine @radtriste I am creating this PR already even though the artifacts have not been deployed yet; I hope tomorrow Cristiano will be able to retrigger and find them there :)

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by tiagodolphine** [comment]
jenkins retest this

**Review by tiagodolphine — APPROVED** [review]

**Comment by evacchi** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by radtriste** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Review by cristianonicolai — APPROVED** [review]

**Pull request merged**
