### PR TITLE
KOGITO-5295: Removing Infinispan dependencies from SpringBoot IT caus…

### PR DESCRIPTION
**Pull request by nmirasch**
…es errors in process-svg IT

Jira: https://issues.redhat.com/browse/KOGITO-5295 

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Run all builds</b>  
  Please add comment: <b>Jenkins retest this</b>

* <b>Run (or rerun) specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [runtimes|optaplanner|apps|examples] tests</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Run (or rerun) LTS specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [runtimes|optaplanner|apps|examples] LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

* <b>Run (or rerun) native specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [runtimes|optaplanner|apps|examples] native</b>

* <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

### CODE REVIEW

**Comment by nmirasch** [comment]
Jenkins rerun runtimes tests

**Comment by nmirasch** [comment]
Jenkins rerun apps tests

**Comment by nmirasch** [comment]
Jenkins rerun examples tests

**Comment by cristianonicolai** [comment]
Jenkins rerun examples tests

**Review by cristianonicolai — APPROVED** [review]

**Comment by cristianonicolai** [comment]
@nmirasch I think `<container.image.infinispan>` can also be removed

**Comment by nmirasch** [comment]
> @nmirasch I think `<container.image.infinispan>` can also be removed

@cristianonicolai I thought this jira was a matter of checking the dependences that couldn't be removed because of the failing process-svg IT test. I see you have generated that removal in https://github.com/kiegroup/kogito-runtimes/pull/1444. Do you need I do anything there?

**Pull request merged**
