### PR TITLE
KOGITO-5748 - Public API: Straight-Through Process Modules (Incubatio…

### PR DESCRIPTION
**Pull request by MarianMacik**
…n) - fix modules organization

FYI @evacchi we need to have a way to exclude IT modules from the build. IT modules were included to default modules by #1547 probably by a mistake.

### CODE REVIEW

**Comment by MarianMacik** [comment]
jenkins rerun examples tests

**Review by jstastny-cz — APPROVED** [review]
LGTM, good catch.

**Comment by MarianMacik** [comment]
Jenkins rerun examples tests

**Comment by MarianMacik** [comment]
Jenkins rerun examples tests

**Comment by MarianMacik** [comment]
Jenkins rerun apps tests

**Comment by MarianMacik** [comment]
Jenkins rerun examples tests

**Comment by MarianMacik** [comment]
Examples fails are unrelated, they are failing also on other PRs.

**Pull request merged**
